// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/runtime/p2p/request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fp2p_2frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fp2p_2frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "protocol/runtime/p2p/type.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2fruntime_2fp2p_2frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fruntime_2fp2p_2frequest_2eproto {
  static const uint32_t offsets[];
};
namespace axcl {
namespace runtime {
namespace p2p {
namespace request {
class BandWidthTestConfig;
struct BandWidthTestConfigDefaultTypeInternal;
extern BandWidthTestConfigDefaultTypeInternal _BandWidthTestConfig_default_instance_;
class Body;
struct BodyDefaultTypeInternal;
extern BodyDefaultTypeInternal _Body_default_instance_;
class Config;
struct ConfigDefaultTypeInternal;
extern ConfigDefaultTypeInternal _Config_default_instance_;
class Head;
struct HeadDefaultTypeInternal;
extern HeadDefaultTypeInternal _Head_default_instance_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
}  // namespace request
}  // namespace p2p
}  // namespace runtime
}  // namespace axcl
PROTOBUF_NAMESPACE_OPEN
template<> ::axcl::runtime::p2p::request::BandWidthTestConfig* Arena::CreateMaybeMessage<::axcl::runtime::p2p::request::BandWidthTestConfig>(Arena*);
template<> ::axcl::runtime::p2p::request::Body* Arena::CreateMaybeMessage<::axcl::runtime::p2p::request::Body>(Arena*);
template<> ::axcl::runtime::p2p::request::Config* Arena::CreateMaybeMessage<::axcl::runtime::p2p::request::Config>(Arena*);
template<> ::axcl::runtime::p2p::request::Head* Arena::CreateMaybeMessage<::axcl::runtime::p2p::request::Head>(Arena*);
template<> ::axcl::runtime::p2p::request::Payload* Arena::CreateMaybeMessage<::axcl::runtime::p2p::request::Payload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace axcl {
namespace runtime {
namespace p2p {
namespace request {

// ===================================================================

class Head final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.p2p.request.Head) */ {
 public:
  inline Head() : Head(nullptr) {}
  ~Head() override;
  explicit PROTOBUF_CONSTEXPR Head(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Head(const Head& from);
  Head(Head&& from) noexcept
    : Head() {
    *this = ::std::move(from);
  }

  inline Head& operator=(const Head& from) {
    CopyFrom(from);
    return *this;
  }
  inline Head& operator=(Head&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Head& default_instance() {
    return *internal_default_instance();
  }
  static inline const Head* internal_default_instance() {
    return reinterpret_cast<const Head*>(
               &_Head_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Head& a, Head& b) {
    a.Swap(&b);
  }
  inline void Swap(Head* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Head* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Head* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Head>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Head& from);
  void MergeFrom(const Head& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Head* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.p2p.request.Head";
  }
  protected:
  explicit Head(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApiFieldNumber = 1,
  };
  // .axcl.runtime.p2p.Api api = 1;
  void clear_api();
  ::axcl::runtime::p2p::Api api() const;
  void set_api(::axcl::runtime::p2p::Api value);
  private:
  ::axcl::runtime::p2p::Api _internal_api() const;
  void _internal_set_api(::axcl::runtime::p2p::Api value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.p2p.request.Head)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int api_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fp2p_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Config final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.p2p.request.Config) */ {
 public:
  inline Config() : Config(nullptr) {}
  ~Config() override;
  explicit PROTOBUF_CONSTEXPR Config(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Config(const Config& from);
  Config(Config&& from) noexcept
    : Config() {
    *this = ::std::move(from);
  }

  inline Config& operator=(const Config& from) {
    CopyFrom(from);
    return *this;
  }
  inline Config& operator=(Config&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Config& default_instance() {
    return *internal_default_instance();
  }
  static inline const Config* internal_default_instance() {
    return reinterpret_cast<const Config*>(
               &_Config_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Config& a, Config& b) {
    a.Swap(&b);
  }
  inline void Swap(Config* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Config* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Config* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Config>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Config& from);
  void MergeFrom(const Config& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Config* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.p2p.request.Config";
  }
  protected:
  explicit Config(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDmaPciAddrFieldNumber = 2,
    kMboxPciAddrFieldNumber = 3,
    kTargetIdFieldNumber = 1,
    kCmmSizeFieldNumber = 5,
    kCmmPhyAddrFieldNumber = 4,
  };
  // uint64 dma_pci_addr = 2;
  void clear_dma_pci_addr();
  uint64_t dma_pci_addr() const;
  void set_dma_pci_addr(uint64_t value);
  private:
  uint64_t _internal_dma_pci_addr() const;
  void _internal_set_dma_pci_addr(uint64_t value);
  public:

  // uint64 mbox_pci_addr = 3;
  void clear_mbox_pci_addr();
  uint64_t mbox_pci_addr() const;
  void set_mbox_pci_addr(uint64_t value);
  private:
  uint64_t _internal_mbox_pci_addr() const;
  void _internal_set_mbox_pci_addr(uint64_t value);
  public:

  // uint32 target_id = 1;
  void clear_target_id();
  uint32_t target_id() const;
  void set_target_id(uint32_t value);
  private:
  uint32_t _internal_target_id() const;
  void _internal_set_target_id(uint32_t value);
  public:

  // uint32 cmm_size = 5;
  void clear_cmm_size();
  uint32_t cmm_size() const;
  void set_cmm_size(uint32_t value);
  private:
  uint32_t _internal_cmm_size() const;
  void _internal_set_cmm_size(uint32_t value);
  public:

  // uint64 cmm_phy_addr = 4;
  void clear_cmm_phy_addr();
  uint64_t cmm_phy_addr() const;
  void set_cmm_phy_addr(uint64_t value);
  private:
  uint64_t _internal_cmm_phy_addr() const;
  void _internal_set_cmm_phy_addr(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.p2p.request.Config)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint64_t dma_pci_addr_;
  uint64_t mbox_pci_addr_;
  uint32_t target_id_;
  uint32_t cmm_size_;
  uint64_t cmm_phy_addr_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fp2p_2frequest_2eproto;
};
// -------------------------------------------------------------------

class BandWidthTestConfig final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.p2p.request.BandWidthTestConfig) */ {
 public:
  inline BandWidthTestConfig() : BandWidthTestConfig(nullptr) {}
  ~BandWidthTestConfig() override;
  explicit PROTOBUF_CONSTEXPR BandWidthTestConfig(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BandWidthTestConfig(const BandWidthTestConfig& from);
  BandWidthTestConfig(BandWidthTestConfig&& from) noexcept
    : BandWidthTestConfig() {
    *this = ::std::move(from);
  }

  inline BandWidthTestConfig& operator=(const BandWidthTestConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline BandWidthTestConfig& operator=(BandWidthTestConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const BandWidthTestConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const BandWidthTestConfig* internal_default_instance() {
    return reinterpret_cast<const BandWidthTestConfig*>(
               &_BandWidthTestConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(BandWidthTestConfig& a, BandWidthTestConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(BandWidthTestConfig* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BandWidthTestConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BandWidthTestConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BandWidthTestConfig>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const BandWidthTestConfig& from);
  void MergeFrom(const BandWidthTestConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BandWidthTestConfig* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.p2p.request.BandWidthTestConfig";
  }
  protected:
  explicit BandWidthTestConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTargetIdFieldNumber = 1,
    kLoopCountFieldNumber = 2,
    kLoopIntervalFieldNumber = 3,
    kChunkSizeFieldNumber = 4,
  };
  // uint32 target_id = 1;
  void clear_target_id();
  uint32_t target_id() const;
  void set_target_id(uint32_t value);
  private:
  uint32_t _internal_target_id() const;
  void _internal_set_target_id(uint32_t value);
  public:

  // uint32 loop_count = 2;
  void clear_loop_count();
  uint32_t loop_count() const;
  void set_loop_count(uint32_t value);
  private:
  uint32_t _internal_loop_count() const;
  void _internal_set_loop_count(uint32_t value);
  public:

  // uint32 loop_interval = 3;
  void clear_loop_interval();
  uint32_t loop_interval() const;
  void set_loop_interval(uint32_t value);
  private:
  uint32_t _internal_loop_interval() const;
  void _internal_set_loop_interval(uint32_t value);
  public:

  // uint32 chunk_size = 4;
  void clear_chunk_size();
  uint32_t chunk_size() const;
  void set_chunk_size(uint32_t value);
  private:
  uint32_t _internal_chunk_size() const;
  void _internal_set_chunk_size(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.p2p.request.BandWidthTestConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t target_id_;
  uint32_t loop_count_;
  uint32_t loop_interval_;
  uint32_t chunk_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fp2p_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Body final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.p2p.request.Body) */ {
 public:
  inline Body() : Body(nullptr) {}
  ~Body() override;
  explicit PROTOBUF_CONSTEXPR Body(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Body(const Body& from);
  Body(Body&& from) noexcept
    : Body() {
    *this = ::std::move(from);
  }

  inline Body& operator=(const Body& from) {
    CopyFrom(from);
    return *this;
  }
  inline Body& operator=(Body&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Body& default_instance() {
    return *internal_default_instance();
  }
  static inline const Body* internal_default_instance() {
    return reinterpret_cast<const Body*>(
               &_Body_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Body& a, Body& b) {
    a.Swap(&b);
  }
  inline void Swap(Body* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Body* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Body* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Body>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Body& from);
  void MergeFrom(const Body& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Body* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.p2p.request.Body";
  }
  protected:
  explicit Body(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kConfigFieldNumber = 1,
    kBwtConfigFieldNumber = 3,
    kTargetIdFieldNumber = 2,
    kBwtTimeoutFieldNumber = 4,
  };
  // repeated .axcl.runtime.p2p.request.Config config = 1;
  int config_size() const;
  private:
  int _internal_config_size() const;
  public:
  void clear_config();
  ::axcl::runtime::p2p::request::Config* mutable_config(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::axcl::runtime::p2p::request::Config >*
      mutable_config();
  private:
  const ::axcl::runtime::p2p::request::Config& _internal_config(int index) const;
  ::axcl::runtime::p2p::request::Config* _internal_add_config();
  public:
  const ::axcl::runtime::p2p::request::Config& config(int index) const;
  ::axcl::runtime::p2p::request::Config* add_config();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::axcl::runtime::p2p::request::Config >&
      config() const;

  // repeated .axcl.runtime.p2p.request.BandWidthTestConfig bwt_config = 3;
  int bwt_config_size() const;
  private:
  int _internal_bwt_config_size() const;
  public:
  void clear_bwt_config();
  ::axcl::runtime::p2p::request::BandWidthTestConfig* mutable_bwt_config(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::axcl::runtime::p2p::request::BandWidthTestConfig >*
      mutable_bwt_config();
  private:
  const ::axcl::runtime::p2p::request::BandWidthTestConfig& _internal_bwt_config(int index) const;
  ::axcl::runtime::p2p::request::BandWidthTestConfig* _internal_add_bwt_config();
  public:
  const ::axcl::runtime::p2p::request::BandWidthTestConfig& bwt_config(int index) const;
  ::axcl::runtime::p2p::request::BandWidthTestConfig* add_bwt_config();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::axcl::runtime::p2p::request::BandWidthTestConfig >&
      bwt_config() const;

  // optional uint32 target_id = 2;
  bool has_target_id() const;
  private:
  bool _internal_has_target_id() const;
  public:
  void clear_target_id();
  uint32_t target_id() const;
  void set_target_id(uint32_t value);
  private:
  uint32_t _internal_target_id() const;
  void _internal_set_target_id(uint32_t value);
  public:

  // optional int32 bwt_timeout = 4;
  bool has_bwt_timeout() const;
  private:
  bool _internal_has_bwt_timeout() const;
  public:
  void clear_bwt_timeout();
  int32_t bwt_timeout() const;
  void set_bwt_timeout(int32_t value);
  private:
  int32_t _internal_bwt_timeout() const;
  void _internal_set_bwt_timeout(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.p2p.request.Body)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::axcl::runtime::p2p::request::Config > config_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::axcl::runtime::p2p::request::BandWidthTestConfig > bwt_config_;
  uint32_t target_id_;
  int32_t bwt_timeout_;
  friend struct ::TableStruct_protocol_2fruntime_2fp2p_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.p2p.request.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Payload& from);
  void MergeFrom(const Payload& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.p2p.request.Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeadFieldNumber = 1,
    kBodyFieldNumber = 2,
  };
  // .axcl.runtime.p2p.request.Head head = 1;
  bool has_head() const;
  private:
  bool _internal_has_head() const;
  public:
  void clear_head();
  const ::axcl::runtime::p2p::request::Head& head() const;
  PROTOBUF_NODISCARD ::axcl::runtime::p2p::request::Head* release_head();
  ::axcl::runtime::p2p::request::Head* mutable_head();
  void set_allocated_head(::axcl::runtime::p2p::request::Head* head);
  private:
  const ::axcl::runtime::p2p::request::Head& _internal_head() const;
  ::axcl::runtime::p2p::request::Head* _internal_mutable_head();
  public:
  void unsafe_arena_set_allocated_head(
      ::axcl::runtime::p2p::request::Head* head);
  ::axcl::runtime::p2p::request::Head* unsafe_arena_release_head();

  // .axcl.runtime.p2p.request.Body body = 2;
  bool has_body() const;
  private:
  bool _internal_has_body() const;
  public:
  void clear_body();
  const ::axcl::runtime::p2p::request::Body& body() const;
  PROTOBUF_NODISCARD ::axcl::runtime::p2p::request::Body* release_body();
  ::axcl::runtime::p2p::request::Body* mutable_body();
  void set_allocated_body(::axcl::runtime::p2p::request::Body* body);
  private:
  const ::axcl::runtime::p2p::request::Body& _internal_body() const;
  ::axcl::runtime::p2p::request::Body* _internal_mutable_body();
  public:
  void unsafe_arena_set_allocated_body(
      ::axcl::runtime::p2p::request::Body* body);
  ::axcl::runtime::p2p::request::Body* unsafe_arena_release_body();

  // @@protoc_insertion_point(class_scope:axcl.runtime.p2p.request.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::axcl::runtime::p2p::request::Head* head_;
  ::axcl::runtime::p2p::request::Body* body_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fp2p_2frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Head

// .axcl.runtime.p2p.Api api = 1;
inline void Head::clear_api() {
  api_ = 0;
}
inline ::axcl::runtime::p2p::Api Head::_internal_api() const {
  return static_cast< ::axcl::runtime::p2p::Api >(api_);
}
inline ::axcl::runtime::p2p::Api Head::api() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Head.api)
  return _internal_api();
}
inline void Head::_internal_set_api(::axcl::runtime::p2p::Api value) {
  
  api_ = value;
}
inline void Head::set_api(::axcl::runtime::p2p::Api value) {
  _internal_set_api(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.Head.api)
}

// -------------------------------------------------------------------

// Config

// uint32 target_id = 1;
inline void Config::clear_target_id() {
  target_id_ = 0u;
}
inline uint32_t Config::_internal_target_id() const {
  return target_id_;
}
inline uint32_t Config::target_id() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Config.target_id)
  return _internal_target_id();
}
inline void Config::_internal_set_target_id(uint32_t value) {
  
  target_id_ = value;
}
inline void Config::set_target_id(uint32_t value) {
  _internal_set_target_id(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.Config.target_id)
}

// uint64 dma_pci_addr = 2;
inline void Config::clear_dma_pci_addr() {
  dma_pci_addr_ = uint64_t{0u};
}
inline uint64_t Config::_internal_dma_pci_addr() const {
  return dma_pci_addr_;
}
inline uint64_t Config::dma_pci_addr() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Config.dma_pci_addr)
  return _internal_dma_pci_addr();
}
inline void Config::_internal_set_dma_pci_addr(uint64_t value) {
  
  dma_pci_addr_ = value;
}
inline void Config::set_dma_pci_addr(uint64_t value) {
  _internal_set_dma_pci_addr(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.Config.dma_pci_addr)
}

// uint64 mbox_pci_addr = 3;
inline void Config::clear_mbox_pci_addr() {
  mbox_pci_addr_ = uint64_t{0u};
}
inline uint64_t Config::_internal_mbox_pci_addr() const {
  return mbox_pci_addr_;
}
inline uint64_t Config::mbox_pci_addr() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Config.mbox_pci_addr)
  return _internal_mbox_pci_addr();
}
inline void Config::_internal_set_mbox_pci_addr(uint64_t value) {
  
  mbox_pci_addr_ = value;
}
inline void Config::set_mbox_pci_addr(uint64_t value) {
  _internal_set_mbox_pci_addr(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.Config.mbox_pci_addr)
}

// uint64 cmm_phy_addr = 4;
inline void Config::clear_cmm_phy_addr() {
  cmm_phy_addr_ = uint64_t{0u};
}
inline uint64_t Config::_internal_cmm_phy_addr() const {
  return cmm_phy_addr_;
}
inline uint64_t Config::cmm_phy_addr() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Config.cmm_phy_addr)
  return _internal_cmm_phy_addr();
}
inline void Config::_internal_set_cmm_phy_addr(uint64_t value) {
  
  cmm_phy_addr_ = value;
}
inline void Config::set_cmm_phy_addr(uint64_t value) {
  _internal_set_cmm_phy_addr(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.Config.cmm_phy_addr)
}

// uint32 cmm_size = 5;
inline void Config::clear_cmm_size() {
  cmm_size_ = 0u;
}
inline uint32_t Config::_internal_cmm_size() const {
  return cmm_size_;
}
inline uint32_t Config::cmm_size() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Config.cmm_size)
  return _internal_cmm_size();
}
inline void Config::_internal_set_cmm_size(uint32_t value) {
  
  cmm_size_ = value;
}
inline void Config::set_cmm_size(uint32_t value) {
  _internal_set_cmm_size(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.Config.cmm_size)
}

// -------------------------------------------------------------------

// BandWidthTestConfig

// uint32 target_id = 1;
inline void BandWidthTestConfig::clear_target_id() {
  target_id_ = 0u;
}
inline uint32_t BandWidthTestConfig::_internal_target_id() const {
  return target_id_;
}
inline uint32_t BandWidthTestConfig::target_id() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.BandWidthTestConfig.target_id)
  return _internal_target_id();
}
inline void BandWidthTestConfig::_internal_set_target_id(uint32_t value) {
  
  target_id_ = value;
}
inline void BandWidthTestConfig::set_target_id(uint32_t value) {
  _internal_set_target_id(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.BandWidthTestConfig.target_id)
}

// uint32 loop_count = 2;
inline void BandWidthTestConfig::clear_loop_count() {
  loop_count_ = 0u;
}
inline uint32_t BandWidthTestConfig::_internal_loop_count() const {
  return loop_count_;
}
inline uint32_t BandWidthTestConfig::loop_count() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.BandWidthTestConfig.loop_count)
  return _internal_loop_count();
}
inline void BandWidthTestConfig::_internal_set_loop_count(uint32_t value) {
  
  loop_count_ = value;
}
inline void BandWidthTestConfig::set_loop_count(uint32_t value) {
  _internal_set_loop_count(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.BandWidthTestConfig.loop_count)
}

// uint32 loop_interval = 3;
inline void BandWidthTestConfig::clear_loop_interval() {
  loop_interval_ = 0u;
}
inline uint32_t BandWidthTestConfig::_internal_loop_interval() const {
  return loop_interval_;
}
inline uint32_t BandWidthTestConfig::loop_interval() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.BandWidthTestConfig.loop_interval)
  return _internal_loop_interval();
}
inline void BandWidthTestConfig::_internal_set_loop_interval(uint32_t value) {
  
  loop_interval_ = value;
}
inline void BandWidthTestConfig::set_loop_interval(uint32_t value) {
  _internal_set_loop_interval(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.BandWidthTestConfig.loop_interval)
}

// uint32 chunk_size = 4;
inline void BandWidthTestConfig::clear_chunk_size() {
  chunk_size_ = 0u;
}
inline uint32_t BandWidthTestConfig::_internal_chunk_size() const {
  return chunk_size_;
}
inline uint32_t BandWidthTestConfig::chunk_size() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.BandWidthTestConfig.chunk_size)
  return _internal_chunk_size();
}
inline void BandWidthTestConfig::_internal_set_chunk_size(uint32_t value) {
  
  chunk_size_ = value;
}
inline void BandWidthTestConfig::set_chunk_size(uint32_t value) {
  _internal_set_chunk_size(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.BandWidthTestConfig.chunk_size)
}

// -------------------------------------------------------------------

// Body

// repeated .axcl.runtime.p2p.request.Config config = 1;
inline int Body::_internal_config_size() const {
  return config_.size();
}
inline int Body::config_size() const {
  return _internal_config_size();
}
inline void Body::clear_config() {
  config_.Clear();
}
inline ::axcl::runtime::p2p::request::Config* Body::mutable_config(int index) {
  // @@protoc_insertion_point(field_mutable:axcl.runtime.p2p.request.Body.config)
  return config_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::axcl::runtime::p2p::request::Config >*
Body::mutable_config() {
  // @@protoc_insertion_point(field_mutable_list:axcl.runtime.p2p.request.Body.config)
  return &config_;
}
inline const ::axcl::runtime::p2p::request::Config& Body::_internal_config(int index) const {
  return config_.Get(index);
}
inline const ::axcl::runtime::p2p::request::Config& Body::config(int index) const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Body.config)
  return _internal_config(index);
}
inline ::axcl::runtime::p2p::request::Config* Body::_internal_add_config() {
  return config_.Add();
}
inline ::axcl::runtime::p2p::request::Config* Body::add_config() {
  ::axcl::runtime::p2p::request::Config* _add = _internal_add_config();
  // @@protoc_insertion_point(field_add:axcl.runtime.p2p.request.Body.config)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::axcl::runtime::p2p::request::Config >&
Body::config() const {
  // @@protoc_insertion_point(field_list:axcl.runtime.p2p.request.Body.config)
  return config_;
}

// optional uint32 target_id = 2;
inline bool Body::_internal_has_target_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Body::has_target_id() const {
  return _internal_has_target_id();
}
inline void Body::clear_target_id() {
  target_id_ = 0u;
  _has_bits_[0] &= ~0x00000001u;
}
inline uint32_t Body::_internal_target_id() const {
  return target_id_;
}
inline uint32_t Body::target_id() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Body.target_id)
  return _internal_target_id();
}
inline void Body::_internal_set_target_id(uint32_t value) {
  _has_bits_[0] |= 0x00000001u;
  target_id_ = value;
}
inline void Body::set_target_id(uint32_t value) {
  _internal_set_target_id(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.Body.target_id)
}

// repeated .axcl.runtime.p2p.request.BandWidthTestConfig bwt_config = 3;
inline int Body::_internal_bwt_config_size() const {
  return bwt_config_.size();
}
inline int Body::bwt_config_size() const {
  return _internal_bwt_config_size();
}
inline void Body::clear_bwt_config() {
  bwt_config_.Clear();
}
inline ::axcl::runtime::p2p::request::BandWidthTestConfig* Body::mutable_bwt_config(int index) {
  // @@protoc_insertion_point(field_mutable:axcl.runtime.p2p.request.Body.bwt_config)
  return bwt_config_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::axcl::runtime::p2p::request::BandWidthTestConfig >*
Body::mutable_bwt_config() {
  // @@protoc_insertion_point(field_mutable_list:axcl.runtime.p2p.request.Body.bwt_config)
  return &bwt_config_;
}
inline const ::axcl::runtime::p2p::request::BandWidthTestConfig& Body::_internal_bwt_config(int index) const {
  return bwt_config_.Get(index);
}
inline const ::axcl::runtime::p2p::request::BandWidthTestConfig& Body::bwt_config(int index) const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Body.bwt_config)
  return _internal_bwt_config(index);
}
inline ::axcl::runtime::p2p::request::BandWidthTestConfig* Body::_internal_add_bwt_config() {
  return bwt_config_.Add();
}
inline ::axcl::runtime::p2p::request::BandWidthTestConfig* Body::add_bwt_config() {
  ::axcl::runtime::p2p::request::BandWidthTestConfig* _add = _internal_add_bwt_config();
  // @@protoc_insertion_point(field_add:axcl.runtime.p2p.request.Body.bwt_config)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::axcl::runtime::p2p::request::BandWidthTestConfig >&
Body::bwt_config() const {
  // @@protoc_insertion_point(field_list:axcl.runtime.p2p.request.Body.bwt_config)
  return bwt_config_;
}

// optional int32 bwt_timeout = 4;
inline bool Body::_internal_has_bwt_timeout() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Body::has_bwt_timeout() const {
  return _internal_has_bwt_timeout();
}
inline void Body::clear_bwt_timeout() {
  bwt_timeout_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline int32_t Body::_internal_bwt_timeout() const {
  return bwt_timeout_;
}
inline int32_t Body::bwt_timeout() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Body.bwt_timeout)
  return _internal_bwt_timeout();
}
inline void Body::_internal_set_bwt_timeout(int32_t value) {
  _has_bits_[0] |= 0x00000002u;
  bwt_timeout_ = value;
}
inline void Body::set_bwt_timeout(int32_t value) {
  _internal_set_bwt_timeout(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.request.Body.bwt_timeout)
}

// -------------------------------------------------------------------

// Payload

// .axcl.runtime.p2p.request.Head head = 1;
inline bool Payload::_internal_has_head() const {
  return this != internal_default_instance() && head_ != nullptr;
}
inline bool Payload::has_head() const {
  return _internal_has_head();
}
inline void Payload::clear_head() {
  if (GetArenaForAllocation() == nullptr && head_ != nullptr) {
    delete head_;
  }
  head_ = nullptr;
}
inline const ::axcl::runtime::p2p::request::Head& Payload::_internal_head() const {
  const ::axcl::runtime::p2p::request::Head* p = head_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::p2p::request::Head&>(
      ::axcl::runtime::p2p::request::_Head_default_instance_);
}
inline const ::axcl::runtime::p2p::request::Head& Payload::head() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Payload.head)
  return _internal_head();
}
inline void Payload::unsafe_arena_set_allocated_head(
    ::axcl::runtime::p2p::request::Head* head) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(head_);
  }
  head_ = head;
  if (head) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.p2p.request.Payload.head)
}
inline ::axcl::runtime::p2p::request::Head* Payload::release_head() {
  
  ::axcl::runtime::p2p::request::Head* temp = head_;
  head_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::p2p::request::Head* Payload::unsafe_arena_release_head() {
  // @@protoc_insertion_point(field_release:axcl.runtime.p2p.request.Payload.head)
  
  ::axcl::runtime::p2p::request::Head* temp = head_;
  head_ = nullptr;
  return temp;
}
inline ::axcl::runtime::p2p::request::Head* Payload::_internal_mutable_head() {
  
  if (head_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::p2p::request::Head>(GetArenaForAllocation());
    head_ = p;
  }
  return head_;
}
inline ::axcl::runtime::p2p::request::Head* Payload::mutable_head() {
  ::axcl::runtime::p2p::request::Head* _msg = _internal_mutable_head();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.p2p.request.Payload.head)
  return _msg;
}
inline void Payload::set_allocated_head(::axcl::runtime::p2p::request::Head* head) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete head_;
  }
  if (head) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(head);
    if (message_arena != submessage_arena) {
      head = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, head, submessage_arena);
    }
    
  } else {
    
  }
  head_ = head;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.p2p.request.Payload.head)
}

// .axcl.runtime.p2p.request.Body body = 2;
inline bool Payload::_internal_has_body() const {
  return this != internal_default_instance() && body_ != nullptr;
}
inline bool Payload::has_body() const {
  return _internal_has_body();
}
inline void Payload::clear_body() {
  if (GetArenaForAllocation() == nullptr && body_ != nullptr) {
    delete body_;
  }
  body_ = nullptr;
}
inline const ::axcl::runtime::p2p::request::Body& Payload::_internal_body() const {
  const ::axcl::runtime::p2p::request::Body* p = body_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::p2p::request::Body&>(
      ::axcl::runtime::p2p::request::_Body_default_instance_);
}
inline const ::axcl::runtime::p2p::request::Body& Payload::body() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.request.Payload.body)
  return _internal_body();
}
inline void Payload::unsafe_arena_set_allocated_body(
    ::axcl::runtime::p2p::request::Body* body) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  body_ = body;
  if (body) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.p2p.request.Payload.body)
}
inline ::axcl::runtime::p2p::request::Body* Payload::release_body() {
  
  ::axcl::runtime::p2p::request::Body* temp = body_;
  body_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::p2p::request::Body* Payload::unsafe_arena_release_body() {
  // @@protoc_insertion_point(field_release:axcl.runtime.p2p.request.Payload.body)
  
  ::axcl::runtime::p2p::request::Body* temp = body_;
  body_ = nullptr;
  return temp;
}
inline ::axcl::runtime::p2p::request::Body* Payload::_internal_mutable_body() {
  
  if (body_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::p2p::request::Body>(GetArenaForAllocation());
    body_ = p;
  }
  return body_;
}
inline ::axcl::runtime::p2p::request::Body* Payload::mutable_body() {
  ::axcl::runtime::p2p::request::Body* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.p2p.request.Payload.body)
  return _msg;
}
inline void Payload::set_allocated_body(::axcl::runtime::p2p::request::Body* body) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete body_;
  }
  if (body) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(body);
    if (message_arena != submessage_arena) {
      body = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body, submessage_arena);
    }
    
  } else {
    
  }
  body_ = body;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.p2p.request.Payload.body)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace request
}  // namespace p2p
}  // namespace runtime
}  // namespace axcl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fp2p_2frequest_2eproto
