// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/runtime/p2p/response.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fp2p_2fresponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fp2p_2fresponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "protocol/runtime/p2p/type.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2fruntime_2fp2p_2fresponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fruntime_2fp2p_2fresponse_2eproto {
  static const uint32_t offsets[];
};
namespace axcl {
namespace runtime {
namespace p2p {
namespace response {
class BandWidthTestResult;
struct BandWidthTestResultDefaultTypeInternal;
extern BandWidthTestResultDefaultTypeInternal _BandWidthTestResult_default_instance_;
class Body;
struct BodyDefaultTypeInternal;
extern BodyDefaultTypeInternal _Body_default_instance_;
class Head;
struct HeadDefaultTypeInternal;
extern HeadDefaultTypeInternal _Head_default_instance_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
}  // namespace response
}  // namespace p2p
}  // namespace runtime
}  // namespace axcl
PROTOBUF_NAMESPACE_OPEN
template<> ::axcl::runtime::p2p::response::BandWidthTestResult* Arena::CreateMaybeMessage<::axcl::runtime::p2p::response::BandWidthTestResult>(Arena*);
template<> ::axcl::runtime::p2p::response::Body* Arena::CreateMaybeMessage<::axcl::runtime::p2p::response::Body>(Arena*);
template<> ::axcl::runtime::p2p::response::Head* Arena::CreateMaybeMessage<::axcl::runtime::p2p::response::Head>(Arena*);
template<> ::axcl::runtime::p2p::response::Payload* Arena::CreateMaybeMessage<::axcl::runtime::p2p::response::Payload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace axcl {
namespace runtime {
namespace p2p {
namespace response {

// ===================================================================

class Head final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.p2p.response.Head) */ {
 public:
  inline Head() : Head(nullptr) {}
  ~Head() override;
  explicit PROTOBUF_CONSTEXPR Head(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Head(const Head& from);
  Head(Head&& from) noexcept
    : Head() {
    *this = ::std::move(from);
  }

  inline Head& operator=(const Head& from) {
    CopyFrom(from);
    return *this;
  }
  inline Head& operator=(Head&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Head& default_instance() {
    return *internal_default_instance();
  }
  static inline const Head* internal_default_instance() {
    return reinterpret_cast<const Head*>(
               &_Head_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Head& a, Head& b) {
    a.Swap(&b);
  }
  inline void Swap(Head* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Head* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Head* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Head>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Head& from);
  void MergeFrom(const Head& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Head* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.p2p.response.Head";
  }
  protected:
  explicit Head(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApiFieldNumber = 1,
  };
  // .axcl.runtime.p2p.Api api = 1;
  void clear_api();
  ::axcl::runtime::p2p::Api api() const;
  void set_api(::axcl::runtime::p2p::Api value);
  private:
  ::axcl::runtime::p2p::Api _internal_api() const;
  void _internal_set_api(::axcl::runtime::p2p::Api value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.p2p.response.Head)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int api_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fp2p_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class BandWidthTestResult final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.p2p.response.BandWidthTestResult) */ {
 public:
  inline BandWidthTestResult() : BandWidthTestResult(nullptr) {}
  ~BandWidthTestResult() override;
  explicit PROTOBUF_CONSTEXPR BandWidthTestResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BandWidthTestResult(const BandWidthTestResult& from);
  BandWidthTestResult(BandWidthTestResult&& from) noexcept
    : BandWidthTestResult() {
    *this = ::std::move(from);
  }

  inline BandWidthTestResult& operator=(const BandWidthTestResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline BandWidthTestResult& operator=(BandWidthTestResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const BandWidthTestResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const BandWidthTestResult* internal_default_instance() {
    return reinterpret_cast<const BandWidthTestResult*>(
               &_BandWidthTestResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BandWidthTestResult& a, BandWidthTestResult& b) {
    a.Swap(&b);
  }
  inline void Swap(BandWidthTestResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BandWidthTestResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BandWidthTestResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BandWidthTestResult>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const BandWidthTestResult& from);
  void MergeFrom(const BandWidthTestResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BandWidthTestResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.p2p.response.BandWidthTestResult";
  }
  protected:
  explicit BandWidthTestResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAvgFieldNumber = 2,
    kMinFieldNumber = 3,
    kMaxFieldNumber = 4,
    kTargetIdFieldNumber = 1,
  };
  // uint64 avg = 2;
  void clear_avg();
  uint64_t avg() const;
  void set_avg(uint64_t value);
  private:
  uint64_t _internal_avg() const;
  void _internal_set_avg(uint64_t value);
  public:

  // uint64 min = 3;
  void clear_min();
  uint64_t min() const;
  void set_min(uint64_t value);
  private:
  uint64_t _internal_min() const;
  void _internal_set_min(uint64_t value);
  public:

  // uint64 max = 4;
  void clear_max();
  uint64_t max() const;
  void set_max(uint64_t value);
  private:
  uint64_t _internal_max() const;
  void _internal_set_max(uint64_t value);
  public:

  // uint32 target_id = 1;
  void clear_target_id();
  uint32_t target_id() const;
  void set_target_id(uint32_t value);
  private:
  uint32_t _internal_target_id() const;
  void _internal_set_target_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.p2p.response.BandWidthTestResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint64_t avg_;
  uint64_t min_;
  uint64_t max_;
  uint32_t target_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fp2p_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class Body final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.p2p.response.Body) */ {
 public:
  inline Body() : Body(nullptr) {}
  ~Body() override;
  explicit PROTOBUF_CONSTEXPR Body(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Body(const Body& from);
  Body(Body&& from) noexcept
    : Body() {
    *this = ::std::move(from);
  }

  inline Body& operator=(const Body& from) {
    CopyFrom(from);
    return *this;
  }
  inline Body& operator=(Body&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Body& default_instance() {
    return *internal_default_instance();
  }
  static inline const Body* internal_default_instance() {
    return reinterpret_cast<const Body*>(
               &_Body_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Body& a, Body& b) {
    a.Swap(&b);
  }
  inline void Swap(Body* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Body* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Body* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Body>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Body& from);
  void MergeFrom(const Body& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Body* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.p2p.response.Body";
  }
  protected:
  explicit Body(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBwtResFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // .axcl.runtime.p2p.response.BandWidthTestResult bwt_res = 2;
  bool has_bwt_res() const;
  private:
  bool _internal_has_bwt_res() const;
  public:
  void clear_bwt_res();
  const ::axcl::runtime::p2p::response::BandWidthTestResult& bwt_res() const;
  PROTOBUF_NODISCARD ::axcl::runtime::p2p::response::BandWidthTestResult* release_bwt_res();
  ::axcl::runtime::p2p::response::BandWidthTestResult* mutable_bwt_res();
  void set_allocated_bwt_res(::axcl::runtime::p2p::response::BandWidthTestResult* bwt_res);
  private:
  const ::axcl::runtime::p2p::response::BandWidthTestResult& _internal_bwt_res() const;
  ::axcl::runtime::p2p::response::BandWidthTestResult* _internal_mutable_bwt_res();
  public:
  void unsafe_arena_set_allocated_bwt_res(
      ::axcl::runtime::p2p::response::BandWidthTestResult* bwt_res);
  ::axcl::runtime::p2p::response::BandWidthTestResult* unsafe_arena_release_bwt_res();

  // sint32 status = 1;
  void clear_status();
  int32_t status() const;
  void set_status(int32_t value);
  private:
  int32_t _internal_status() const;
  void _internal_set_status(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.p2p.response.Body)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::axcl::runtime::p2p::response::BandWidthTestResult* bwt_res_;
  int32_t status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fp2p_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.p2p.response.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Payload& from);
  void MergeFrom(const Payload& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.p2p.response.Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeadFieldNumber = 1,
    kBodyFieldNumber = 2,
  };
  // .axcl.runtime.p2p.response.Head head = 1;
  bool has_head() const;
  private:
  bool _internal_has_head() const;
  public:
  void clear_head();
  const ::axcl::runtime::p2p::response::Head& head() const;
  PROTOBUF_NODISCARD ::axcl::runtime::p2p::response::Head* release_head();
  ::axcl::runtime::p2p::response::Head* mutable_head();
  void set_allocated_head(::axcl::runtime::p2p::response::Head* head);
  private:
  const ::axcl::runtime::p2p::response::Head& _internal_head() const;
  ::axcl::runtime::p2p::response::Head* _internal_mutable_head();
  public:
  void unsafe_arena_set_allocated_head(
      ::axcl::runtime::p2p::response::Head* head);
  ::axcl::runtime::p2p::response::Head* unsafe_arena_release_head();

  // .axcl.runtime.p2p.response.Body body = 2;
  bool has_body() const;
  private:
  bool _internal_has_body() const;
  public:
  void clear_body();
  const ::axcl::runtime::p2p::response::Body& body() const;
  PROTOBUF_NODISCARD ::axcl::runtime::p2p::response::Body* release_body();
  ::axcl::runtime::p2p::response::Body* mutable_body();
  void set_allocated_body(::axcl::runtime::p2p::response::Body* body);
  private:
  const ::axcl::runtime::p2p::response::Body& _internal_body() const;
  ::axcl::runtime::p2p::response::Body* _internal_mutable_body();
  public:
  void unsafe_arena_set_allocated_body(
      ::axcl::runtime::p2p::response::Body* body);
  ::axcl::runtime::p2p::response::Body* unsafe_arena_release_body();

  // @@protoc_insertion_point(class_scope:axcl.runtime.p2p.response.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::axcl::runtime::p2p::response::Head* head_;
  ::axcl::runtime::p2p::response::Body* body_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fp2p_2fresponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Head

// .axcl.runtime.p2p.Api api = 1;
inline void Head::clear_api() {
  api_ = 0;
}
inline ::axcl::runtime::p2p::Api Head::_internal_api() const {
  return static_cast< ::axcl::runtime::p2p::Api >(api_);
}
inline ::axcl::runtime::p2p::Api Head::api() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.response.Head.api)
  return _internal_api();
}
inline void Head::_internal_set_api(::axcl::runtime::p2p::Api value) {
  
  api_ = value;
}
inline void Head::set_api(::axcl::runtime::p2p::Api value) {
  _internal_set_api(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.response.Head.api)
}

// -------------------------------------------------------------------

// BandWidthTestResult

// uint32 target_id = 1;
inline void BandWidthTestResult::clear_target_id() {
  target_id_ = 0u;
}
inline uint32_t BandWidthTestResult::_internal_target_id() const {
  return target_id_;
}
inline uint32_t BandWidthTestResult::target_id() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.response.BandWidthTestResult.target_id)
  return _internal_target_id();
}
inline void BandWidthTestResult::_internal_set_target_id(uint32_t value) {
  
  target_id_ = value;
}
inline void BandWidthTestResult::set_target_id(uint32_t value) {
  _internal_set_target_id(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.response.BandWidthTestResult.target_id)
}

// uint64 avg = 2;
inline void BandWidthTestResult::clear_avg() {
  avg_ = uint64_t{0u};
}
inline uint64_t BandWidthTestResult::_internal_avg() const {
  return avg_;
}
inline uint64_t BandWidthTestResult::avg() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.response.BandWidthTestResult.avg)
  return _internal_avg();
}
inline void BandWidthTestResult::_internal_set_avg(uint64_t value) {
  
  avg_ = value;
}
inline void BandWidthTestResult::set_avg(uint64_t value) {
  _internal_set_avg(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.response.BandWidthTestResult.avg)
}

// uint64 min = 3;
inline void BandWidthTestResult::clear_min() {
  min_ = uint64_t{0u};
}
inline uint64_t BandWidthTestResult::_internal_min() const {
  return min_;
}
inline uint64_t BandWidthTestResult::min() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.response.BandWidthTestResult.min)
  return _internal_min();
}
inline void BandWidthTestResult::_internal_set_min(uint64_t value) {
  
  min_ = value;
}
inline void BandWidthTestResult::set_min(uint64_t value) {
  _internal_set_min(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.response.BandWidthTestResult.min)
}

// uint64 max = 4;
inline void BandWidthTestResult::clear_max() {
  max_ = uint64_t{0u};
}
inline uint64_t BandWidthTestResult::_internal_max() const {
  return max_;
}
inline uint64_t BandWidthTestResult::max() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.response.BandWidthTestResult.max)
  return _internal_max();
}
inline void BandWidthTestResult::_internal_set_max(uint64_t value) {
  
  max_ = value;
}
inline void BandWidthTestResult::set_max(uint64_t value) {
  _internal_set_max(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.response.BandWidthTestResult.max)
}

// -------------------------------------------------------------------

// Body

// sint32 status = 1;
inline void Body::clear_status() {
  status_ = 0;
}
inline int32_t Body::_internal_status() const {
  return status_;
}
inline int32_t Body::status() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.response.Body.status)
  return _internal_status();
}
inline void Body::_internal_set_status(int32_t value) {
  
  status_ = value;
}
inline void Body::set_status(int32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.p2p.response.Body.status)
}

// .axcl.runtime.p2p.response.BandWidthTestResult bwt_res = 2;
inline bool Body::_internal_has_bwt_res() const {
  return this != internal_default_instance() && bwt_res_ != nullptr;
}
inline bool Body::has_bwt_res() const {
  return _internal_has_bwt_res();
}
inline void Body::clear_bwt_res() {
  if (GetArenaForAllocation() == nullptr && bwt_res_ != nullptr) {
    delete bwt_res_;
  }
  bwt_res_ = nullptr;
}
inline const ::axcl::runtime::p2p::response::BandWidthTestResult& Body::_internal_bwt_res() const {
  const ::axcl::runtime::p2p::response::BandWidthTestResult* p = bwt_res_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::p2p::response::BandWidthTestResult&>(
      ::axcl::runtime::p2p::response::_BandWidthTestResult_default_instance_);
}
inline const ::axcl::runtime::p2p::response::BandWidthTestResult& Body::bwt_res() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.response.Body.bwt_res)
  return _internal_bwt_res();
}
inline void Body::unsafe_arena_set_allocated_bwt_res(
    ::axcl::runtime::p2p::response::BandWidthTestResult* bwt_res) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(bwt_res_);
  }
  bwt_res_ = bwt_res;
  if (bwt_res) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.p2p.response.Body.bwt_res)
}
inline ::axcl::runtime::p2p::response::BandWidthTestResult* Body::release_bwt_res() {
  
  ::axcl::runtime::p2p::response::BandWidthTestResult* temp = bwt_res_;
  bwt_res_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::p2p::response::BandWidthTestResult* Body::unsafe_arena_release_bwt_res() {
  // @@protoc_insertion_point(field_release:axcl.runtime.p2p.response.Body.bwt_res)
  
  ::axcl::runtime::p2p::response::BandWidthTestResult* temp = bwt_res_;
  bwt_res_ = nullptr;
  return temp;
}
inline ::axcl::runtime::p2p::response::BandWidthTestResult* Body::_internal_mutable_bwt_res() {
  
  if (bwt_res_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::p2p::response::BandWidthTestResult>(GetArenaForAllocation());
    bwt_res_ = p;
  }
  return bwt_res_;
}
inline ::axcl::runtime::p2p::response::BandWidthTestResult* Body::mutable_bwt_res() {
  ::axcl::runtime::p2p::response::BandWidthTestResult* _msg = _internal_mutable_bwt_res();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.p2p.response.Body.bwt_res)
  return _msg;
}
inline void Body::set_allocated_bwt_res(::axcl::runtime::p2p::response::BandWidthTestResult* bwt_res) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete bwt_res_;
  }
  if (bwt_res) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(bwt_res);
    if (message_arena != submessage_arena) {
      bwt_res = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, bwt_res, submessage_arena);
    }
    
  } else {
    
  }
  bwt_res_ = bwt_res;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.p2p.response.Body.bwt_res)
}

// -------------------------------------------------------------------

// Payload

// .axcl.runtime.p2p.response.Head head = 1;
inline bool Payload::_internal_has_head() const {
  return this != internal_default_instance() && head_ != nullptr;
}
inline bool Payload::has_head() const {
  return _internal_has_head();
}
inline void Payload::clear_head() {
  if (GetArenaForAllocation() == nullptr && head_ != nullptr) {
    delete head_;
  }
  head_ = nullptr;
}
inline const ::axcl::runtime::p2p::response::Head& Payload::_internal_head() const {
  const ::axcl::runtime::p2p::response::Head* p = head_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::p2p::response::Head&>(
      ::axcl::runtime::p2p::response::_Head_default_instance_);
}
inline const ::axcl::runtime::p2p::response::Head& Payload::head() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.response.Payload.head)
  return _internal_head();
}
inline void Payload::unsafe_arena_set_allocated_head(
    ::axcl::runtime::p2p::response::Head* head) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(head_);
  }
  head_ = head;
  if (head) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.p2p.response.Payload.head)
}
inline ::axcl::runtime::p2p::response::Head* Payload::release_head() {
  
  ::axcl::runtime::p2p::response::Head* temp = head_;
  head_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::p2p::response::Head* Payload::unsafe_arena_release_head() {
  // @@protoc_insertion_point(field_release:axcl.runtime.p2p.response.Payload.head)
  
  ::axcl::runtime::p2p::response::Head* temp = head_;
  head_ = nullptr;
  return temp;
}
inline ::axcl::runtime::p2p::response::Head* Payload::_internal_mutable_head() {
  
  if (head_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::p2p::response::Head>(GetArenaForAllocation());
    head_ = p;
  }
  return head_;
}
inline ::axcl::runtime::p2p::response::Head* Payload::mutable_head() {
  ::axcl::runtime::p2p::response::Head* _msg = _internal_mutable_head();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.p2p.response.Payload.head)
  return _msg;
}
inline void Payload::set_allocated_head(::axcl::runtime::p2p::response::Head* head) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete head_;
  }
  if (head) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(head);
    if (message_arena != submessage_arena) {
      head = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, head, submessage_arena);
    }
    
  } else {
    
  }
  head_ = head;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.p2p.response.Payload.head)
}

// .axcl.runtime.p2p.response.Body body = 2;
inline bool Payload::_internal_has_body() const {
  return this != internal_default_instance() && body_ != nullptr;
}
inline bool Payload::has_body() const {
  return _internal_has_body();
}
inline void Payload::clear_body() {
  if (GetArenaForAllocation() == nullptr && body_ != nullptr) {
    delete body_;
  }
  body_ = nullptr;
}
inline const ::axcl::runtime::p2p::response::Body& Payload::_internal_body() const {
  const ::axcl::runtime::p2p::response::Body* p = body_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::p2p::response::Body&>(
      ::axcl::runtime::p2p::response::_Body_default_instance_);
}
inline const ::axcl::runtime::p2p::response::Body& Payload::body() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.p2p.response.Payload.body)
  return _internal_body();
}
inline void Payload::unsafe_arena_set_allocated_body(
    ::axcl::runtime::p2p::response::Body* body) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  body_ = body;
  if (body) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.p2p.response.Payload.body)
}
inline ::axcl::runtime::p2p::response::Body* Payload::release_body() {
  
  ::axcl::runtime::p2p::response::Body* temp = body_;
  body_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::p2p::response::Body* Payload::unsafe_arena_release_body() {
  // @@protoc_insertion_point(field_release:axcl.runtime.p2p.response.Payload.body)
  
  ::axcl::runtime::p2p::response::Body* temp = body_;
  body_ = nullptr;
  return temp;
}
inline ::axcl::runtime::p2p::response::Body* Payload::_internal_mutable_body() {
  
  if (body_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::p2p::response::Body>(GetArenaForAllocation());
    body_ = p;
  }
  return body_;
}
inline ::axcl::runtime::p2p::response::Body* Payload::mutable_body() {
  ::axcl::runtime::p2p::response::Body* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.p2p.response.Payload.body)
  return _msg;
}
inline void Payload::set_allocated_body(::axcl::runtime::p2p::response::Body* body) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete body_;
  }
  if (body) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(body);
    if (message_arena != submessage_arena) {
      body = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body, submessage_arena);
    }
    
  } else {
    
  }
  body_ = body;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.p2p.response.Payload.body)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace response
}  // namespace p2p
}  // namespace runtime
}  // namespace axcl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fp2p_2fresponse_2eproto
