// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/runtime/memory/request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fmemory_2frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fmemory_2frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "protocol/runtime/memory/type.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2fruntime_2fmemory_2frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fruntime_2fmemory_2frequest_2eproto {
  static const uint32_t offsets[];
};
namespace axcl {
namespace runtime {
namespace memory {
namespace request {
class Body;
struct BodyDefaultTypeInternal;
extern BodyDefaultTypeInternal _Body_default_instance_;
class Head;
struct HeadDefaultTypeInternal;
extern HeadDefaultTypeInternal _Head_default_instance_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
}  // namespace request
}  // namespace memory
}  // namespace runtime
}  // namespace axcl
PROTOBUF_NAMESPACE_OPEN
template<> ::axcl::runtime::memory::request::Body* Arena::CreateMaybeMessage<::axcl::runtime::memory::request::Body>(Arena*);
template<> ::axcl::runtime::memory::request::Head* Arena::CreateMaybeMessage<::axcl::runtime::memory::request::Head>(Arena*);
template<> ::axcl::runtime::memory::request::Payload* Arena::CreateMaybeMessage<::axcl::runtime::memory::request::Payload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace axcl {
namespace runtime {
namespace memory {
namespace request {

// ===================================================================

class Head final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.memory.request.Head) */ {
 public:
  inline Head() : Head(nullptr) {}
  ~Head() override;
  explicit PROTOBUF_CONSTEXPR Head(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Head(const Head& from);
  Head(Head&& from) noexcept
    : Head() {
    *this = ::std::move(from);
  }

  inline Head& operator=(const Head& from) {
    CopyFrom(from);
    return *this;
  }
  inline Head& operator=(Head&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Head& default_instance() {
    return *internal_default_instance();
  }
  static inline const Head* internal_default_instance() {
    return reinterpret_cast<const Head*>(
               &_Head_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Head& a, Head& b) {
    a.Swap(&b);
  }
  inline void Swap(Head* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Head* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Head* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Head>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Head& from);
  void MergeFrom(const Head& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Head* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.memory.request.Head";
  }
  protected:
  explicit Head(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApiFieldNumber = 1,
  };
  // .axcl.runtime.memory.Api api = 1;
  void clear_api();
  ::axcl::runtime::memory::Api api() const;
  void set_api(::axcl::runtime::memory::Api value);
  private:
  ::axcl::runtime::memory::Api _internal_api() const;
  void _internal_set_api(::axcl::runtime::memory::Api value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.memory.request.Head)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int api_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fmemory_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Body final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.memory.request.Body) */ {
 public:
  inline Body() : Body(nullptr) {}
  ~Body() override;
  explicit PROTOBUF_CONSTEXPR Body(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Body(const Body& from);
  Body(Body&& from) noexcept
    : Body() {
    *this = ::std::move(from);
  }

  inline Body& operator=(const Body& from) {
    CopyFrom(from);
    return *this;
  }
  inline Body& operator=(Body&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Body& default_instance() {
    return *internal_default_instance();
  }
  static inline const Body* internal_default_instance() {
    return reinterpret_cast<const Body*>(
               &_Body_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Body& a, Body& b) {
    a.Swap(&b);
  }
  inline void Swap(Body* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Body* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Body* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Body>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Body& from);
  void MergeFrom(const Body& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Body* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.memory.request.Body";
  }
  protected:
  explicit Body(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddrFieldNumber = 1,
    kFromFieldNumber = 3,
    kSizeFieldNumber = 2,
    kCacheFieldNumber = 4,
    kIndexFieldNumber = 5,
    kValueFieldNumber = 6,
    kPolicyFieldNumber = 7,
    kKindFieldNumber = 8,
    kPhyFieldNumber = 10,
    kNorespFieldNumber = 9,
  };
  // uint64 addr = 1;
  void clear_addr();
  uint64_t addr() const;
  void set_addr(uint64_t value);
  private:
  uint64_t _internal_addr() const;
  void _internal_set_addr(uint64_t value);
  public:

  // optional uint64 from = 3;
  bool has_from() const;
  private:
  bool _internal_has_from() const;
  public:
  void clear_from();
  uint64_t from() const;
  void set_from(uint64_t value);
  private:
  uint64_t _internal_from() const;
  void _internal_set_from(uint64_t value);
  public:

  // optional uint32 size = 2;
  bool has_size() const;
  private:
  bool _internal_has_size() const;
  public:
  void clear_size();
  uint32_t size() const;
  void set_size(uint32_t value);
  private:
  uint32_t _internal_size() const;
  void _internal_set_size(uint32_t value);
  public:

  // optional .axcl.runtime.memory.CacheType cache = 4;
  bool has_cache() const;
  private:
  bool _internal_has_cache() const;
  public:
  void clear_cache();
  ::axcl::runtime::memory::CacheType cache() const;
  void set_cache(::axcl::runtime::memory::CacheType value);
  private:
  ::axcl::runtime::memory::CacheType _internal_cache() const;
  void _internal_set_cache(::axcl::runtime::memory::CacheType value);
  public:

  // optional uint32 index = 5;
  bool has_index() const;
  private:
  bool _internal_has_index() const;
  public:
  void clear_index();
  uint32_t index() const;
  void set_index(uint32_t value);
  private:
  uint32_t _internal_index() const;
  void _internal_set_index(uint32_t value);
  public:

  // optional uint32 value = 6;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  uint32_t value() const;
  void set_value(uint32_t value);
  private:
  uint32_t _internal_value() const;
  void _internal_set_value(uint32_t value);
  public:

  // optional uint32 policy = 7;
  bool has_policy() const;
  private:
  bool _internal_has_policy() const;
  public:
  void clear_policy();
  uint32_t policy() const;
  void set_policy(uint32_t value);
  private:
  uint32_t _internal_policy() const;
  void _internal_set_policy(uint32_t value);
  public:

  // optional uint32 kind = 8;
  bool has_kind() const;
  private:
  bool _internal_has_kind() const;
  public:
  void clear_kind();
  uint32_t kind() const;
  void set_kind(uint32_t value);
  private:
  uint32_t _internal_kind() const;
  void _internal_set_kind(uint32_t value);
  public:

  // optional uint64 phy = 10;
  bool has_phy() const;
  private:
  bool _internal_has_phy() const;
  public:
  void clear_phy();
  uint64_t phy() const;
  void set_phy(uint64_t value);
  private:
  uint64_t _internal_phy() const;
  void _internal_set_phy(uint64_t value);
  public:

  // optional uint32 noresp = 9;
  bool has_noresp() const;
  private:
  bool _internal_has_noresp() const;
  public:
  void clear_noresp();
  uint32_t noresp() const;
  void set_noresp(uint32_t value);
  private:
  uint32_t _internal_noresp() const;
  void _internal_set_noresp(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.memory.request.Body)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  uint64_t addr_;
  uint64_t from_;
  uint32_t size_;
  int cache_;
  uint32_t index_;
  uint32_t value_;
  uint32_t policy_;
  uint32_t kind_;
  uint64_t phy_;
  uint32_t noresp_;
  friend struct ::TableStruct_protocol_2fruntime_2fmemory_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.memory.request.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Payload& from);
  void MergeFrom(const Payload& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.memory.request.Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeadFieldNumber = 1,
    kBodyFieldNumber = 2,
  };
  // .axcl.runtime.memory.request.Head head = 1;
  bool has_head() const;
  private:
  bool _internal_has_head() const;
  public:
  void clear_head();
  const ::axcl::runtime::memory::request::Head& head() const;
  PROTOBUF_NODISCARD ::axcl::runtime::memory::request::Head* release_head();
  ::axcl::runtime::memory::request::Head* mutable_head();
  void set_allocated_head(::axcl::runtime::memory::request::Head* head);
  private:
  const ::axcl::runtime::memory::request::Head& _internal_head() const;
  ::axcl::runtime::memory::request::Head* _internal_mutable_head();
  public:
  void unsafe_arena_set_allocated_head(
      ::axcl::runtime::memory::request::Head* head);
  ::axcl::runtime::memory::request::Head* unsafe_arena_release_head();

  // .axcl.runtime.memory.request.Body body = 2;
  bool has_body() const;
  private:
  bool _internal_has_body() const;
  public:
  void clear_body();
  const ::axcl::runtime::memory::request::Body& body() const;
  PROTOBUF_NODISCARD ::axcl::runtime::memory::request::Body* release_body();
  ::axcl::runtime::memory::request::Body* mutable_body();
  void set_allocated_body(::axcl::runtime::memory::request::Body* body);
  private:
  const ::axcl::runtime::memory::request::Body& _internal_body() const;
  ::axcl::runtime::memory::request::Body* _internal_mutable_body();
  public:
  void unsafe_arena_set_allocated_body(
      ::axcl::runtime::memory::request::Body* body);
  ::axcl::runtime::memory::request::Body* unsafe_arena_release_body();

  // @@protoc_insertion_point(class_scope:axcl.runtime.memory.request.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::axcl::runtime::memory::request::Head* head_;
  ::axcl::runtime::memory::request::Body* body_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fmemory_2frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Head

// .axcl.runtime.memory.Api api = 1;
inline void Head::clear_api() {
  api_ = 0;
}
inline ::axcl::runtime::memory::Api Head::_internal_api() const {
  return static_cast< ::axcl::runtime::memory::Api >(api_);
}
inline ::axcl::runtime::memory::Api Head::api() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Head.api)
  return _internal_api();
}
inline void Head::_internal_set_api(::axcl::runtime::memory::Api value) {
  
  api_ = value;
}
inline void Head::set_api(::axcl::runtime::memory::Api value) {
  _internal_set_api(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Head.api)
}

// -------------------------------------------------------------------

// Body

// uint64 addr = 1;
inline void Body::clear_addr() {
  addr_ = uint64_t{0u};
}
inline uint64_t Body::_internal_addr() const {
  return addr_;
}
inline uint64_t Body::addr() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Body.addr)
  return _internal_addr();
}
inline void Body::_internal_set_addr(uint64_t value) {
  
  addr_ = value;
}
inline void Body::set_addr(uint64_t value) {
  _internal_set_addr(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Body.addr)
}

// optional uint32 size = 2;
inline bool Body::_internal_has_size() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Body::has_size() const {
  return _internal_has_size();
}
inline void Body::clear_size() {
  size_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline uint32_t Body::_internal_size() const {
  return size_;
}
inline uint32_t Body::size() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Body.size)
  return _internal_size();
}
inline void Body::_internal_set_size(uint32_t value) {
  _has_bits_[0] |= 0x00000002u;
  size_ = value;
}
inline void Body::set_size(uint32_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Body.size)
}

// optional uint64 from = 3;
inline bool Body::_internal_has_from() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Body::has_from() const {
  return _internal_has_from();
}
inline void Body::clear_from() {
  from_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000001u;
}
inline uint64_t Body::_internal_from() const {
  return from_;
}
inline uint64_t Body::from() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Body.from)
  return _internal_from();
}
inline void Body::_internal_set_from(uint64_t value) {
  _has_bits_[0] |= 0x00000001u;
  from_ = value;
}
inline void Body::set_from(uint64_t value) {
  _internal_set_from(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Body.from)
}

// optional .axcl.runtime.memory.CacheType cache = 4;
inline bool Body::_internal_has_cache() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Body::has_cache() const {
  return _internal_has_cache();
}
inline void Body::clear_cache() {
  cache_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::axcl::runtime::memory::CacheType Body::_internal_cache() const {
  return static_cast< ::axcl::runtime::memory::CacheType >(cache_);
}
inline ::axcl::runtime::memory::CacheType Body::cache() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Body.cache)
  return _internal_cache();
}
inline void Body::_internal_set_cache(::axcl::runtime::memory::CacheType value) {
  _has_bits_[0] |= 0x00000004u;
  cache_ = value;
}
inline void Body::set_cache(::axcl::runtime::memory::CacheType value) {
  _internal_set_cache(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Body.cache)
}

// optional uint32 index = 5;
inline bool Body::_internal_has_index() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Body::has_index() const {
  return _internal_has_index();
}
inline void Body::clear_index() {
  index_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline uint32_t Body::_internal_index() const {
  return index_;
}
inline uint32_t Body::index() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Body.index)
  return _internal_index();
}
inline void Body::_internal_set_index(uint32_t value) {
  _has_bits_[0] |= 0x00000008u;
  index_ = value;
}
inline void Body::set_index(uint32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Body.index)
}

// optional uint32 value = 6;
inline bool Body::_internal_has_value() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Body::has_value() const {
  return _internal_has_value();
}
inline void Body::clear_value() {
  value_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline uint32_t Body::_internal_value() const {
  return value_;
}
inline uint32_t Body::value() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Body.value)
  return _internal_value();
}
inline void Body::_internal_set_value(uint32_t value) {
  _has_bits_[0] |= 0x00000010u;
  value_ = value;
}
inline void Body::set_value(uint32_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Body.value)
}

// optional uint32 policy = 7;
inline bool Body::_internal_has_policy() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Body::has_policy() const {
  return _internal_has_policy();
}
inline void Body::clear_policy() {
  policy_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline uint32_t Body::_internal_policy() const {
  return policy_;
}
inline uint32_t Body::policy() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Body.policy)
  return _internal_policy();
}
inline void Body::_internal_set_policy(uint32_t value) {
  _has_bits_[0] |= 0x00000020u;
  policy_ = value;
}
inline void Body::set_policy(uint32_t value) {
  _internal_set_policy(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Body.policy)
}

// optional uint32 kind = 8;
inline bool Body::_internal_has_kind() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Body::has_kind() const {
  return _internal_has_kind();
}
inline void Body::clear_kind() {
  kind_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline uint32_t Body::_internal_kind() const {
  return kind_;
}
inline uint32_t Body::kind() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Body.kind)
  return _internal_kind();
}
inline void Body::_internal_set_kind(uint32_t value) {
  _has_bits_[0] |= 0x00000040u;
  kind_ = value;
}
inline void Body::set_kind(uint32_t value) {
  _internal_set_kind(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Body.kind)
}

// optional uint32 noresp = 9;
inline bool Body::_internal_has_noresp() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Body::has_noresp() const {
  return _internal_has_noresp();
}
inline void Body::clear_noresp() {
  noresp_ = 0u;
  _has_bits_[0] &= ~0x00000100u;
}
inline uint32_t Body::_internal_noresp() const {
  return noresp_;
}
inline uint32_t Body::noresp() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Body.noresp)
  return _internal_noresp();
}
inline void Body::_internal_set_noresp(uint32_t value) {
  _has_bits_[0] |= 0x00000100u;
  noresp_ = value;
}
inline void Body::set_noresp(uint32_t value) {
  _internal_set_noresp(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Body.noresp)
}

// optional uint64 phy = 10;
inline bool Body::_internal_has_phy() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Body::has_phy() const {
  return _internal_has_phy();
}
inline void Body::clear_phy() {
  phy_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000080u;
}
inline uint64_t Body::_internal_phy() const {
  return phy_;
}
inline uint64_t Body::phy() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Body.phy)
  return _internal_phy();
}
inline void Body::_internal_set_phy(uint64_t value) {
  _has_bits_[0] |= 0x00000080u;
  phy_ = value;
}
inline void Body::set_phy(uint64_t value) {
  _internal_set_phy(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.memory.request.Body.phy)
}

// -------------------------------------------------------------------

// Payload

// .axcl.runtime.memory.request.Head head = 1;
inline bool Payload::_internal_has_head() const {
  return this != internal_default_instance() && head_ != nullptr;
}
inline bool Payload::has_head() const {
  return _internal_has_head();
}
inline void Payload::clear_head() {
  if (GetArenaForAllocation() == nullptr && head_ != nullptr) {
    delete head_;
  }
  head_ = nullptr;
}
inline const ::axcl::runtime::memory::request::Head& Payload::_internal_head() const {
  const ::axcl::runtime::memory::request::Head* p = head_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::memory::request::Head&>(
      ::axcl::runtime::memory::request::_Head_default_instance_);
}
inline const ::axcl::runtime::memory::request::Head& Payload::head() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Payload.head)
  return _internal_head();
}
inline void Payload::unsafe_arena_set_allocated_head(
    ::axcl::runtime::memory::request::Head* head) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(head_);
  }
  head_ = head;
  if (head) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.memory.request.Payload.head)
}
inline ::axcl::runtime::memory::request::Head* Payload::release_head() {
  
  ::axcl::runtime::memory::request::Head* temp = head_;
  head_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::memory::request::Head* Payload::unsafe_arena_release_head() {
  // @@protoc_insertion_point(field_release:axcl.runtime.memory.request.Payload.head)
  
  ::axcl::runtime::memory::request::Head* temp = head_;
  head_ = nullptr;
  return temp;
}
inline ::axcl::runtime::memory::request::Head* Payload::_internal_mutable_head() {
  
  if (head_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::memory::request::Head>(GetArenaForAllocation());
    head_ = p;
  }
  return head_;
}
inline ::axcl::runtime::memory::request::Head* Payload::mutable_head() {
  ::axcl::runtime::memory::request::Head* _msg = _internal_mutable_head();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.memory.request.Payload.head)
  return _msg;
}
inline void Payload::set_allocated_head(::axcl::runtime::memory::request::Head* head) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete head_;
  }
  if (head) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(head);
    if (message_arena != submessage_arena) {
      head = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, head, submessage_arena);
    }
    
  } else {
    
  }
  head_ = head;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.memory.request.Payload.head)
}

// .axcl.runtime.memory.request.Body body = 2;
inline bool Payload::_internal_has_body() const {
  return this != internal_default_instance() && body_ != nullptr;
}
inline bool Payload::has_body() const {
  return _internal_has_body();
}
inline void Payload::clear_body() {
  if (GetArenaForAllocation() == nullptr && body_ != nullptr) {
    delete body_;
  }
  body_ = nullptr;
}
inline const ::axcl::runtime::memory::request::Body& Payload::_internal_body() const {
  const ::axcl::runtime::memory::request::Body* p = body_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::memory::request::Body&>(
      ::axcl::runtime::memory::request::_Body_default_instance_);
}
inline const ::axcl::runtime::memory::request::Body& Payload::body() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.memory.request.Payload.body)
  return _internal_body();
}
inline void Payload::unsafe_arena_set_allocated_body(
    ::axcl::runtime::memory::request::Body* body) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  body_ = body;
  if (body) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.memory.request.Payload.body)
}
inline ::axcl::runtime::memory::request::Body* Payload::release_body() {
  
  ::axcl::runtime::memory::request::Body* temp = body_;
  body_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::memory::request::Body* Payload::unsafe_arena_release_body() {
  // @@protoc_insertion_point(field_release:axcl.runtime.memory.request.Payload.body)
  
  ::axcl::runtime::memory::request::Body* temp = body_;
  body_ = nullptr;
  return temp;
}
inline ::axcl::runtime::memory::request::Body* Payload::_internal_mutable_body() {
  
  if (body_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::memory::request::Body>(GetArenaForAllocation());
    body_ = p;
  }
  return body_;
}
inline ::axcl::runtime::memory::request::Body* Payload::mutable_body() {
  ::axcl::runtime::memory::request::Body* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.memory.request.Payload.body)
  return _msg;
}
inline void Payload::set_allocated_body(::axcl::runtime::memory::request::Body* body) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete body_;
  }
  if (body) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(body);
    if (message_arena != submessage_arena) {
      body = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body, submessage_arena);
    }
    
  } else {
    
  }
  body_ = body;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.memory.request.Payload.body)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace request
}  // namespace memory
}  // namespace runtime
}  // namespace axcl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fmemory_2frequest_2eproto
