// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/runtime/engine/request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fengine_2frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fengine_2frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "protocol/runtime/engine/type.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2fruntime_2fengine_2frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fruntime_2fengine_2frequest_2eproto {
  static const uint32_t offsets[];
};
namespace axcl {
namespace runtime {
namespace engine {
namespace request {
class Body;
struct BodyDefaultTypeInternal;
extern BodyDefaultTypeInternal _Body_default_instance_;
class Head;
struct HeadDefaultTypeInternal;
extern HeadDefaultTypeInternal _Head_default_instance_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
}  // namespace request
}  // namespace engine
}  // namespace runtime
}  // namespace axcl
PROTOBUF_NAMESPACE_OPEN
template<> ::axcl::runtime::engine::request::Body* Arena::CreateMaybeMessage<::axcl::runtime::engine::request::Body>(Arena*);
template<> ::axcl::runtime::engine::request::Head* Arena::CreateMaybeMessage<::axcl::runtime::engine::request::Head>(Arena*);
template<> ::axcl::runtime::engine::request::Payload* Arena::CreateMaybeMessage<::axcl::runtime::engine::request::Payload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace axcl {
namespace runtime {
namespace engine {
namespace request {

// ===================================================================

class Head final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.engine.request.Head) */ {
 public:
  inline Head() : Head(nullptr) {}
  ~Head() override;
  explicit PROTOBUF_CONSTEXPR Head(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Head(const Head& from);
  Head(Head&& from) noexcept
    : Head() {
    *this = ::std::move(from);
  }

  inline Head& operator=(const Head& from) {
    CopyFrom(from);
    return *this;
  }
  inline Head& operator=(Head&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Head& default_instance() {
    return *internal_default_instance();
  }
  static inline const Head* internal_default_instance() {
    return reinterpret_cast<const Head*>(
               &_Head_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Head& a, Head& b) {
    a.Swap(&b);
  }
  inline void Swap(Head* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Head* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Head* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Head>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Head& from);
  void MergeFrom(const Head& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Head* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.engine.request.Head";
  }
  protected:
  explicit Head(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApiFieldNumber = 1,
  };
  // .axcl.runtime.engine.ApiKind api = 1;
  void clear_api();
  ::axcl::runtime::engine::ApiKind api() const;
  void set_api(::axcl::runtime::engine::ApiKind value);
  private:
  ::axcl::runtime::engine::ApiKind _internal_api() const;
  void _internal_set_api(::axcl::runtime::engine::ApiKind value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.engine.request.Head)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int api_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fengine_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Body final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.engine.request.Body) */ {
 public:
  inline Body() : Body(nullptr) {}
  ~Body() override;
  explicit PROTOBUF_CONSTEXPR Body(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Body(const Body& from);
  Body(Body&& from) noexcept
    : Body() {
    *this = ::std::move(from);
  }

  inline Body& operator=(const Body& from) {
    CopyFrom(from);
    return *this;
  }
  inline Body& operator=(Body&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Body& default_instance() {
    return *internal_default_instance();
  }
  static inline const Body* internal_default_instance() {
    return reinterpret_cast<const Body*>(
               &_Body_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Body& a, Body& b) {
    a.Swap(&b);
  }
  inline void Swap(Body* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Body* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Body* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Body>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Body& from);
  void MergeFrom(const Body& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Body* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.engine.request.Body";
  }
  protected:
  explicit Body(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIoFieldNumber = 8,
    kAddressFieldNumber = 2,
    kSizeFieldNumber = 3,
    kHandleFieldNumber = 4,
    kNpuKindFieldNumber = 1,
    kAffinityFieldNumber = 7,
    kContextFieldNumber = 5,
    kGroupFieldNumber = 6,
    kNorespFieldNumber = 9,
  };
  // optional .axcl.runtime.engine.IoDesc io = 8;
  bool has_io() const;
  private:
  bool _internal_has_io() const;
  public:
  void clear_io();
  const ::axcl::runtime::engine::IoDesc& io() const;
  PROTOBUF_NODISCARD ::axcl::runtime::engine::IoDesc* release_io();
  ::axcl::runtime::engine::IoDesc* mutable_io();
  void set_allocated_io(::axcl::runtime::engine::IoDesc* io);
  private:
  const ::axcl::runtime::engine::IoDesc& _internal_io() const;
  ::axcl::runtime::engine::IoDesc* _internal_mutable_io();
  public:
  void unsafe_arena_set_allocated_io(
      ::axcl::runtime::engine::IoDesc* io);
  ::axcl::runtime::engine::IoDesc* unsafe_arena_release_io();

  // optional uint64 address = 2;
  bool has_address() const;
  private:
  bool _internal_has_address() const;
  public:
  void clear_address();
  uint64_t address() const;
  void set_address(uint64_t value);
  private:
  uint64_t _internal_address() const;
  void _internal_set_address(uint64_t value);
  public:

  // optional uint64 size = 3;
  bool has_size() const;
  private:
  bool _internal_has_size() const;
  public:
  void clear_size();
  uint64_t size() const;
  void set_size(uint64_t value);
  private:
  uint64_t _internal_size() const;
  void _internal_set_size(uint64_t value);
  public:

  // optional uint64 handle = 4;
  bool has_handle() const;
  private:
  bool _internal_has_handle() const;
  public:
  void clear_handle();
  uint64_t handle() const;
  void set_handle(uint64_t value);
  private:
  uint64_t _internal_handle() const;
  void _internal_set_handle(uint64_t value);
  public:

  // optional .axcl.runtime.engine.NpuKind npu_kind = 1;
  bool has_npu_kind() const;
  private:
  bool _internal_has_npu_kind() const;
  public:
  void clear_npu_kind();
  ::axcl::runtime::engine::NpuKind npu_kind() const;
  void set_npu_kind(::axcl::runtime::engine::NpuKind value);
  private:
  ::axcl::runtime::engine::NpuKind _internal_npu_kind() const;
  void _internal_set_npu_kind(::axcl::runtime::engine::NpuKind value);
  public:

  // optional uint32 affinity = 7;
  bool has_affinity() const;
  private:
  bool _internal_has_affinity() const;
  public:
  void clear_affinity();
  uint32_t affinity() const;
  void set_affinity(uint32_t value);
  private:
  uint32_t _internal_affinity() const;
  void _internal_set_affinity(uint32_t value);
  public:

  // optional uint64 context = 5;
  bool has_context() const;
  private:
  bool _internal_has_context() const;
  public:
  void clear_context();
  uint64_t context() const;
  void set_context(uint64_t value);
  private:
  uint64_t _internal_context() const;
  void _internal_set_context(uint64_t value);
  public:

  // optional uint64 group = 6;
  bool has_group() const;
  private:
  bool _internal_has_group() const;
  public:
  void clear_group();
  uint64_t group() const;
  void set_group(uint64_t value);
  private:
  uint64_t _internal_group() const;
  void _internal_set_group(uint64_t value);
  public:

  // optional uint32 noresp = 9;
  bool has_noresp() const;
  private:
  bool _internal_has_noresp() const;
  public:
  void clear_noresp();
  uint32_t noresp() const;
  void set_noresp(uint32_t value);
  private:
  uint32_t _internal_noresp() const;
  void _internal_set_noresp(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.engine.request.Body)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::axcl::runtime::engine::IoDesc* io_;
  uint64_t address_;
  uint64_t size_;
  uint64_t handle_;
  int npu_kind_;
  uint32_t affinity_;
  uint64_t context_;
  uint64_t group_;
  uint32_t noresp_;
  friend struct ::TableStruct_protocol_2fruntime_2fengine_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.engine.request.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Payload& from);
  void MergeFrom(const Payload& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.engine.request.Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeadFieldNumber = 1,
    kBodyFieldNumber = 2,
  };
  // .axcl.runtime.engine.request.Head head = 1;
  bool has_head() const;
  private:
  bool _internal_has_head() const;
  public:
  void clear_head();
  const ::axcl::runtime::engine::request::Head& head() const;
  PROTOBUF_NODISCARD ::axcl::runtime::engine::request::Head* release_head();
  ::axcl::runtime::engine::request::Head* mutable_head();
  void set_allocated_head(::axcl::runtime::engine::request::Head* head);
  private:
  const ::axcl::runtime::engine::request::Head& _internal_head() const;
  ::axcl::runtime::engine::request::Head* _internal_mutable_head();
  public:
  void unsafe_arena_set_allocated_head(
      ::axcl::runtime::engine::request::Head* head);
  ::axcl::runtime::engine::request::Head* unsafe_arena_release_head();

  // .axcl.runtime.engine.request.Body body = 2;
  bool has_body() const;
  private:
  bool _internal_has_body() const;
  public:
  void clear_body();
  const ::axcl::runtime::engine::request::Body& body() const;
  PROTOBUF_NODISCARD ::axcl::runtime::engine::request::Body* release_body();
  ::axcl::runtime::engine::request::Body* mutable_body();
  void set_allocated_body(::axcl::runtime::engine::request::Body* body);
  private:
  const ::axcl::runtime::engine::request::Body& _internal_body() const;
  ::axcl::runtime::engine::request::Body* _internal_mutable_body();
  public:
  void unsafe_arena_set_allocated_body(
      ::axcl::runtime::engine::request::Body* body);
  ::axcl::runtime::engine::request::Body* unsafe_arena_release_body();

  // @@protoc_insertion_point(class_scope:axcl.runtime.engine.request.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::axcl::runtime::engine::request::Head* head_;
  ::axcl::runtime::engine::request::Body* body_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fengine_2frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Head

// .axcl.runtime.engine.ApiKind api = 1;
inline void Head::clear_api() {
  api_ = 0;
}
inline ::axcl::runtime::engine::ApiKind Head::_internal_api() const {
  return static_cast< ::axcl::runtime::engine::ApiKind >(api_);
}
inline ::axcl::runtime::engine::ApiKind Head::api() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Head.api)
  return _internal_api();
}
inline void Head::_internal_set_api(::axcl::runtime::engine::ApiKind value) {
  
  api_ = value;
}
inline void Head::set_api(::axcl::runtime::engine::ApiKind value) {
  _internal_set_api(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.engine.request.Head.api)
}

// -------------------------------------------------------------------

// Body

// optional .axcl.runtime.engine.NpuKind npu_kind = 1;
inline bool Body::_internal_has_npu_kind() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Body::has_npu_kind() const {
  return _internal_has_npu_kind();
}
inline void Body::clear_npu_kind() {
  npu_kind_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::axcl::runtime::engine::NpuKind Body::_internal_npu_kind() const {
  return static_cast< ::axcl::runtime::engine::NpuKind >(npu_kind_);
}
inline ::axcl::runtime::engine::NpuKind Body::npu_kind() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Body.npu_kind)
  return _internal_npu_kind();
}
inline void Body::_internal_set_npu_kind(::axcl::runtime::engine::NpuKind value) {
  _has_bits_[0] |= 0x00000010u;
  npu_kind_ = value;
}
inline void Body::set_npu_kind(::axcl::runtime::engine::NpuKind value) {
  _internal_set_npu_kind(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.engine.request.Body.npu_kind)
}

// optional uint64 address = 2;
inline bool Body::_internal_has_address() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Body::has_address() const {
  return _internal_has_address();
}
inline void Body::clear_address() {
  address_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000002u;
}
inline uint64_t Body::_internal_address() const {
  return address_;
}
inline uint64_t Body::address() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Body.address)
  return _internal_address();
}
inline void Body::_internal_set_address(uint64_t value) {
  _has_bits_[0] |= 0x00000002u;
  address_ = value;
}
inline void Body::set_address(uint64_t value) {
  _internal_set_address(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.engine.request.Body.address)
}

// optional uint64 size = 3;
inline bool Body::_internal_has_size() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Body::has_size() const {
  return _internal_has_size();
}
inline void Body::clear_size() {
  size_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000004u;
}
inline uint64_t Body::_internal_size() const {
  return size_;
}
inline uint64_t Body::size() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Body.size)
  return _internal_size();
}
inline void Body::_internal_set_size(uint64_t value) {
  _has_bits_[0] |= 0x00000004u;
  size_ = value;
}
inline void Body::set_size(uint64_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.engine.request.Body.size)
}

// optional uint64 handle = 4;
inline bool Body::_internal_has_handle() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Body::has_handle() const {
  return _internal_has_handle();
}
inline void Body::clear_handle() {
  handle_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000008u;
}
inline uint64_t Body::_internal_handle() const {
  return handle_;
}
inline uint64_t Body::handle() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Body.handle)
  return _internal_handle();
}
inline void Body::_internal_set_handle(uint64_t value) {
  _has_bits_[0] |= 0x00000008u;
  handle_ = value;
}
inline void Body::set_handle(uint64_t value) {
  _internal_set_handle(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.engine.request.Body.handle)
}

// optional uint64 context = 5;
inline bool Body::_internal_has_context() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Body::has_context() const {
  return _internal_has_context();
}
inline void Body::clear_context() {
  context_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000040u;
}
inline uint64_t Body::_internal_context() const {
  return context_;
}
inline uint64_t Body::context() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Body.context)
  return _internal_context();
}
inline void Body::_internal_set_context(uint64_t value) {
  _has_bits_[0] |= 0x00000040u;
  context_ = value;
}
inline void Body::set_context(uint64_t value) {
  _internal_set_context(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.engine.request.Body.context)
}

// optional uint64 group = 6;
inline bool Body::_internal_has_group() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Body::has_group() const {
  return _internal_has_group();
}
inline void Body::clear_group() {
  group_ = uint64_t{0u};
  _has_bits_[0] &= ~0x00000080u;
}
inline uint64_t Body::_internal_group() const {
  return group_;
}
inline uint64_t Body::group() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Body.group)
  return _internal_group();
}
inline void Body::_internal_set_group(uint64_t value) {
  _has_bits_[0] |= 0x00000080u;
  group_ = value;
}
inline void Body::set_group(uint64_t value) {
  _internal_set_group(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.engine.request.Body.group)
}

// optional uint32 affinity = 7;
inline bool Body::_internal_has_affinity() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Body::has_affinity() const {
  return _internal_has_affinity();
}
inline void Body::clear_affinity() {
  affinity_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline uint32_t Body::_internal_affinity() const {
  return affinity_;
}
inline uint32_t Body::affinity() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Body.affinity)
  return _internal_affinity();
}
inline void Body::_internal_set_affinity(uint32_t value) {
  _has_bits_[0] |= 0x00000020u;
  affinity_ = value;
}
inline void Body::set_affinity(uint32_t value) {
  _internal_set_affinity(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.engine.request.Body.affinity)
}

// optional .axcl.runtime.engine.IoDesc io = 8;
inline bool Body::_internal_has_io() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || io_ != nullptr);
  return value;
}
inline bool Body::has_io() const {
  return _internal_has_io();
}
inline const ::axcl::runtime::engine::IoDesc& Body::_internal_io() const {
  const ::axcl::runtime::engine::IoDesc* p = io_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::engine::IoDesc&>(
      ::axcl::runtime::engine::_IoDesc_default_instance_);
}
inline const ::axcl::runtime::engine::IoDesc& Body::io() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Body.io)
  return _internal_io();
}
inline void Body::unsafe_arena_set_allocated_io(
    ::axcl::runtime::engine::IoDesc* io) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(io_);
  }
  io_ = io;
  if (io) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.engine.request.Body.io)
}
inline ::axcl::runtime::engine::IoDesc* Body::release_io() {
  _has_bits_[0] &= ~0x00000001u;
  ::axcl::runtime::engine::IoDesc* temp = io_;
  io_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::engine::IoDesc* Body::unsafe_arena_release_io() {
  // @@protoc_insertion_point(field_release:axcl.runtime.engine.request.Body.io)
  _has_bits_[0] &= ~0x00000001u;
  ::axcl::runtime::engine::IoDesc* temp = io_;
  io_ = nullptr;
  return temp;
}
inline ::axcl::runtime::engine::IoDesc* Body::_internal_mutable_io() {
  _has_bits_[0] |= 0x00000001u;
  if (io_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::engine::IoDesc>(GetArenaForAllocation());
    io_ = p;
  }
  return io_;
}
inline ::axcl::runtime::engine::IoDesc* Body::mutable_io() {
  ::axcl::runtime::engine::IoDesc* _msg = _internal_mutable_io();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.engine.request.Body.io)
  return _msg;
}
inline void Body::set_allocated_io(::axcl::runtime::engine::IoDesc* io) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(io_);
  }
  if (io) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(io));
    if (message_arena != submessage_arena) {
      io = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, io, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  io_ = io;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.engine.request.Body.io)
}

// optional uint32 noresp = 9;
inline bool Body::_internal_has_noresp() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Body::has_noresp() const {
  return _internal_has_noresp();
}
inline void Body::clear_noresp() {
  noresp_ = 0u;
  _has_bits_[0] &= ~0x00000100u;
}
inline uint32_t Body::_internal_noresp() const {
  return noresp_;
}
inline uint32_t Body::noresp() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Body.noresp)
  return _internal_noresp();
}
inline void Body::_internal_set_noresp(uint32_t value) {
  _has_bits_[0] |= 0x00000100u;
  noresp_ = value;
}
inline void Body::set_noresp(uint32_t value) {
  _internal_set_noresp(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.engine.request.Body.noresp)
}

// -------------------------------------------------------------------

// Payload

// .axcl.runtime.engine.request.Head head = 1;
inline bool Payload::_internal_has_head() const {
  return this != internal_default_instance() && head_ != nullptr;
}
inline bool Payload::has_head() const {
  return _internal_has_head();
}
inline void Payload::clear_head() {
  if (GetArenaForAllocation() == nullptr && head_ != nullptr) {
    delete head_;
  }
  head_ = nullptr;
}
inline const ::axcl::runtime::engine::request::Head& Payload::_internal_head() const {
  const ::axcl::runtime::engine::request::Head* p = head_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::engine::request::Head&>(
      ::axcl::runtime::engine::request::_Head_default_instance_);
}
inline const ::axcl::runtime::engine::request::Head& Payload::head() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Payload.head)
  return _internal_head();
}
inline void Payload::unsafe_arena_set_allocated_head(
    ::axcl::runtime::engine::request::Head* head) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(head_);
  }
  head_ = head;
  if (head) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.engine.request.Payload.head)
}
inline ::axcl::runtime::engine::request::Head* Payload::release_head() {
  
  ::axcl::runtime::engine::request::Head* temp = head_;
  head_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::engine::request::Head* Payload::unsafe_arena_release_head() {
  // @@protoc_insertion_point(field_release:axcl.runtime.engine.request.Payload.head)
  
  ::axcl::runtime::engine::request::Head* temp = head_;
  head_ = nullptr;
  return temp;
}
inline ::axcl::runtime::engine::request::Head* Payload::_internal_mutable_head() {
  
  if (head_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::engine::request::Head>(GetArenaForAllocation());
    head_ = p;
  }
  return head_;
}
inline ::axcl::runtime::engine::request::Head* Payload::mutable_head() {
  ::axcl::runtime::engine::request::Head* _msg = _internal_mutable_head();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.engine.request.Payload.head)
  return _msg;
}
inline void Payload::set_allocated_head(::axcl::runtime::engine::request::Head* head) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete head_;
  }
  if (head) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(head);
    if (message_arena != submessage_arena) {
      head = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, head, submessage_arena);
    }
    
  } else {
    
  }
  head_ = head;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.engine.request.Payload.head)
}

// .axcl.runtime.engine.request.Body body = 2;
inline bool Payload::_internal_has_body() const {
  return this != internal_default_instance() && body_ != nullptr;
}
inline bool Payload::has_body() const {
  return _internal_has_body();
}
inline void Payload::clear_body() {
  if (GetArenaForAllocation() == nullptr && body_ != nullptr) {
    delete body_;
  }
  body_ = nullptr;
}
inline const ::axcl::runtime::engine::request::Body& Payload::_internal_body() const {
  const ::axcl::runtime::engine::request::Body* p = body_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::engine::request::Body&>(
      ::axcl::runtime::engine::request::_Body_default_instance_);
}
inline const ::axcl::runtime::engine::request::Body& Payload::body() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.engine.request.Payload.body)
  return _internal_body();
}
inline void Payload::unsafe_arena_set_allocated_body(
    ::axcl::runtime::engine::request::Body* body) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  body_ = body;
  if (body) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.engine.request.Payload.body)
}
inline ::axcl::runtime::engine::request::Body* Payload::release_body() {
  
  ::axcl::runtime::engine::request::Body* temp = body_;
  body_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::engine::request::Body* Payload::unsafe_arena_release_body() {
  // @@protoc_insertion_point(field_release:axcl.runtime.engine.request.Payload.body)
  
  ::axcl::runtime::engine::request::Body* temp = body_;
  body_ = nullptr;
  return temp;
}
inline ::axcl::runtime::engine::request::Body* Payload::_internal_mutable_body() {
  
  if (body_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::engine::request::Body>(GetArenaForAllocation());
    body_ = p;
  }
  return body_;
}
inline ::axcl::runtime::engine::request::Body* Payload::mutable_body() {
  ::axcl::runtime::engine::request::Body* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.engine.request.Payload.body)
  return _msg;
}
inline void Payload::set_allocated_body(::axcl::runtime::engine::request::Body* body) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete body_;
  }
  if (body) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(body);
    if (message_arena != submessage_arena) {
      body = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body, submessage_arena);
    }
    
  } else {
    
  }
  body_ = body;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.engine.request.Payload.body)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace request
}  // namespace engine
}  // namespace runtime
}  // namespace axcl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fengine_2frequest_2eproto
