// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/runtime/system/request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fsystem_2frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fsystem_2frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "protocol/runtime/system/type.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2fruntime_2fsystem_2frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fruntime_2fsystem_2frequest_2eproto {
  static const uint32_t offsets[];
};
namespace axcl {
namespace runtime {
namespace system {
namespace request {
class Alive;
struct AliveDefaultTypeInternal;
extern AliveDefaultTypeInternal _Alive_default_instance_;
class Body;
struct BodyDefaultTypeInternal;
extern BodyDefaultTypeInternal _Body_default_instance_;
class Control;
struct ControlDefaultTypeInternal;
extern ControlDefaultTypeInternal _Control_default_instance_;
class Head;
struct HeadDefaultTypeInternal;
extern HeadDefaultTypeInternal _Head_default_instance_;
class Latency;
struct LatencyDefaultTypeInternal;
extern LatencyDefaultTypeInternal _Latency_default_instance_;
class Log;
struct LogDefaultTypeInternal;
extern LogDefaultTypeInternal _Log_default_instance_;
class PCIeSubID;
struct PCIeSubIDDefaultTypeInternal;
extern PCIeSubIDDefaultTypeInternal _PCIeSubID_default_instance_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
class Shell;
struct ShellDefaultTypeInternal;
extern ShellDefaultTypeInternal _Shell_default_instance_;
}  // namespace request
}  // namespace system
}  // namespace runtime
}  // namespace axcl
PROTOBUF_NAMESPACE_OPEN
template<> ::axcl::runtime::system::request::Alive* Arena::CreateMaybeMessage<::axcl::runtime::system::request::Alive>(Arena*);
template<> ::axcl::runtime::system::request::Body* Arena::CreateMaybeMessage<::axcl::runtime::system::request::Body>(Arena*);
template<> ::axcl::runtime::system::request::Control* Arena::CreateMaybeMessage<::axcl::runtime::system::request::Control>(Arena*);
template<> ::axcl::runtime::system::request::Head* Arena::CreateMaybeMessage<::axcl::runtime::system::request::Head>(Arena*);
template<> ::axcl::runtime::system::request::Latency* Arena::CreateMaybeMessage<::axcl::runtime::system::request::Latency>(Arena*);
template<> ::axcl::runtime::system::request::Log* Arena::CreateMaybeMessage<::axcl::runtime::system::request::Log>(Arena*);
template<> ::axcl::runtime::system::request::PCIeSubID* Arena::CreateMaybeMessage<::axcl::runtime::system::request::PCIeSubID>(Arena*);
template<> ::axcl::runtime::system::request::Payload* Arena::CreateMaybeMessage<::axcl::runtime::system::request::Payload>(Arena*);
template<> ::axcl::runtime::system::request::Shell* Arena::CreateMaybeMessage<::axcl::runtime::system::request::Shell>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace axcl {
namespace runtime {
namespace system {
namespace request {

// ===================================================================

class Head final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.system.request.Head) */ {
 public:
  inline Head() : Head(nullptr) {}
  ~Head() override;
  explicit PROTOBUF_CONSTEXPR Head(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Head(const Head& from);
  Head(Head&& from) noexcept
    : Head() {
    *this = ::std::move(from);
  }

  inline Head& operator=(const Head& from) {
    CopyFrom(from);
    return *this;
  }
  inline Head& operator=(Head&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Head& default_instance() {
    return *internal_default_instance();
  }
  static inline const Head* internal_default_instance() {
    return reinterpret_cast<const Head*>(
               &_Head_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Head& a, Head& b) {
    a.Swap(&b);
  }
  inline void Swap(Head* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Head* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Head* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Head>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Head& from);
  void MergeFrom(const Head& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Head* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.system.request.Head";
  }
  protected:
  explicit Head(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModuleFieldNumber = 1,
  };
  // .axcl.runtime.system.Module module = 1;
  void clear_module();
  ::axcl::runtime::system::Module module() const;
  void set_module(::axcl::runtime::system::Module value);
  private:
  ::axcl::runtime::system::Module _internal_module() const;
  void _internal_set_module(::axcl::runtime::system::Module value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.system.request.Head)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int module_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fsystem_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Alive final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.system.request.Alive) */ {
 public:
  inline Alive() : Alive(nullptr) {}
  ~Alive() override;
  explicit PROTOBUF_CONSTEXPR Alive(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Alive(const Alive& from);
  Alive(Alive&& from) noexcept
    : Alive() {
    *this = ::std::move(from);
  }

  inline Alive& operator=(const Alive& from) {
    CopyFrom(from);
    return *this;
  }
  inline Alive& operator=(Alive&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Alive& default_instance() {
    return *internal_default_instance();
  }
  static inline const Alive* internal_default_instance() {
    return reinterpret_cast<const Alive*>(
               &_Alive_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Alive& a, Alive& b) {
    a.Swap(&b);
  }
  inline void Swap(Alive* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Alive* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Alive* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Alive>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Alive& from);
  void MergeFrom(const Alive& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Alive* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.system.request.Alive";
  }
  protected:
  explicit Alive(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:axcl.runtime.system.request.Alive)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fsystem_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Latency final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.system.request.Latency) */ {
 public:
  inline Latency() : Latency(nullptr) {}
  ~Latency() override;
  explicit PROTOBUF_CONSTEXPR Latency(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Latency(const Latency& from);
  Latency(Latency&& from) noexcept
    : Latency() {
    *this = ::std::move(from);
  }

  inline Latency& operator=(const Latency& from) {
    CopyFrom(from);
    return *this;
  }
  inline Latency& operator=(Latency&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Latency& default_instance() {
    return *internal_default_instance();
  }
  static inline const Latency* internal_default_instance() {
    return reinterpret_cast<const Latency*>(
               &_Latency_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Latency& a, Latency& b) {
    a.Swap(&b);
  }
  inline void Swap(Latency* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Latency* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Latency* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Latency>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Latency& from);
  void MergeFrom(const Latency& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Latency* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.system.request.Latency";
  }
  protected:
  explicit Latency(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // bytes data = 1;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.system.request.Latency)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fsystem_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Log final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.system.request.Log) */ {
 public:
  inline Log() : Log(nullptr) {}
  ~Log() override;
  explicit PROTOBUF_CONSTEXPR Log(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Log(const Log& from);
  Log(Log&& from) noexcept
    : Log() {
    *this = ::std::move(from);
  }

  inline Log& operator=(const Log& from) {
    CopyFrom(from);
    return *this;
  }
  inline Log& operator=(Log&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Log& default_instance() {
    return *internal_default_instance();
  }
  static inline const Log* internal_default_instance() {
    return reinterpret_cast<const Log*>(
               &_Log_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Log& a, Log& b) {
    a.Swap(&b);
  }
  inline void Swap(Log* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Log* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Log* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Log>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Log& from);
  void MergeFrom(const Log& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Log* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.system.request.Log";
  }
  protected:
  explicit Log(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kFlagFieldNumber = 2,
  };
  // uint32 type = 1;
  void clear_type();
  uint32_t type() const;
  void set_type(uint32_t value);
  private:
  uint32_t _internal_type() const;
  void _internal_set_type(uint32_t value);
  public:

  // uint32 flag = 2;
  void clear_flag();
  uint32_t flag() const;
  void set_flag(uint32_t value);
  private:
  uint32_t _internal_flag() const;
  void _internal_set_flag(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.system.request.Log)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t type_;
  uint32_t flag_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fsystem_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Shell final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.system.request.Shell) */ {
 public:
  inline Shell() : Shell(nullptr) {}
  ~Shell() override;
  explicit PROTOBUF_CONSTEXPR Shell(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Shell(const Shell& from);
  Shell(Shell&& from) noexcept
    : Shell() {
    *this = ::std::move(from);
  }

  inline Shell& operator=(const Shell& from) {
    CopyFrom(from);
    return *this;
  }
  inline Shell& operator=(Shell&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Shell& default_instance() {
    return *internal_default_instance();
  }
  static inline const Shell* internal_default_instance() {
    return reinterpret_cast<const Shell*>(
               &_Shell_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Shell& a, Shell& b) {
    a.Swap(&b);
  }
  inline void Swap(Shell* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Shell* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Shell* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Shell>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Shell& from);
  void MergeFrom(const Shell& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Shell* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.system.request.Shell";
  }
  protected:
  explicit Shell(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArgsFieldNumber = 2,
    kCmdFieldNumber = 1,
  };
  // repeated string args = 2;
  int args_size() const;
  private:
  int _internal_args_size() const;
  public:
  void clear_args();
  const std::string& args(int index) const;
  std::string* mutable_args(int index);
  void set_args(int index, const std::string& value);
  void set_args(int index, std::string&& value);
  void set_args(int index, const char* value);
  void set_args(int index, const char* value, size_t size);
  std::string* add_args();
  void add_args(const std::string& value);
  void add_args(std::string&& value);
  void add_args(const char* value);
  void add_args(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& args() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_args();
  private:
  const std::string& _internal_args(int index) const;
  std::string* _internal_add_args();
  public:

  // string cmd = 1;
  void clear_cmd();
  const std::string& cmd() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_cmd(ArgT0&& arg0, ArgT... args);
  std::string* mutable_cmd();
  PROTOBUF_NODISCARD std::string* release_cmd();
  void set_allocated_cmd(std::string* cmd);
  private:
  const std::string& _internal_cmd() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_cmd(const std::string& value);
  std::string* _internal_mutable_cmd();
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.system.request.Shell)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> args_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cmd_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fsystem_2frequest_2eproto;
};
// -------------------------------------------------------------------

class PCIeSubID final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.system.request.PCIeSubID) */ {
 public:
  inline PCIeSubID() : PCIeSubID(nullptr) {}
  ~PCIeSubID() override;
  explicit PROTOBUF_CONSTEXPR PCIeSubID(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PCIeSubID(const PCIeSubID& from);
  PCIeSubID(PCIeSubID&& from) noexcept
    : PCIeSubID() {
    *this = ::std::move(from);
  }

  inline PCIeSubID& operator=(const PCIeSubID& from) {
    CopyFrom(from);
    return *this;
  }
  inline PCIeSubID& operator=(PCIeSubID&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const PCIeSubID& default_instance() {
    return *internal_default_instance();
  }
  static inline const PCIeSubID* internal_default_instance() {
    return reinterpret_cast<const PCIeSubID*>(
               &_PCIeSubID_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(PCIeSubID& a, PCIeSubID& b) {
    a.Swap(&b);
  }
  inline void Swap(PCIeSubID* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PCIeSubID* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PCIeSubID* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PCIeSubID>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const PCIeSubID& from);
  void MergeFrom(const PCIeSubID& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PCIeSubID* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.system.request.PCIeSubID";
  }
  protected:
  explicit PCIeSubID(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVendorIdFieldNumber = 1,
    kDeviceIdFieldNumber = 2,
  };
  // uint32 vendor_id = 1;
  void clear_vendor_id();
  uint32_t vendor_id() const;
  void set_vendor_id(uint32_t value);
  private:
  uint32_t _internal_vendor_id() const;
  void _internal_set_vendor_id(uint32_t value);
  public:

  // uint32 device_id = 2;
  void clear_device_id();
  uint32_t device_id() const;
  void set_device_id(uint32_t value);
  private:
  uint32_t _internal_device_id() const;
  void _internal_set_device_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.system.request.PCIeSubID)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t vendor_id_;
  uint32_t device_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fsystem_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Control final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.system.request.Control) */ {
 public:
  inline Control() : Control(nullptr) {}
  ~Control() override;
  explicit PROTOBUF_CONSTEXPR Control(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Control(const Control& from);
  Control(Control&& from) noexcept
    : Control() {
    *this = ::std::move(from);
  }

  inline Control& operator=(const Control& from) {
    CopyFrom(from);
    return *this;
  }
  inline Control& operator=(Control&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Control& default_instance() {
    return *internal_default_instance();
  }
  static inline const Control* internal_default_instance() {
    return reinterpret_cast<const Control*>(
               &_Control_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Control& a, Control& b) {
    a.Swap(&b);
  }
  inline void Swap(Control* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Control* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Control* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Control>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Control& from);
  void MergeFrom(const Control& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Control* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.system.request.Control";
  }
  protected:
  explicit Control(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShellFieldNumber = 5,
    kPcieSubIdFieldNumber = 6,
    kCmdFieldNumber = 1,
    kPidFieldNumber = 2,
    kTidFieldNumber = 3,
    kContextFieldNumber = 4,
    kStreamFieldNumber = 7,
    kEventFieldNumber = 8,
    kTimeoutFieldNumber = 9,
    kNorespFieldNumber = 10,
  };
  // optional .axcl.runtime.system.request.Shell shell = 5;
  bool has_shell() const;
  private:
  bool _internal_has_shell() const;
  public:
  void clear_shell();
  const ::axcl::runtime::system::request::Shell& shell() const;
  PROTOBUF_NODISCARD ::axcl::runtime::system::request::Shell* release_shell();
  ::axcl::runtime::system::request::Shell* mutable_shell();
  void set_allocated_shell(::axcl::runtime::system::request::Shell* shell);
  private:
  const ::axcl::runtime::system::request::Shell& _internal_shell() const;
  ::axcl::runtime::system::request::Shell* _internal_mutable_shell();
  public:
  void unsafe_arena_set_allocated_shell(
      ::axcl::runtime::system::request::Shell* shell);
  ::axcl::runtime::system::request::Shell* unsafe_arena_release_shell();

  // optional .axcl.runtime.system.request.PCIeSubID pcie_sub_id = 6;
  bool has_pcie_sub_id() const;
  private:
  bool _internal_has_pcie_sub_id() const;
  public:
  void clear_pcie_sub_id();
  const ::axcl::runtime::system::request::PCIeSubID& pcie_sub_id() const;
  PROTOBUF_NODISCARD ::axcl::runtime::system::request::PCIeSubID* release_pcie_sub_id();
  ::axcl::runtime::system::request::PCIeSubID* mutable_pcie_sub_id();
  void set_allocated_pcie_sub_id(::axcl::runtime::system::request::PCIeSubID* pcie_sub_id);
  private:
  const ::axcl::runtime::system::request::PCIeSubID& _internal_pcie_sub_id() const;
  ::axcl::runtime::system::request::PCIeSubID* _internal_mutable_pcie_sub_id();
  public:
  void unsafe_arena_set_allocated_pcie_sub_id(
      ::axcl::runtime::system::request::PCIeSubID* pcie_sub_id);
  ::axcl::runtime::system::request::PCIeSubID* unsafe_arena_release_pcie_sub_id();

  // .axcl.runtime.system.Command cmd = 1;
  void clear_cmd();
  ::axcl::runtime::system::Command cmd() const;
  void set_cmd(::axcl::runtime::system::Command value);
  private:
  ::axcl::runtime::system::Command _internal_cmd() const;
  void _internal_set_cmd(::axcl::runtime::system::Command value);
  public:

  // optional uint32 pid = 2;
  bool has_pid() const;
  private:
  bool _internal_has_pid() const;
  public:
  void clear_pid();
  uint32_t pid() const;
  void set_pid(uint32_t value);
  private:
  uint32_t _internal_pid() const;
  void _internal_set_pid(uint32_t value);
  public:

  // optional uint32 tid = 3;
  bool has_tid() const;
  private:
  bool _internal_has_tid() const;
  public:
  void clear_tid();
  uint32_t tid() const;
  void set_tid(uint32_t value);
  private:
  uint32_t _internal_tid() const;
  void _internal_set_tid(uint32_t value);
  public:

  // optional uint32 context = 4;
  bool has_context() const;
  private:
  bool _internal_has_context() const;
  public:
  void clear_context();
  uint32_t context() const;
  void set_context(uint32_t value);
  private:
  uint32_t _internal_context() const;
  void _internal_set_context(uint32_t value);
  public:

  // optional uint32 stream = 7;
  bool has_stream() const;
  private:
  bool _internal_has_stream() const;
  public:
  void clear_stream();
  uint32_t stream() const;
  void set_stream(uint32_t value);
  private:
  uint32_t _internal_stream() const;
  void _internal_set_stream(uint32_t value);
  public:

  // optional uint32 event = 8;
  bool has_event() const;
  private:
  bool _internal_has_event() const;
  public:
  void clear_event();
  uint32_t event() const;
  void set_event(uint32_t value);
  private:
  uint32_t _internal_event() const;
  void _internal_set_event(uint32_t value);
  public:

  // optional int32 timeout = 9;
  bool has_timeout() const;
  private:
  bool _internal_has_timeout() const;
  public:
  void clear_timeout();
  int32_t timeout() const;
  void set_timeout(int32_t value);
  private:
  int32_t _internal_timeout() const;
  void _internal_set_timeout(int32_t value);
  public:

  // optional uint32 noresp = 10;
  bool has_noresp() const;
  private:
  bool _internal_has_noresp() const;
  public:
  void clear_noresp();
  uint32_t noresp() const;
  void set_noresp(uint32_t value);
  private:
  uint32_t _internal_noresp() const;
  void _internal_set_noresp(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.system.request.Control)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::axcl::runtime::system::request::Shell* shell_;
  ::axcl::runtime::system::request::PCIeSubID* pcie_sub_id_;
  int cmd_;
  uint32_t pid_;
  uint32_t tid_;
  uint32_t context_;
  uint32_t stream_;
  uint32_t event_;
  int32_t timeout_;
  uint32_t noresp_;
  friend struct ::TableStruct_protocol_2fruntime_2fsystem_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Body final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.system.request.Body) */ {
 public:
  inline Body() : Body(nullptr) {}
  ~Body() override;
  explicit PROTOBUF_CONSTEXPR Body(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Body(const Body& from);
  Body(Body&& from) noexcept
    : Body() {
    *this = ::std::move(from);
  }

  inline Body& operator=(const Body& from) {
    CopyFrom(from);
    return *this;
  }
  inline Body& operator=(Body&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Body& default_instance() {
    return *internal_default_instance();
  }
  static inline const Body* internal_default_instance() {
    return reinterpret_cast<const Body*>(
               &_Body_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(Body& a, Body& b) {
    a.Swap(&b);
  }
  inline void Swap(Body* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Body* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Body* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Body>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Body& from);
  void MergeFrom(const Body& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Body* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.system.request.Body";
  }
  protected:
  explicit Body(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAliveFieldNumber = 1,
    kLatencyFieldNumber = 2,
    kLogFieldNumber = 3,
    kControlFieldNumber = 4,
  };
  // optional .axcl.runtime.system.request.Alive alive = 1;
  bool has_alive() const;
  private:
  bool _internal_has_alive() const;
  public:
  void clear_alive();
  const ::axcl::runtime::system::request::Alive& alive() const;
  PROTOBUF_NODISCARD ::axcl::runtime::system::request::Alive* release_alive();
  ::axcl::runtime::system::request::Alive* mutable_alive();
  void set_allocated_alive(::axcl::runtime::system::request::Alive* alive);
  private:
  const ::axcl::runtime::system::request::Alive& _internal_alive() const;
  ::axcl::runtime::system::request::Alive* _internal_mutable_alive();
  public:
  void unsafe_arena_set_allocated_alive(
      ::axcl::runtime::system::request::Alive* alive);
  ::axcl::runtime::system::request::Alive* unsafe_arena_release_alive();

  // optional .axcl.runtime.system.request.Latency latency = 2;
  bool has_latency() const;
  private:
  bool _internal_has_latency() const;
  public:
  void clear_latency();
  const ::axcl::runtime::system::request::Latency& latency() const;
  PROTOBUF_NODISCARD ::axcl::runtime::system::request::Latency* release_latency();
  ::axcl::runtime::system::request::Latency* mutable_latency();
  void set_allocated_latency(::axcl::runtime::system::request::Latency* latency);
  private:
  const ::axcl::runtime::system::request::Latency& _internal_latency() const;
  ::axcl::runtime::system::request::Latency* _internal_mutable_latency();
  public:
  void unsafe_arena_set_allocated_latency(
      ::axcl::runtime::system::request::Latency* latency);
  ::axcl::runtime::system::request::Latency* unsafe_arena_release_latency();

  // optional .axcl.runtime.system.request.Log log = 3;
  bool has_log() const;
  private:
  bool _internal_has_log() const;
  public:
  void clear_log();
  const ::axcl::runtime::system::request::Log& log() const;
  PROTOBUF_NODISCARD ::axcl::runtime::system::request::Log* release_log();
  ::axcl::runtime::system::request::Log* mutable_log();
  void set_allocated_log(::axcl::runtime::system::request::Log* log);
  private:
  const ::axcl::runtime::system::request::Log& _internal_log() const;
  ::axcl::runtime::system::request::Log* _internal_mutable_log();
  public:
  void unsafe_arena_set_allocated_log(
      ::axcl::runtime::system::request::Log* log);
  ::axcl::runtime::system::request::Log* unsafe_arena_release_log();

  // optional .axcl.runtime.system.request.Control control = 4;
  bool has_control() const;
  private:
  bool _internal_has_control() const;
  public:
  void clear_control();
  const ::axcl::runtime::system::request::Control& control() const;
  PROTOBUF_NODISCARD ::axcl::runtime::system::request::Control* release_control();
  ::axcl::runtime::system::request::Control* mutable_control();
  void set_allocated_control(::axcl::runtime::system::request::Control* control);
  private:
  const ::axcl::runtime::system::request::Control& _internal_control() const;
  ::axcl::runtime::system::request::Control* _internal_mutable_control();
  public:
  void unsafe_arena_set_allocated_control(
      ::axcl::runtime::system::request::Control* control);
  ::axcl::runtime::system::request::Control* unsafe_arena_release_control();

  // @@protoc_insertion_point(class_scope:axcl.runtime.system.request.Body)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::axcl::runtime::system::request::Alive* alive_;
  ::axcl::runtime::system::request::Latency* latency_;
  ::axcl::runtime::system::request::Log* log_;
  ::axcl::runtime::system::request::Control* control_;
  friend struct ::TableStruct_protocol_2fruntime_2fsystem_2frequest_2eproto;
};
// -------------------------------------------------------------------

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.system.request.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Payload& from);
  void MergeFrom(const Payload& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.system.request.Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeadFieldNumber = 1,
    kBodyFieldNumber = 2,
  };
  // .axcl.runtime.system.request.Head head = 1;
  bool has_head() const;
  private:
  bool _internal_has_head() const;
  public:
  void clear_head();
  const ::axcl::runtime::system::request::Head& head() const;
  PROTOBUF_NODISCARD ::axcl::runtime::system::request::Head* release_head();
  ::axcl::runtime::system::request::Head* mutable_head();
  void set_allocated_head(::axcl::runtime::system::request::Head* head);
  private:
  const ::axcl::runtime::system::request::Head& _internal_head() const;
  ::axcl::runtime::system::request::Head* _internal_mutable_head();
  public:
  void unsafe_arena_set_allocated_head(
      ::axcl::runtime::system::request::Head* head);
  ::axcl::runtime::system::request::Head* unsafe_arena_release_head();

  // .axcl.runtime.system.request.Body body = 2;
  bool has_body() const;
  private:
  bool _internal_has_body() const;
  public:
  void clear_body();
  const ::axcl::runtime::system::request::Body& body() const;
  PROTOBUF_NODISCARD ::axcl::runtime::system::request::Body* release_body();
  ::axcl::runtime::system::request::Body* mutable_body();
  void set_allocated_body(::axcl::runtime::system::request::Body* body);
  private:
  const ::axcl::runtime::system::request::Body& _internal_body() const;
  ::axcl::runtime::system::request::Body* _internal_mutable_body();
  public:
  void unsafe_arena_set_allocated_body(
      ::axcl::runtime::system::request::Body* body);
  ::axcl::runtime::system::request::Body* unsafe_arena_release_body();

  // @@protoc_insertion_point(class_scope:axcl.runtime.system.request.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::axcl::runtime::system::request::Head* head_;
  ::axcl::runtime::system::request::Body* body_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fsystem_2frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Head

// .axcl.runtime.system.Module module = 1;
inline void Head::clear_module() {
  module_ = 0;
}
inline ::axcl::runtime::system::Module Head::_internal_module() const {
  return static_cast< ::axcl::runtime::system::Module >(module_);
}
inline ::axcl::runtime::system::Module Head::module() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Head.module)
  return _internal_module();
}
inline void Head::_internal_set_module(::axcl::runtime::system::Module value) {
  
  module_ = value;
}
inline void Head::set_module(::axcl::runtime::system::Module value) {
  _internal_set_module(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Head.module)
}

// -------------------------------------------------------------------

// Alive

// -------------------------------------------------------------------

// Latency

// bytes data = 1;
inline void Latency::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& Latency::data() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Latency.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Latency::set_data(ArgT0&& arg0, ArgT... args) {
 
 data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Latency.data)
}
inline std::string* Latency::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Latency.data)
  return _s;
}
inline const std::string& Latency::_internal_data() const {
  return data_.Get();
}
inline void Latency::_internal_set_data(const std::string& value) {
  
  data_.Set(value, GetArenaForAllocation());
}
inline std::string* Latency::_internal_mutable_data() {
  
  return data_.Mutable(GetArenaForAllocation());
}
inline std::string* Latency::release_data() {
  // @@protoc_insertion_point(field_release:axcl.runtime.system.request.Latency.data)
  return data_.Release();
}
inline void Latency::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault()) {
    data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.system.request.Latency.data)
}

// -------------------------------------------------------------------

// Log

// uint32 type = 1;
inline void Log::clear_type() {
  type_ = 0u;
}
inline uint32_t Log::_internal_type() const {
  return type_;
}
inline uint32_t Log::type() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Log.type)
  return _internal_type();
}
inline void Log::_internal_set_type(uint32_t value) {
  
  type_ = value;
}
inline void Log::set_type(uint32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Log.type)
}

// uint32 flag = 2;
inline void Log::clear_flag() {
  flag_ = 0u;
}
inline uint32_t Log::_internal_flag() const {
  return flag_;
}
inline uint32_t Log::flag() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Log.flag)
  return _internal_flag();
}
inline void Log::_internal_set_flag(uint32_t value) {
  
  flag_ = value;
}
inline void Log::set_flag(uint32_t value) {
  _internal_set_flag(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Log.flag)
}

// -------------------------------------------------------------------

// Shell

// string cmd = 1;
inline void Shell::clear_cmd() {
  cmd_.ClearToEmpty();
}
inline const std::string& Shell::cmd() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Shell.cmd)
  return _internal_cmd();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Shell::set_cmd(ArgT0&& arg0, ArgT... args) {
 
 cmd_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Shell.cmd)
}
inline std::string* Shell::mutable_cmd() {
  std::string* _s = _internal_mutable_cmd();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Shell.cmd)
  return _s;
}
inline const std::string& Shell::_internal_cmd() const {
  return cmd_.Get();
}
inline void Shell::_internal_set_cmd(const std::string& value) {
  
  cmd_.Set(value, GetArenaForAllocation());
}
inline std::string* Shell::_internal_mutable_cmd() {
  
  return cmd_.Mutable(GetArenaForAllocation());
}
inline std::string* Shell::release_cmd() {
  // @@protoc_insertion_point(field_release:axcl.runtime.system.request.Shell.cmd)
  return cmd_.Release();
}
inline void Shell::set_allocated_cmd(std::string* cmd) {
  if (cmd != nullptr) {
    
  } else {
    
  }
  cmd_.SetAllocated(cmd, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (cmd_.IsDefault()) {
    cmd_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.system.request.Shell.cmd)
}

// repeated string args = 2;
inline int Shell::_internal_args_size() const {
  return args_.size();
}
inline int Shell::args_size() const {
  return _internal_args_size();
}
inline void Shell::clear_args() {
  args_.Clear();
}
inline std::string* Shell::add_args() {
  std::string* _s = _internal_add_args();
  // @@protoc_insertion_point(field_add_mutable:axcl.runtime.system.request.Shell.args)
  return _s;
}
inline const std::string& Shell::_internal_args(int index) const {
  return args_.Get(index);
}
inline const std::string& Shell::args(int index) const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Shell.args)
  return _internal_args(index);
}
inline std::string* Shell::mutable_args(int index) {
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Shell.args)
  return args_.Mutable(index);
}
inline void Shell::set_args(int index, const std::string& value) {
  args_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Shell.args)
}
inline void Shell::set_args(int index, std::string&& value) {
  args_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Shell.args)
}
inline void Shell::set_args(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  args_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:axcl.runtime.system.request.Shell.args)
}
inline void Shell::set_args(int index, const char* value, size_t size) {
  args_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:axcl.runtime.system.request.Shell.args)
}
inline std::string* Shell::_internal_add_args() {
  return args_.Add();
}
inline void Shell::add_args(const std::string& value) {
  args_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:axcl.runtime.system.request.Shell.args)
}
inline void Shell::add_args(std::string&& value) {
  args_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:axcl.runtime.system.request.Shell.args)
}
inline void Shell::add_args(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  args_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:axcl.runtime.system.request.Shell.args)
}
inline void Shell::add_args(const char* value, size_t size) {
  args_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:axcl.runtime.system.request.Shell.args)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Shell::args() const {
  // @@protoc_insertion_point(field_list:axcl.runtime.system.request.Shell.args)
  return args_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Shell::mutable_args() {
  // @@protoc_insertion_point(field_mutable_list:axcl.runtime.system.request.Shell.args)
  return &args_;
}

// -------------------------------------------------------------------

// PCIeSubID

// uint32 vendor_id = 1;
inline void PCIeSubID::clear_vendor_id() {
  vendor_id_ = 0u;
}
inline uint32_t PCIeSubID::_internal_vendor_id() const {
  return vendor_id_;
}
inline uint32_t PCIeSubID::vendor_id() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.PCIeSubID.vendor_id)
  return _internal_vendor_id();
}
inline void PCIeSubID::_internal_set_vendor_id(uint32_t value) {
  
  vendor_id_ = value;
}
inline void PCIeSubID::set_vendor_id(uint32_t value) {
  _internal_set_vendor_id(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.PCIeSubID.vendor_id)
}

// uint32 device_id = 2;
inline void PCIeSubID::clear_device_id() {
  device_id_ = 0u;
}
inline uint32_t PCIeSubID::_internal_device_id() const {
  return device_id_;
}
inline uint32_t PCIeSubID::device_id() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.PCIeSubID.device_id)
  return _internal_device_id();
}
inline void PCIeSubID::_internal_set_device_id(uint32_t value) {
  
  device_id_ = value;
}
inline void PCIeSubID::set_device_id(uint32_t value) {
  _internal_set_device_id(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.PCIeSubID.device_id)
}

// -------------------------------------------------------------------

// Control

// .axcl.runtime.system.Command cmd = 1;
inline void Control::clear_cmd() {
  cmd_ = 0;
}
inline ::axcl::runtime::system::Command Control::_internal_cmd() const {
  return static_cast< ::axcl::runtime::system::Command >(cmd_);
}
inline ::axcl::runtime::system::Command Control::cmd() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Control.cmd)
  return _internal_cmd();
}
inline void Control::_internal_set_cmd(::axcl::runtime::system::Command value) {
  
  cmd_ = value;
}
inline void Control::set_cmd(::axcl::runtime::system::Command value) {
  _internal_set_cmd(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Control.cmd)
}

// optional uint32 pid = 2;
inline bool Control::_internal_has_pid() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Control::has_pid() const {
  return _internal_has_pid();
}
inline void Control::clear_pid() {
  pid_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline uint32_t Control::_internal_pid() const {
  return pid_;
}
inline uint32_t Control::pid() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Control.pid)
  return _internal_pid();
}
inline void Control::_internal_set_pid(uint32_t value) {
  _has_bits_[0] |= 0x00000004u;
  pid_ = value;
}
inline void Control::set_pid(uint32_t value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Control.pid)
}

// optional uint32 tid = 3;
inline bool Control::_internal_has_tid() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Control::has_tid() const {
  return _internal_has_tid();
}
inline void Control::clear_tid() {
  tid_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline uint32_t Control::_internal_tid() const {
  return tid_;
}
inline uint32_t Control::tid() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Control.tid)
  return _internal_tid();
}
inline void Control::_internal_set_tid(uint32_t value) {
  _has_bits_[0] |= 0x00000008u;
  tid_ = value;
}
inline void Control::set_tid(uint32_t value) {
  _internal_set_tid(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Control.tid)
}

// optional uint32 context = 4;
inline bool Control::_internal_has_context() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Control::has_context() const {
  return _internal_has_context();
}
inline void Control::clear_context() {
  context_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline uint32_t Control::_internal_context() const {
  return context_;
}
inline uint32_t Control::context() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Control.context)
  return _internal_context();
}
inline void Control::_internal_set_context(uint32_t value) {
  _has_bits_[0] |= 0x00000010u;
  context_ = value;
}
inline void Control::set_context(uint32_t value) {
  _internal_set_context(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Control.context)
}

// optional .axcl.runtime.system.request.Shell shell = 5;
inline bool Control::_internal_has_shell() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || shell_ != nullptr);
  return value;
}
inline bool Control::has_shell() const {
  return _internal_has_shell();
}
inline void Control::clear_shell() {
  if (shell_ != nullptr) shell_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::axcl::runtime::system::request::Shell& Control::_internal_shell() const {
  const ::axcl::runtime::system::request::Shell* p = shell_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::system::request::Shell&>(
      ::axcl::runtime::system::request::_Shell_default_instance_);
}
inline const ::axcl::runtime::system::request::Shell& Control::shell() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Control.shell)
  return _internal_shell();
}
inline void Control::unsafe_arena_set_allocated_shell(
    ::axcl::runtime::system::request::Shell* shell) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(shell_);
  }
  shell_ = shell;
  if (shell) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.system.request.Control.shell)
}
inline ::axcl::runtime::system::request::Shell* Control::release_shell() {
  _has_bits_[0] &= ~0x00000001u;
  ::axcl::runtime::system::request::Shell* temp = shell_;
  shell_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::system::request::Shell* Control::unsafe_arena_release_shell() {
  // @@protoc_insertion_point(field_release:axcl.runtime.system.request.Control.shell)
  _has_bits_[0] &= ~0x00000001u;
  ::axcl::runtime::system::request::Shell* temp = shell_;
  shell_ = nullptr;
  return temp;
}
inline ::axcl::runtime::system::request::Shell* Control::_internal_mutable_shell() {
  _has_bits_[0] |= 0x00000001u;
  if (shell_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::system::request::Shell>(GetArenaForAllocation());
    shell_ = p;
  }
  return shell_;
}
inline ::axcl::runtime::system::request::Shell* Control::mutable_shell() {
  ::axcl::runtime::system::request::Shell* _msg = _internal_mutable_shell();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Control.shell)
  return _msg;
}
inline void Control::set_allocated_shell(::axcl::runtime::system::request::Shell* shell) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete shell_;
  }
  if (shell) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(shell);
    if (message_arena != submessage_arena) {
      shell = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, shell, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  shell_ = shell;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.system.request.Control.shell)
}

// optional .axcl.runtime.system.request.PCIeSubID pcie_sub_id = 6;
inline bool Control::_internal_has_pcie_sub_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || pcie_sub_id_ != nullptr);
  return value;
}
inline bool Control::has_pcie_sub_id() const {
  return _internal_has_pcie_sub_id();
}
inline void Control::clear_pcie_sub_id() {
  if (pcie_sub_id_ != nullptr) pcie_sub_id_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::axcl::runtime::system::request::PCIeSubID& Control::_internal_pcie_sub_id() const {
  const ::axcl::runtime::system::request::PCIeSubID* p = pcie_sub_id_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::system::request::PCIeSubID&>(
      ::axcl::runtime::system::request::_PCIeSubID_default_instance_);
}
inline const ::axcl::runtime::system::request::PCIeSubID& Control::pcie_sub_id() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Control.pcie_sub_id)
  return _internal_pcie_sub_id();
}
inline void Control::unsafe_arena_set_allocated_pcie_sub_id(
    ::axcl::runtime::system::request::PCIeSubID* pcie_sub_id) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(pcie_sub_id_);
  }
  pcie_sub_id_ = pcie_sub_id;
  if (pcie_sub_id) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.system.request.Control.pcie_sub_id)
}
inline ::axcl::runtime::system::request::PCIeSubID* Control::release_pcie_sub_id() {
  _has_bits_[0] &= ~0x00000002u;
  ::axcl::runtime::system::request::PCIeSubID* temp = pcie_sub_id_;
  pcie_sub_id_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::system::request::PCIeSubID* Control::unsafe_arena_release_pcie_sub_id() {
  // @@protoc_insertion_point(field_release:axcl.runtime.system.request.Control.pcie_sub_id)
  _has_bits_[0] &= ~0x00000002u;
  ::axcl::runtime::system::request::PCIeSubID* temp = pcie_sub_id_;
  pcie_sub_id_ = nullptr;
  return temp;
}
inline ::axcl::runtime::system::request::PCIeSubID* Control::_internal_mutable_pcie_sub_id() {
  _has_bits_[0] |= 0x00000002u;
  if (pcie_sub_id_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::system::request::PCIeSubID>(GetArenaForAllocation());
    pcie_sub_id_ = p;
  }
  return pcie_sub_id_;
}
inline ::axcl::runtime::system::request::PCIeSubID* Control::mutable_pcie_sub_id() {
  ::axcl::runtime::system::request::PCIeSubID* _msg = _internal_mutable_pcie_sub_id();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Control.pcie_sub_id)
  return _msg;
}
inline void Control::set_allocated_pcie_sub_id(::axcl::runtime::system::request::PCIeSubID* pcie_sub_id) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete pcie_sub_id_;
  }
  if (pcie_sub_id) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(pcie_sub_id);
    if (message_arena != submessage_arena) {
      pcie_sub_id = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, pcie_sub_id, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  pcie_sub_id_ = pcie_sub_id;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.system.request.Control.pcie_sub_id)
}

// optional uint32 stream = 7;
inline bool Control::_internal_has_stream() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Control::has_stream() const {
  return _internal_has_stream();
}
inline void Control::clear_stream() {
  stream_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline uint32_t Control::_internal_stream() const {
  return stream_;
}
inline uint32_t Control::stream() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Control.stream)
  return _internal_stream();
}
inline void Control::_internal_set_stream(uint32_t value) {
  _has_bits_[0] |= 0x00000020u;
  stream_ = value;
}
inline void Control::set_stream(uint32_t value) {
  _internal_set_stream(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Control.stream)
}

// optional uint32 event = 8;
inline bool Control::_internal_has_event() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Control::has_event() const {
  return _internal_has_event();
}
inline void Control::clear_event() {
  event_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline uint32_t Control::_internal_event() const {
  return event_;
}
inline uint32_t Control::event() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Control.event)
  return _internal_event();
}
inline void Control::_internal_set_event(uint32_t value) {
  _has_bits_[0] |= 0x00000040u;
  event_ = value;
}
inline void Control::set_event(uint32_t value) {
  _internal_set_event(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Control.event)
}

// optional int32 timeout = 9;
inline bool Control::_internal_has_timeout() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Control::has_timeout() const {
  return _internal_has_timeout();
}
inline void Control::clear_timeout() {
  timeout_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline int32_t Control::_internal_timeout() const {
  return timeout_;
}
inline int32_t Control::timeout() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Control.timeout)
  return _internal_timeout();
}
inline void Control::_internal_set_timeout(int32_t value) {
  _has_bits_[0] |= 0x00000080u;
  timeout_ = value;
}
inline void Control::set_timeout(int32_t value) {
  _internal_set_timeout(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Control.timeout)
}

// optional uint32 noresp = 10;
inline bool Control::_internal_has_noresp() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Control::has_noresp() const {
  return _internal_has_noresp();
}
inline void Control::clear_noresp() {
  noresp_ = 0u;
  _has_bits_[0] &= ~0x00000100u;
}
inline uint32_t Control::_internal_noresp() const {
  return noresp_;
}
inline uint32_t Control::noresp() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Control.noresp)
  return _internal_noresp();
}
inline void Control::_internal_set_noresp(uint32_t value) {
  _has_bits_[0] |= 0x00000100u;
  noresp_ = value;
}
inline void Control::set_noresp(uint32_t value) {
  _internal_set_noresp(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.system.request.Control.noresp)
}

// -------------------------------------------------------------------

// Body

// optional .axcl.runtime.system.request.Alive alive = 1;
inline bool Body::_internal_has_alive() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || alive_ != nullptr);
  return value;
}
inline bool Body::has_alive() const {
  return _internal_has_alive();
}
inline void Body::clear_alive() {
  if (alive_ != nullptr) alive_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::axcl::runtime::system::request::Alive& Body::_internal_alive() const {
  const ::axcl::runtime::system::request::Alive* p = alive_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::system::request::Alive&>(
      ::axcl::runtime::system::request::_Alive_default_instance_);
}
inline const ::axcl::runtime::system::request::Alive& Body::alive() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Body.alive)
  return _internal_alive();
}
inline void Body::unsafe_arena_set_allocated_alive(
    ::axcl::runtime::system::request::Alive* alive) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(alive_);
  }
  alive_ = alive;
  if (alive) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.system.request.Body.alive)
}
inline ::axcl::runtime::system::request::Alive* Body::release_alive() {
  _has_bits_[0] &= ~0x00000001u;
  ::axcl::runtime::system::request::Alive* temp = alive_;
  alive_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::system::request::Alive* Body::unsafe_arena_release_alive() {
  // @@protoc_insertion_point(field_release:axcl.runtime.system.request.Body.alive)
  _has_bits_[0] &= ~0x00000001u;
  ::axcl::runtime::system::request::Alive* temp = alive_;
  alive_ = nullptr;
  return temp;
}
inline ::axcl::runtime::system::request::Alive* Body::_internal_mutable_alive() {
  _has_bits_[0] |= 0x00000001u;
  if (alive_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::system::request::Alive>(GetArenaForAllocation());
    alive_ = p;
  }
  return alive_;
}
inline ::axcl::runtime::system::request::Alive* Body::mutable_alive() {
  ::axcl::runtime::system::request::Alive* _msg = _internal_mutable_alive();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Body.alive)
  return _msg;
}
inline void Body::set_allocated_alive(::axcl::runtime::system::request::Alive* alive) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete alive_;
  }
  if (alive) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(alive);
    if (message_arena != submessage_arena) {
      alive = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, alive, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  alive_ = alive;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.system.request.Body.alive)
}

// optional .axcl.runtime.system.request.Latency latency = 2;
inline bool Body::_internal_has_latency() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || latency_ != nullptr);
  return value;
}
inline bool Body::has_latency() const {
  return _internal_has_latency();
}
inline void Body::clear_latency() {
  if (latency_ != nullptr) latency_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::axcl::runtime::system::request::Latency& Body::_internal_latency() const {
  const ::axcl::runtime::system::request::Latency* p = latency_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::system::request::Latency&>(
      ::axcl::runtime::system::request::_Latency_default_instance_);
}
inline const ::axcl::runtime::system::request::Latency& Body::latency() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Body.latency)
  return _internal_latency();
}
inline void Body::unsafe_arena_set_allocated_latency(
    ::axcl::runtime::system::request::Latency* latency) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(latency_);
  }
  latency_ = latency;
  if (latency) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.system.request.Body.latency)
}
inline ::axcl::runtime::system::request::Latency* Body::release_latency() {
  _has_bits_[0] &= ~0x00000002u;
  ::axcl::runtime::system::request::Latency* temp = latency_;
  latency_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::system::request::Latency* Body::unsafe_arena_release_latency() {
  // @@protoc_insertion_point(field_release:axcl.runtime.system.request.Body.latency)
  _has_bits_[0] &= ~0x00000002u;
  ::axcl::runtime::system::request::Latency* temp = latency_;
  latency_ = nullptr;
  return temp;
}
inline ::axcl::runtime::system::request::Latency* Body::_internal_mutable_latency() {
  _has_bits_[0] |= 0x00000002u;
  if (latency_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::system::request::Latency>(GetArenaForAllocation());
    latency_ = p;
  }
  return latency_;
}
inline ::axcl::runtime::system::request::Latency* Body::mutable_latency() {
  ::axcl::runtime::system::request::Latency* _msg = _internal_mutable_latency();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Body.latency)
  return _msg;
}
inline void Body::set_allocated_latency(::axcl::runtime::system::request::Latency* latency) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete latency_;
  }
  if (latency) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(latency);
    if (message_arena != submessage_arena) {
      latency = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, latency, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  latency_ = latency;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.system.request.Body.latency)
}

// optional .axcl.runtime.system.request.Log log = 3;
inline bool Body::_internal_has_log() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || log_ != nullptr);
  return value;
}
inline bool Body::has_log() const {
  return _internal_has_log();
}
inline void Body::clear_log() {
  if (log_ != nullptr) log_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::axcl::runtime::system::request::Log& Body::_internal_log() const {
  const ::axcl::runtime::system::request::Log* p = log_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::system::request::Log&>(
      ::axcl::runtime::system::request::_Log_default_instance_);
}
inline const ::axcl::runtime::system::request::Log& Body::log() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Body.log)
  return _internal_log();
}
inline void Body::unsafe_arena_set_allocated_log(
    ::axcl::runtime::system::request::Log* log) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(log_);
  }
  log_ = log;
  if (log) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.system.request.Body.log)
}
inline ::axcl::runtime::system::request::Log* Body::release_log() {
  _has_bits_[0] &= ~0x00000004u;
  ::axcl::runtime::system::request::Log* temp = log_;
  log_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::system::request::Log* Body::unsafe_arena_release_log() {
  // @@protoc_insertion_point(field_release:axcl.runtime.system.request.Body.log)
  _has_bits_[0] &= ~0x00000004u;
  ::axcl::runtime::system::request::Log* temp = log_;
  log_ = nullptr;
  return temp;
}
inline ::axcl::runtime::system::request::Log* Body::_internal_mutable_log() {
  _has_bits_[0] |= 0x00000004u;
  if (log_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::system::request::Log>(GetArenaForAllocation());
    log_ = p;
  }
  return log_;
}
inline ::axcl::runtime::system::request::Log* Body::mutable_log() {
  ::axcl::runtime::system::request::Log* _msg = _internal_mutable_log();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Body.log)
  return _msg;
}
inline void Body::set_allocated_log(::axcl::runtime::system::request::Log* log) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete log_;
  }
  if (log) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(log);
    if (message_arena != submessage_arena) {
      log = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, log, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  log_ = log;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.system.request.Body.log)
}

// optional .axcl.runtime.system.request.Control control = 4;
inline bool Body::_internal_has_control() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || control_ != nullptr);
  return value;
}
inline bool Body::has_control() const {
  return _internal_has_control();
}
inline void Body::clear_control() {
  if (control_ != nullptr) control_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::axcl::runtime::system::request::Control& Body::_internal_control() const {
  const ::axcl::runtime::system::request::Control* p = control_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::system::request::Control&>(
      ::axcl::runtime::system::request::_Control_default_instance_);
}
inline const ::axcl::runtime::system::request::Control& Body::control() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Body.control)
  return _internal_control();
}
inline void Body::unsafe_arena_set_allocated_control(
    ::axcl::runtime::system::request::Control* control) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(control_);
  }
  control_ = control;
  if (control) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.system.request.Body.control)
}
inline ::axcl::runtime::system::request::Control* Body::release_control() {
  _has_bits_[0] &= ~0x00000008u;
  ::axcl::runtime::system::request::Control* temp = control_;
  control_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::system::request::Control* Body::unsafe_arena_release_control() {
  // @@protoc_insertion_point(field_release:axcl.runtime.system.request.Body.control)
  _has_bits_[0] &= ~0x00000008u;
  ::axcl::runtime::system::request::Control* temp = control_;
  control_ = nullptr;
  return temp;
}
inline ::axcl::runtime::system::request::Control* Body::_internal_mutable_control() {
  _has_bits_[0] |= 0x00000008u;
  if (control_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::system::request::Control>(GetArenaForAllocation());
    control_ = p;
  }
  return control_;
}
inline ::axcl::runtime::system::request::Control* Body::mutable_control() {
  ::axcl::runtime::system::request::Control* _msg = _internal_mutable_control();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Body.control)
  return _msg;
}
inline void Body::set_allocated_control(::axcl::runtime::system::request::Control* control) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete control_;
  }
  if (control) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(control);
    if (message_arena != submessage_arena) {
      control = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, control, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  control_ = control;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.system.request.Body.control)
}

// -------------------------------------------------------------------

// Payload

// .axcl.runtime.system.request.Head head = 1;
inline bool Payload::_internal_has_head() const {
  return this != internal_default_instance() && head_ != nullptr;
}
inline bool Payload::has_head() const {
  return _internal_has_head();
}
inline void Payload::clear_head() {
  if (GetArenaForAllocation() == nullptr && head_ != nullptr) {
    delete head_;
  }
  head_ = nullptr;
}
inline const ::axcl::runtime::system::request::Head& Payload::_internal_head() const {
  const ::axcl::runtime::system::request::Head* p = head_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::system::request::Head&>(
      ::axcl::runtime::system::request::_Head_default_instance_);
}
inline const ::axcl::runtime::system::request::Head& Payload::head() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Payload.head)
  return _internal_head();
}
inline void Payload::unsafe_arena_set_allocated_head(
    ::axcl::runtime::system::request::Head* head) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(head_);
  }
  head_ = head;
  if (head) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.system.request.Payload.head)
}
inline ::axcl::runtime::system::request::Head* Payload::release_head() {
  
  ::axcl::runtime::system::request::Head* temp = head_;
  head_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::system::request::Head* Payload::unsafe_arena_release_head() {
  // @@protoc_insertion_point(field_release:axcl.runtime.system.request.Payload.head)
  
  ::axcl::runtime::system::request::Head* temp = head_;
  head_ = nullptr;
  return temp;
}
inline ::axcl::runtime::system::request::Head* Payload::_internal_mutable_head() {
  
  if (head_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::system::request::Head>(GetArenaForAllocation());
    head_ = p;
  }
  return head_;
}
inline ::axcl::runtime::system::request::Head* Payload::mutable_head() {
  ::axcl::runtime::system::request::Head* _msg = _internal_mutable_head();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Payload.head)
  return _msg;
}
inline void Payload::set_allocated_head(::axcl::runtime::system::request::Head* head) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete head_;
  }
  if (head) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(head);
    if (message_arena != submessage_arena) {
      head = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, head, submessage_arena);
    }
    
  } else {
    
  }
  head_ = head;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.system.request.Payload.head)
}

// .axcl.runtime.system.request.Body body = 2;
inline bool Payload::_internal_has_body() const {
  return this != internal_default_instance() && body_ != nullptr;
}
inline bool Payload::has_body() const {
  return _internal_has_body();
}
inline void Payload::clear_body() {
  if (GetArenaForAllocation() == nullptr && body_ != nullptr) {
    delete body_;
  }
  body_ = nullptr;
}
inline const ::axcl::runtime::system::request::Body& Payload::_internal_body() const {
  const ::axcl::runtime::system::request::Body* p = body_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::system::request::Body&>(
      ::axcl::runtime::system::request::_Body_default_instance_);
}
inline const ::axcl::runtime::system::request::Body& Payload::body() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.system.request.Payload.body)
  return _internal_body();
}
inline void Payload::unsafe_arena_set_allocated_body(
    ::axcl::runtime::system::request::Body* body) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  body_ = body;
  if (body) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.system.request.Payload.body)
}
inline ::axcl::runtime::system::request::Body* Payload::release_body() {
  
  ::axcl::runtime::system::request::Body* temp = body_;
  body_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::system::request::Body* Payload::unsafe_arena_release_body() {
  // @@protoc_insertion_point(field_release:axcl.runtime.system.request.Payload.body)
  
  ::axcl::runtime::system::request::Body* temp = body_;
  body_ = nullptr;
  return temp;
}
inline ::axcl::runtime::system::request::Body* Payload::_internal_mutable_body() {
  
  if (body_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::system::request::Body>(GetArenaForAllocation());
    body_ = p;
  }
  return body_;
}
inline ::axcl::runtime::system::request::Body* Payload::mutable_body() {
  ::axcl::runtime::system::request::Body* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.system.request.Payload.body)
  return _msg;
}
inline void Payload::set_allocated_body(::axcl::runtime::system::request::Body* body) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete body_;
  }
  if (body) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(body);
    if (message_arena != submessage_arena) {
      body = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body, submessage_arena);
    }
    
  } else {
    
  }
  body_ = body;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.system.request.Payload.body)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace request
}  // namespace system
}  // namespace runtime
}  // namespace axcl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fsystem_2frequest_2eproto
