/**************************************************************************************************
 *
 * Copyright (c) 2019-2024 Axera Semiconductor Co., Ltd. All Rights Reserved.
 *
 * This source file is the property of Axera Semiconductor Co., Ltd. and
 * may not be copied or distributed in any isomorphic form without the prior
 * written consent of Axera Semiconductor Co., Ltd.
 *
 **************************************************************************************************/

syntax = "proto3";
package axcl.runtime.p2p;
option optimize_for = @AXCL_PROTOCOL_OPTIMIZED_OPTION@;


enum Api
{
    P2P_SETUP_CONFIG = 0;
    P2P_START_BANDWIDTH_TEST = 1;
    P2P_REMOVE_CONFIG = 2;
}
