// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/runtime/response.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fresponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fresponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "protocol/runtime/type.pb.h"
#include "protocol/runtime/system/response.pb.h"
#include "protocol/runtime/memory/response.pb.h"
#include "protocol/runtime/engine/response.pb.h"
#include "protocol/runtime/p2p/response.pb.h"
#include "protocol/runtime/usrwork/response.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2fruntime_2fresponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fruntime_2fresponse_2eproto {
  static const uint32_t offsets[];
};
namespace axcl {
namespace runtime {
namespace response {
class Body;
struct BodyDefaultTypeInternal;
extern BodyDefaultTypeInternal _Body_default_instance_;
class Head;
struct HeadDefaultTypeInternal;
extern HeadDefaultTypeInternal _Head_default_instance_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
}  // namespace response
}  // namespace runtime
}  // namespace axcl
PROTOBUF_NAMESPACE_OPEN
template<> ::axcl::runtime::response::Body* Arena::CreateMaybeMessage<::axcl::runtime::response::Body>(Arena*);
template<> ::axcl::runtime::response::Head* Arena::CreateMaybeMessage<::axcl::runtime::response::Head>(Arena*);
template<> ::axcl::runtime::response::Payload* Arena::CreateMaybeMessage<::axcl::runtime::response::Payload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace axcl {
namespace runtime {
namespace response {

// ===================================================================

class Head final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.response.Head) */ {
 public:
  inline Head() : Head(nullptr) {}
  ~Head() override;
  explicit PROTOBUF_CONSTEXPR Head(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Head(const Head& from);
  Head(Head&& from) noexcept
    : Head() {
    *this = ::std::move(from);
  }

  inline Head& operator=(const Head& from) {
    CopyFrom(from);
    return *this;
  }
  inline Head& operator=(Head&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Head& default_instance() {
    return *internal_default_instance();
  }
  static inline const Head* internal_default_instance() {
    return reinterpret_cast<const Head*>(
               &_Head_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Head& a, Head& b) {
    a.Swap(&b);
  }
  inline void Swap(Head* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Head* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Head* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Head>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Head& from);
  void MergeFrom(const Head& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Head* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.response.Head";
  }
  protected:
  explicit Head(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModuleFieldNumber = 1,
  };
  // .axcl.runtime.Module module = 1;
  void clear_module();
  ::axcl::runtime::Module module() const;
  void set_module(::axcl::runtime::Module value);
  private:
  ::axcl::runtime::Module _internal_module() const;
  void _internal_set_module(::axcl::runtime::Module value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.response.Head)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int module_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class Body final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.response.Body) */ {
 public:
  inline Body() : Body(nullptr) {}
  ~Body() override;
  explicit PROTOBUF_CONSTEXPR Body(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Body(const Body& from);
  Body(Body&& from) noexcept
    : Body() {
    *this = ::std::move(from);
  }

  inline Body& operator=(const Body& from) {
    CopyFrom(from);
    return *this;
  }
  inline Body& operator=(Body&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Body& default_instance() {
    return *internal_default_instance();
  }
  static inline const Body* internal_default_instance() {
    return reinterpret_cast<const Body*>(
               &_Body_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Body& a, Body& b) {
    a.Swap(&b);
  }
  inline void Swap(Body* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Body* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Body* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Body>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Body& from);
  void MergeFrom(const Body& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Body* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.response.Body";
  }
  protected:
  explicit Body(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSystemFieldNumber = 1,
    kMemoryFieldNumber = 2,
    kEngineFieldNumber = 3,
    kP2PFieldNumber = 4,
    kUsrworkFieldNumber = 5,
  };
  // optional .axcl.runtime.system.response.Payload system = 1;
  bool has_system() const;
  private:
  bool _internal_has_system() const;
  public:
  void clear_system();
  const ::axcl::runtime::system::response::Payload& system() const;
  PROTOBUF_NODISCARD ::axcl::runtime::system::response::Payload* release_system();
  ::axcl::runtime::system::response::Payload* mutable_system();
  void set_allocated_system(::axcl::runtime::system::response::Payload* system);
  private:
  const ::axcl::runtime::system::response::Payload& _internal_system() const;
  ::axcl::runtime::system::response::Payload* _internal_mutable_system();
  public:
  void unsafe_arena_set_allocated_system(
      ::axcl::runtime::system::response::Payload* system);
  ::axcl::runtime::system::response::Payload* unsafe_arena_release_system();

  // optional .axcl.runtime.memory.response.Payload memory = 2;
  bool has_memory() const;
  private:
  bool _internal_has_memory() const;
  public:
  void clear_memory();
  const ::axcl::runtime::memory::response::Payload& memory() const;
  PROTOBUF_NODISCARD ::axcl::runtime::memory::response::Payload* release_memory();
  ::axcl::runtime::memory::response::Payload* mutable_memory();
  void set_allocated_memory(::axcl::runtime::memory::response::Payload* memory);
  private:
  const ::axcl::runtime::memory::response::Payload& _internal_memory() const;
  ::axcl::runtime::memory::response::Payload* _internal_mutable_memory();
  public:
  void unsafe_arena_set_allocated_memory(
      ::axcl::runtime::memory::response::Payload* memory);
  ::axcl::runtime::memory::response::Payload* unsafe_arena_release_memory();

  // optional .axcl.runtime.engine.response.Payload engine = 3;
  bool has_engine() const;
  private:
  bool _internal_has_engine() const;
  public:
  void clear_engine();
  const ::axcl::runtime::engine::response::Payload& engine() const;
  PROTOBUF_NODISCARD ::axcl::runtime::engine::response::Payload* release_engine();
  ::axcl::runtime::engine::response::Payload* mutable_engine();
  void set_allocated_engine(::axcl::runtime::engine::response::Payload* engine);
  private:
  const ::axcl::runtime::engine::response::Payload& _internal_engine() const;
  ::axcl::runtime::engine::response::Payload* _internal_mutable_engine();
  public:
  void unsafe_arena_set_allocated_engine(
      ::axcl::runtime::engine::response::Payload* engine);
  ::axcl::runtime::engine::response::Payload* unsafe_arena_release_engine();

  // optional .axcl.runtime.p2p.response.Payload p2p = 4;
  bool has_p2p() const;
  private:
  bool _internal_has_p2p() const;
  public:
  void clear_p2p();
  const ::axcl::runtime::p2p::response::Payload& p2p() const;
  PROTOBUF_NODISCARD ::axcl::runtime::p2p::response::Payload* release_p2p();
  ::axcl::runtime::p2p::response::Payload* mutable_p2p();
  void set_allocated_p2p(::axcl::runtime::p2p::response::Payload* p2p);
  private:
  const ::axcl::runtime::p2p::response::Payload& _internal_p2p() const;
  ::axcl::runtime::p2p::response::Payload* _internal_mutable_p2p();
  public:
  void unsafe_arena_set_allocated_p2p(
      ::axcl::runtime::p2p::response::Payload* p2p);
  ::axcl::runtime::p2p::response::Payload* unsafe_arena_release_p2p();

  // optional .axcl.runtime.usrwork.response.Payload usrwork = 5;
  bool has_usrwork() const;
  private:
  bool _internal_has_usrwork() const;
  public:
  void clear_usrwork();
  const ::axcl::runtime::usrwork::response::Payload& usrwork() const;
  PROTOBUF_NODISCARD ::axcl::runtime::usrwork::response::Payload* release_usrwork();
  ::axcl::runtime::usrwork::response::Payload* mutable_usrwork();
  void set_allocated_usrwork(::axcl::runtime::usrwork::response::Payload* usrwork);
  private:
  const ::axcl::runtime::usrwork::response::Payload& _internal_usrwork() const;
  ::axcl::runtime::usrwork::response::Payload* _internal_mutable_usrwork();
  public:
  void unsafe_arena_set_allocated_usrwork(
      ::axcl::runtime::usrwork::response::Payload* usrwork);
  ::axcl::runtime::usrwork::response::Payload* unsafe_arena_release_usrwork();

  // @@protoc_insertion_point(class_scope:axcl.runtime.response.Body)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::axcl::runtime::system::response::Payload* system_;
  ::axcl::runtime::memory::response::Payload* memory_;
  ::axcl::runtime::engine::response::Payload* engine_;
  ::axcl::runtime::p2p::response::Payload* p2p_;
  ::axcl::runtime::usrwork::response::Payload* usrwork_;
  friend struct ::TableStruct_protocol_2fruntime_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.response.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Payload& from);
  void MergeFrom(const Payload& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.response.Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeadFieldNumber = 1,
    kBodyFieldNumber = 2,
  };
  // .axcl.runtime.response.Head head = 1;
  bool has_head() const;
  private:
  bool _internal_has_head() const;
  public:
  void clear_head();
  const ::axcl::runtime::response::Head& head() const;
  PROTOBUF_NODISCARD ::axcl::runtime::response::Head* release_head();
  ::axcl::runtime::response::Head* mutable_head();
  void set_allocated_head(::axcl::runtime::response::Head* head);
  private:
  const ::axcl::runtime::response::Head& _internal_head() const;
  ::axcl::runtime::response::Head* _internal_mutable_head();
  public:
  void unsafe_arena_set_allocated_head(
      ::axcl::runtime::response::Head* head);
  ::axcl::runtime::response::Head* unsafe_arena_release_head();

  // .axcl.runtime.response.Body body = 2;
  bool has_body() const;
  private:
  bool _internal_has_body() const;
  public:
  void clear_body();
  const ::axcl::runtime::response::Body& body() const;
  PROTOBUF_NODISCARD ::axcl::runtime::response::Body* release_body();
  ::axcl::runtime::response::Body* mutable_body();
  void set_allocated_body(::axcl::runtime::response::Body* body);
  private:
  const ::axcl::runtime::response::Body& _internal_body() const;
  ::axcl::runtime::response::Body* _internal_mutable_body();
  public:
  void unsafe_arena_set_allocated_body(
      ::axcl::runtime::response::Body* body);
  ::axcl::runtime::response::Body* unsafe_arena_release_body();

  // @@protoc_insertion_point(class_scope:axcl.runtime.response.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::axcl::runtime::response::Head* head_;
  ::axcl::runtime::response::Body* body_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fresponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Head

// .axcl.runtime.Module module = 1;
inline void Head::clear_module() {
  module_ = 0;
}
inline ::axcl::runtime::Module Head::_internal_module() const {
  return static_cast< ::axcl::runtime::Module >(module_);
}
inline ::axcl::runtime::Module Head::module() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.response.Head.module)
  return _internal_module();
}
inline void Head::_internal_set_module(::axcl::runtime::Module value) {
  
  module_ = value;
}
inline void Head::set_module(::axcl::runtime::Module value) {
  _internal_set_module(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.response.Head.module)
}

// -------------------------------------------------------------------

// Body

// optional .axcl.runtime.system.response.Payload system = 1;
inline bool Body::_internal_has_system() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || system_ != nullptr);
  return value;
}
inline bool Body::has_system() const {
  return _internal_has_system();
}
inline const ::axcl::runtime::system::response::Payload& Body::_internal_system() const {
  const ::axcl::runtime::system::response::Payload* p = system_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::system::response::Payload&>(
      ::axcl::runtime::system::response::_Payload_default_instance_);
}
inline const ::axcl::runtime::system::response::Payload& Body::system() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.response.Body.system)
  return _internal_system();
}
inline void Body::unsafe_arena_set_allocated_system(
    ::axcl::runtime::system::response::Payload* system) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(system_);
  }
  system_ = system;
  if (system) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.response.Body.system)
}
inline ::axcl::runtime::system::response::Payload* Body::release_system() {
  _has_bits_[0] &= ~0x00000001u;
  ::axcl::runtime::system::response::Payload* temp = system_;
  system_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::system::response::Payload* Body::unsafe_arena_release_system() {
  // @@protoc_insertion_point(field_release:axcl.runtime.response.Body.system)
  _has_bits_[0] &= ~0x00000001u;
  ::axcl::runtime::system::response::Payload* temp = system_;
  system_ = nullptr;
  return temp;
}
inline ::axcl::runtime::system::response::Payload* Body::_internal_mutable_system() {
  _has_bits_[0] |= 0x00000001u;
  if (system_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::system::response::Payload>(GetArenaForAllocation());
    system_ = p;
  }
  return system_;
}
inline ::axcl::runtime::system::response::Payload* Body::mutable_system() {
  ::axcl::runtime::system::response::Payload* _msg = _internal_mutable_system();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.response.Body.system)
  return _msg;
}
inline void Body::set_allocated_system(::axcl::runtime::system::response::Payload* system) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(system_);
  }
  if (system) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(system));
    if (message_arena != submessage_arena) {
      system = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, system, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  system_ = system;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.response.Body.system)
}

// optional .axcl.runtime.memory.response.Payload memory = 2;
inline bool Body::_internal_has_memory() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || memory_ != nullptr);
  return value;
}
inline bool Body::has_memory() const {
  return _internal_has_memory();
}
inline const ::axcl::runtime::memory::response::Payload& Body::_internal_memory() const {
  const ::axcl::runtime::memory::response::Payload* p = memory_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::memory::response::Payload&>(
      ::axcl::runtime::memory::response::_Payload_default_instance_);
}
inline const ::axcl::runtime::memory::response::Payload& Body::memory() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.response.Body.memory)
  return _internal_memory();
}
inline void Body::unsafe_arena_set_allocated_memory(
    ::axcl::runtime::memory::response::Payload* memory) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(memory_);
  }
  memory_ = memory;
  if (memory) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.response.Body.memory)
}
inline ::axcl::runtime::memory::response::Payload* Body::release_memory() {
  _has_bits_[0] &= ~0x00000002u;
  ::axcl::runtime::memory::response::Payload* temp = memory_;
  memory_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::memory::response::Payload* Body::unsafe_arena_release_memory() {
  // @@protoc_insertion_point(field_release:axcl.runtime.response.Body.memory)
  _has_bits_[0] &= ~0x00000002u;
  ::axcl::runtime::memory::response::Payload* temp = memory_;
  memory_ = nullptr;
  return temp;
}
inline ::axcl::runtime::memory::response::Payload* Body::_internal_mutable_memory() {
  _has_bits_[0] |= 0x00000002u;
  if (memory_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::memory::response::Payload>(GetArenaForAllocation());
    memory_ = p;
  }
  return memory_;
}
inline ::axcl::runtime::memory::response::Payload* Body::mutable_memory() {
  ::axcl::runtime::memory::response::Payload* _msg = _internal_mutable_memory();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.response.Body.memory)
  return _msg;
}
inline void Body::set_allocated_memory(::axcl::runtime::memory::response::Payload* memory) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(memory_);
  }
  if (memory) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(memory));
    if (message_arena != submessage_arena) {
      memory = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, memory, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  memory_ = memory;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.response.Body.memory)
}

// optional .axcl.runtime.engine.response.Payload engine = 3;
inline bool Body::_internal_has_engine() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || engine_ != nullptr);
  return value;
}
inline bool Body::has_engine() const {
  return _internal_has_engine();
}
inline const ::axcl::runtime::engine::response::Payload& Body::_internal_engine() const {
  const ::axcl::runtime::engine::response::Payload* p = engine_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::engine::response::Payload&>(
      ::axcl::runtime::engine::response::_Payload_default_instance_);
}
inline const ::axcl::runtime::engine::response::Payload& Body::engine() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.response.Body.engine)
  return _internal_engine();
}
inline void Body::unsafe_arena_set_allocated_engine(
    ::axcl::runtime::engine::response::Payload* engine) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(engine_);
  }
  engine_ = engine;
  if (engine) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.response.Body.engine)
}
inline ::axcl::runtime::engine::response::Payload* Body::release_engine() {
  _has_bits_[0] &= ~0x00000004u;
  ::axcl::runtime::engine::response::Payload* temp = engine_;
  engine_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::engine::response::Payload* Body::unsafe_arena_release_engine() {
  // @@protoc_insertion_point(field_release:axcl.runtime.response.Body.engine)
  _has_bits_[0] &= ~0x00000004u;
  ::axcl::runtime::engine::response::Payload* temp = engine_;
  engine_ = nullptr;
  return temp;
}
inline ::axcl::runtime::engine::response::Payload* Body::_internal_mutable_engine() {
  _has_bits_[0] |= 0x00000004u;
  if (engine_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::engine::response::Payload>(GetArenaForAllocation());
    engine_ = p;
  }
  return engine_;
}
inline ::axcl::runtime::engine::response::Payload* Body::mutable_engine() {
  ::axcl::runtime::engine::response::Payload* _msg = _internal_mutable_engine();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.response.Body.engine)
  return _msg;
}
inline void Body::set_allocated_engine(::axcl::runtime::engine::response::Payload* engine) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(engine_);
  }
  if (engine) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(engine));
    if (message_arena != submessage_arena) {
      engine = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, engine, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  engine_ = engine;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.response.Body.engine)
}

// optional .axcl.runtime.p2p.response.Payload p2p = 4;
inline bool Body::_internal_has_p2p() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || p2p_ != nullptr);
  return value;
}
inline bool Body::has_p2p() const {
  return _internal_has_p2p();
}
inline const ::axcl::runtime::p2p::response::Payload& Body::_internal_p2p() const {
  const ::axcl::runtime::p2p::response::Payload* p = p2p_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::p2p::response::Payload&>(
      ::axcl::runtime::p2p::response::_Payload_default_instance_);
}
inline const ::axcl::runtime::p2p::response::Payload& Body::p2p() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.response.Body.p2p)
  return _internal_p2p();
}
inline void Body::unsafe_arena_set_allocated_p2p(
    ::axcl::runtime::p2p::response::Payload* p2p) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(p2p_);
  }
  p2p_ = p2p;
  if (p2p) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.response.Body.p2p)
}
inline ::axcl::runtime::p2p::response::Payload* Body::release_p2p() {
  _has_bits_[0] &= ~0x00000008u;
  ::axcl::runtime::p2p::response::Payload* temp = p2p_;
  p2p_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::p2p::response::Payload* Body::unsafe_arena_release_p2p() {
  // @@protoc_insertion_point(field_release:axcl.runtime.response.Body.p2p)
  _has_bits_[0] &= ~0x00000008u;
  ::axcl::runtime::p2p::response::Payload* temp = p2p_;
  p2p_ = nullptr;
  return temp;
}
inline ::axcl::runtime::p2p::response::Payload* Body::_internal_mutable_p2p() {
  _has_bits_[0] |= 0x00000008u;
  if (p2p_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::p2p::response::Payload>(GetArenaForAllocation());
    p2p_ = p;
  }
  return p2p_;
}
inline ::axcl::runtime::p2p::response::Payload* Body::mutable_p2p() {
  ::axcl::runtime::p2p::response::Payload* _msg = _internal_mutable_p2p();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.response.Body.p2p)
  return _msg;
}
inline void Body::set_allocated_p2p(::axcl::runtime::p2p::response::Payload* p2p) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(p2p_);
  }
  if (p2p) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(p2p));
    if (message_arena != submessage_arena) {
      p2p = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, p2p, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  p2p_ = p2p;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.response.Body.p2p)
}

// optional .axcl.runtime.usrwork.response.Payload usrwork = 5;
inline bool Body::_internal_has_usrwork() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || usrwork_ != nullptr);
  return value;
}
inline bool Body::has_usrwork() const {
  return _internal_has_usrwork();
}
inline const ::axcl::runtime::usrwork::response::Payload& Body::_internal_usrwork() const {
  const ::axcl::runtime::usrwork::response::Payload* p = usrwork_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::usrwork::response::Payload&>(
      ::axcl::runtime::usrwork::response::_Payload_default_instance_);
}
inline const ::axcl::runtime::usrwork::response::Payload& Body::usrwork() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.response.Body.usrwork)
  return _internal_usrwork();
}
inline void Body::unsafe_arena_set_allocated_usrwork(
    ::axcl::runtime::usrwork::response::Payload* usrwork) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(usrwork_);
  }
  usrwork_ = usrwork;
  if (usrwork) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.response.Body.usrwork)
}
inline ::axcl::runtime::usrwork::response::Payload* Body::release_usrwork() {
  _has_bits_[0] &= ~0x00000010u;
  ::axcl::runtime::usrwork::response::Payload* temp = usrwork_;
  usrwork_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::usrwork::response::Payload* Body::unsafe_arena_release_usrwork() {
  // @@protoc_insertion_point(field_release:axcl.runtime.response.Body.usrwork)
  _has_bits_[0] &= ~0x00000010u;
  ::axcl::runtime::usrwork::response::Payload* temp = usrwork_;
  usrwork_ = nullptr;
  return temp;
}
inline ::axcl::runtime::usrwork::response::Payload* Body::_internal_mutable_usrwork() {
  _has_bits_[0] |= 0x00000010u;
  if (usrwork_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::usrwork::response::Payload>(GetArenaForAllocation());
    usrwork_ = p;
  }
  return usrwork_;
}
inline ::axcl::runtime::usrwork::response::Payload* Body::mutable_usrwork() {
  ::axcl::runtime::usrwork::response::Payload* _msg = _internal_mutable_usrwork();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.response.Body.usrwork)
  return _msg;
}
inline void Body::set_allocated_usrwork(::axcl::runtime::usrwork::response::Payload* usrwork) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(usrwork_);
  }
  if (usrwork) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(usrwork));
    if (message_arena != submessage_arena) {
      usrwork = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, usrwork, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  usrwork_ = usrwork;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.response.Body.usrwork)
}

// -------------------------------------------------------------------

// Payload

// .axcl.runtime.response.Head head = 1;
inline bool Payload::_internal_has_head() const {
  return this != internal_default_instance() && head_ != nullptr;
}
inline bool Payload::has_head() const {
  return _internal_has_head();
}
inline void Payload::clear_head() {
  if (GetArenaForAllocation() == nullptr && head_ != nullptr) {
    delete head_;
  }
  head_ = nullptr;
}
inline const ::axcl::runtime::response::Head& Payload::_internal_head() const {
  const ::axcl::runtime::response::Head* p = head_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::response::Head&>(
      ::axcl::runtime::response::_Head_default_instance_);
}
inline const ::axcl::runtime::response::Head& Payload::head() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.response.Payload.head)
  return _internal_head();
}
inline void Payload::unsafe_arena_set_allocated_head(
    ::axcl::runtime::response::Head* head) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(head_);
  }
  head_ = head;
  if (head) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.response.Payload.head)
}
inline ::axcl::runtime::response::Head* Payload::release_head() {
  
  ::axcl::runtime::response::Head* temp = head_;
  head_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::response::Head* Payload::unsafe_arena_release_head() {
  // @@protoc_insertion_point(field_release:axcl.runtime.response.Payload.head)
  
  ::axcl::runtime::response::Head* temp = head_;
  head_ = nullptr;
  return temp;
}
inline ::axcl::runtime::response::Head* Payload::_internal_mutable_head() {
  
  if (head_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::response::Head>(GetArenaForAllocation());
    head_ = p;
  }
  return head_;
}
inline ::axcl::runtime::response::Head* Payload::mutable_head() {
  ::axcl::runtime::response::Head* _msg = _internal_mutable_head();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.response.Payload.head)
  return _msg;
}
inline void Payload::set_allocated_head(::axcl::runtime::response::Head* head) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete head_;
  }
  if (head) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(head);
    if (message_arena != submessage_arena) {
      head = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, head, submessage_arena);
    }
    
  } else {
    
  }
  head_ = head;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.response.Payload.head)
}

// .axcl.runtime.response.Body body = 2;
inline bool Payload::_internal_has_body() const {
  return this != internal_default_instance() && body_ != nullptr;
}
inline bool Payload::has_body() const {
  return _internal_has_body();
}
inline void Payload::clear_body() {
  if (GetArenaForAllocation() == nullptr && body_ != nullptr) {
    delete body_;
  }
  body_ = nullptr;
}
inline const ::axcl::runtime::response::Body& Payload::_internal_body() const {
  const ::axcl::runtime::response::Body* p = body_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::response::Body&>(
      ::axcl::runtime::response::_Body_default_instance_);
}
inline const ::axcl::runtime::response::Body& Payload::body() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.response.Payload.body)
  return _internal_body();
}
inline void Payload::unsafe_arena_set_allocated_body(
    ::axcl::runtime::response::Body* body) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  body_ = body;
  if (body) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.response.Payload.body)
}
inline ::axcl::runtime::response::Body* Payload::release_body() {
  
  ::axcl::runtime::response::Body* temp = body_;
  body_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::response::Body* Payload::unsafe_arena_release_body() {
  // @@protoc_insertion_point(field_release:axcl.runtime.response.Payload.body)
  
  ::axcl::runtime::response::Body* temp = body_;
  body_ = nullptr;
  return temp;
}
inline ::axcl::runtime::response::Body* Payload::_internal_mutable_body() {
  
  if (body_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::response::Body>(GetArenaForAllocation());
    body_ = p;
  }
  return body_;
}
inline ::axcl::runtime::response::Body* Payload::mutable_body() {
  ::axcl::runtime::response::Body* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.response.Payload.body)
  return _msg;
}
inline void Payload::set_allocated_body(::axcl::runtime::response::Body* body) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete body_;
  }
  if (body) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(body);
    if (message_arena != submessage_arena) {
      body = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body, submessage_arena);
    }
    
  } else {
    
  }
  body_ = body;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.response.Payload.body)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace response
}  // namespace runtime
}  // namespace axcl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fresponse_2eproto
