// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/type.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2ftype_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2ftype_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2ftype_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2ftype_2eproto {
  static const uint32_t offsets[];
};
namespace axcl {
class Environment;
struct EnvironmentDefaultTypeInternal;
extern EnvironmentDefaultTypeInternal _Environment_default_instance_;
class Version;
struct VersionDefaultTypeInternal;
extern VersionDefaultTypeInternal _Version_default_instance_;
}  // namespace axcl
PROTOBUF_NAMESPACE_OPEN
template<> ::axcl::Environment* Arena::CreateMaybeMessage<::axcl::Environment>(Arena*);
template<> ::axcl::Version* Arena::CreateMaybeMessage<::axcl::Version>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace axcl {

enum Module : int {
  RUNTIME = 0,
  NATIVE = 1,
  Module_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Module_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Module_IsValid(int value);
constexpr Module Module_MIN = RUNTIME;
constexpr Module Module_MAX = NATIVE;
constexpr int Module_ARRAYSIZE = Module_MAX + 1;

const std::string& Module_Name(Module value);
template<typename T>
inline const std::string& Module_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Module>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Module_Name.");
  return Module_Name(static_cast<Module>(enum_t_value));
}
bool Module_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Module* value);
// ===================================================================

class Version final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.Version) */ {
 public:
  inline Version() : Version(nullptr) {}
  ~Version() override;
  explicit PROTOBUF_CONSTEXPR Version(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Version(const Version& from);
  Version(Version&& from) noexcept
    : Version() {
    *this = ::std::move(from);
  }

  inline Version& operator=(const Version& from) {
    CopyFrom(from);
    return *this;
  }
  inline Version& operator=(Version&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Version& default_instance() {
    return *internal_default_instance();
  }
  static inline const Version* internal_default_instance() {
    return reinterpret_cast<const Version*>(
               &_Version_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Version& a, Version& b) {
    a.Swap(&b);
  }
  inline void Swap(Version* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Version* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Version* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Version>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Version& from);
  void MergeFrom(const Version& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Version* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.Version";
  }
  protected:
  explicit Version(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMajorVFieldNumber = 1,
    kMinorVFieldNumber = 2,
    kPatchVFieldNumber = 3,
  };
  // uint32 major_v = 1;
  void clear_major_v();
  uint32_t major_v() const;
  void set_major_v(uint32_t value);
  private:
  uint32_t _internal_major_v() const;
  void _internal_set_major_v(uint32_t value);
  public:

  // uint32 minor_v = 2;
  void clear_minor_v();
  uint32_t minor_v() const;
  void set_minor_v(uint32_t value);
  private:
  uint32_t _internal_minor_v() const;
  void _internal_set_minor_v(uint32_t value);
  public:

  // uint32 patch_v = 3;
  void clear_patch_v();
  uint32_t patch_v() const;
  void set_patch_v(uint32_t value);
  private:
  uint32_t _internal_patch_v() const;
  void _internal_set_patch_v(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.Version)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t major_v_;
  uint32_t minor_v_;
  uint32_t patch_v_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2ftype_2eproto;
};
// -------------------------------------------------------------------

class Environment final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.Environment) */ {
 public:
  inline Environment() : Environment(nullptr) {}
  ~Environment() override;
  explicit PROTOBUF_CONSTEXPR Environment(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Environment(const Environment& from);
  Environment(Environment&& from) noexcept
    : Environment() {
    *this = ::std::move(from);
  }

  inline Environment& operator=(const Environment& from) {
    CopyFrom(from);
    return *this;
  }
  inline Environment& operator=(Environment&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Environment& default_instance() {
    return *internal_default_instance();
  }
  static inline const Environment* internal_default_instance() {
    return reinterpret_cast<const Environment*>(
               &_Environment_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Environment& a, Environment& b) {
    a.Swap(&b);
  }
  inline void Swap(Environment* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Environment* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Environment* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Environment>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Environment& from);
  void MergeFrom(const Environment& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Environment* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.Environment";
  }
  protected:
  explicit Environment(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPidFieldNumber = 1,
    kTidFieldNumber = 2,
  };
  // uint32 pid = 1;
  void clear_pid();
  uint32_t pid() const;
  void set_pid(uint32_t value);
  private:
  uint32_t _internal_pid() const;
  void _internal_set_pid(uint32_t value);
  public:

  // uint32 tid = 2;
  void clear_tid();
  uint32_t tid() const;
  void set_tid(uint32_t value);
  private:
  uint32_t _internal_tid() const;
  void _internal_set_tid(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.Environment)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint32_t pid_;
  uint32_t tid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2ftype_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Version

// uint32 major_v = 1;
inline void Version::clear_major_v() {
  major_v_ = 0u;
}
inline uint32_t Version::_internal_major_v() const {
  return major_v_;
}
inline uint32_t Version::major_v() const {
  // @@protoc_insertion_point(field_get:axcl.Version.major_v)
  return _internal_major_v();
}
inline void Version::_internal_set_major_v(uint32_t value) {
  
  major_v_ = value;
}
inline void Version::set_major_v(uint32_t value) {
  _internal_set_major_v(value);
  // @@protoc_insertion_point(field_set:axcl.Version.major_v)
}

// uint32 minor_v = 2;
inline void Version::clear_minor_v() {
  minor_v_ = 0u;
}
inline uint32_t Version::_internal_minor_v() const {
  return minor_v_;
}
inline uint32_t Version::minor_v() const {
  // @@protoc_insertion_point(field_get:axcl.Version.minor_v)
  return _internal_minor_v();
}
inline void Version::_internal_set_minor_v(uint32_t value) {
  
  minor_v_ = value;
}
inline void Version::set_minor_v(uint32_t value) {
  _internal_set_minor_v(value);
  // @@protoc_insertion_point(field_set:axcl.Version.minor_v)
}

// uint32 patch_v = 3;
inline void Version::clear_patch_v() {
  patch_v_ = 0u;
}
inline uint32_t Version::_internal_patch_v() const {
  return patch_v_;
}
inline uint32_t Version::patch_v() const {
  // @@protoc_insertion_point(field_get:axcl.Version.patch_v)
  return _internal_patch_v();
}
inline void Version::_internal_set_patch_v(uint32_t value) {
  
  patch_v_ = value;
}
inline void Version::set_patch_v(uint32_t value) {
  _internal_set_patch_v(value);
  // @@protoc_insertion_point(field_set:axcl.Version.patch_v)
}

// -------------------------------------------------------------------

// Environment

// uint32 pid = 1;
inline void Environment::clear_pid() {
  pid_ = 0u;
}
inline uint32_t Environment::_internal_pid() const {
  return pid_;
}
inline uint32_t Environment::pid() const {
  // @@protoc_insertion_point(field_get:axcl.Environment.pid)
  return _internal_pid();
}
inline void Environment::_internal_set_pid(uint32_t value) {
  
  pid_ = value;
}
inline void Environment::set_pid(uint32_t value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:axcl.Environment.pid)
}

// uint32 tid = 2;
inline void Environment::clear_tid() {
  tid_ = 0u;
}
inline uint32_t Environment::_internal_tid() const {
  return tid_;
}
inline uint32_t Environment::tid() const {
  // @@protoc_insertion_point(field_get:axcl.Environment.tid)
  return _internal_tid();
}
inline void Environment::_internal_set_tid(uint32_t value) {
  
  tid_ = value;
}
inline void Environment::set_tid(uint32_t value) {
  _internal_set_tid(value);
  // @@protoc_insertion_point(field_set:axcl.Environment.tid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace axcl

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::axcl::Module> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2ftype_2eproto
