// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/runtime/usrwork/response.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fusrwork_2fresponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fusrwork_2fresponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "protocol/runtime/usrwork/type.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2fruntime_2fusrwork_2fresponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fruntime_2fusrwork_2fresponse_2eproto {
  static const uint32_t offsets[];
};
namespace axcl {
namespace runtime {
namespace usrwork {
namespace response {
class Body;
struct BodyDefaultTypeInternal;
extern BodyDefaultTypeInternal _Body_default_instance_;
class Head;
struct HeadDefaultTypeInternal;
extern HeadDefaultTypeInternal _Head_default_instance_;
class Payload;
struct PayloadDefaultTypeInternal;
extern PayloadDefaultTypeInternal _Payload_default_instance_;
}  // namespace response
}  // namespace usrwork
}  // namespace runtime
}  // namespace axcl
PROTOBUF_NAMESPACE_OPEN
template<> ::axcl::runtime::usrwork::response::Body* Arena::CreateMaybeMessage<::axcl::runtime::usrwork::response::Body>(Arena*);
template<> ::axcl::runtime::usrwork::response::Head* Arena::CreateMaybeMessage<::axcl::runtime::usrwork::response::Head>(Arena*);
template<> ::axcl::runtime::usrwork::response::Payload* Arena::CreateMaybeMessage<::axcl::runtime::usrwork::response::Payload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace axcl {
namespace runtime {
namespace usrwork {
namespace response {

// ===================================================================

class Head final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.usrwork.response.Head) */ {
 public:
  inline Head() : Head(nullptr) {}
  ~Head() override;
  explicit PROTOBUF_CONSTEXPR Head(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Head(const Head& from);
  Head(Head&& from) noexcept
    : Head() {
    *this = ::std::move(from);
  }

  inline Head& operator=(const Head& from) {
    CopyFrom(from);
    return *this;
  }
  inline Head& operator=(Head&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Head& default_instance() {
    return *internal_default_instance();
  }
  static inline const Head* internal_default_instance() {
    return reinterpret_cast<const Head*>(
               &_Head_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Head& a, Head& b) {
    a.Swap(&b);
  }
  inline void Swap(Head* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Head* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Head* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Head>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Head& from);
  void MergeFrom(const Head& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Head* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.usrwork.response.Head";
  }
  protected:
  explicit Head(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kApiFieldNumber = 1,
  };
  // .axcl.runtime.usrwork.Api api = 1;
  void clear_api();
  ::axcl::runtime::usrwork::Api api() const;
  void set_api(::axcl::runtime::usrwork::Api value);
  private:
  ::axcl::runtime::usrwork::Api _internal_api() const;
  void _internal_set_api(::axcl::runtime::usrwork::Api value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.usrwork.response.Head)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  int api_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fusrwork_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class Body final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.usrwork.response.Body) */ {
 public:
  inline Body() : Body(nullptr) {}
  ~Body() override;
  explicit PROTOBUF_CONSTEXPR Body(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Body(const Body& from);
  Body(Body&& from) noexcept
    : Body() {
    *this = ::std::move(from);
  }

  inline Body& operator=(const Body& from) {
    CopyFrom(from);
    return *this;
  }
  inline Body& operator=(Body&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Body& default_instance() {
    return *internal_default_instance();
  }
  static inline const Body* internal_default_instance() {
    return reinterpret_cast<const Body*>(
               &_Body_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Body& a, Body& b) {
    a.Swap(&b);
  }
  inline void Swap(Body* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Body* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Body* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Body>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Body& from);
  void MergeFrom(const Body& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Body* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.usrwork.response.Body";
  }
  protected:
  explicit Body(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 4,
    kStatusFieldNumber = 1,
    kPidFieldNumber = 2,
    kDataSizeFieldNumber = 3,
  };
  // optional bytes data = 4;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // sint32 status = 1;
  void clear_status();
  int32_t status() const;
  void set_status(int32_t value);
  private:
  int32_t _internal_status() const;
  void _internal_set_status(int32_t value);
  public:

  // optional uint32 pid = 2;
  bool has_pid() const;
  private:
  bool _internal_has_pid() const;
  public:
  void clear_pid();
  uint32_t pid() const;
  void set_pid(uint32_t value);
  private:
  uint32_t _internal_pid() const;
  void _internal_set_pid(uint32_t value);
  public:

  // optional uint32 data_size = 3;
  bool has_data_size() const;
  private:
  bool _internal_has_data_size() const;
  public:
  void clear_data_size();
  uint32_t data_size() const;
  void set_data_size(uint32_t value);
  private:
  uint32_t _internal_data_size() const;
  void _internal_set_data_size(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.runtime.usrwork.response.Body)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  int32_t status_;
  uint32_t pid_;
  uint32_t data_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fusrwork_2fresponse_2eproto;
};
// -------------------------------------------------------------------

class Payload final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.runtime.usrwork.response.Payload) */ {
 public:
  inline Payload() : Payload(nullptr) {}
  ~Payload() override;
  explicit PROTOBUF_CONSTEXPR Payload(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Payload(const Payload& from);
  Payload(Payload&& from) noexcept
    : Payload() {
    *this = ::std::move(from);
  }

  inline Payload& operator=(const Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Payload& operator=(Payload&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Payload& default_instance() {
    return *internal_default_instance();
  }
  static inline const Payload* internal_default_instance() {
    return reinterpret_cast<const Payload*>(
               &_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Payload& a, Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Payload* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Payload>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Payload& from);
  void MergeFrom(const Payload& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Payload* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.runtime.usrwork.response.Payload";
  }
  protected:
  explicit Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeadFieldNumber = 1,
    kBodyFieldNumber = 2,
  };
  // .axcl.runtime.usrwork.response.Head head = 1;
  bool has_head() const;
  private:
  bool _internal_has_head() const;
  public:
  void clear_head();
  const ::axcl::runtime::usrwork::response::Head& head() const;
  PROTOBUF_NODISCARD ::axcl::runtime::usrwork::response::Head* release_head();
  ::axcl::runtime::usrwork::response::Head* mutable_head();
  void set_allocated_head(::axcl::runtime::usrwork::response::Head* head);
  private:
  const ::axcl::runtime::usrwork::response::Head& _internal_head() const;
  ::axcl::runtime::usrwork::response::Head* _internal_mutable_head();
  public:
  void unsafe_arena_set_allocated_head(
      ::axcl::runtime::usrwork::response::Head* head);
  ::axcl::runtime::usrwork::response::Head* unsafe_arena_release_head();

  // .axcl.runtime.usrwork.response.Body body = 2;
  bool has_body() const;
  private:
  bool _internal_has_body() const;
  public:
  void clear_body();
  const ::axcl::runtime::usrwork::response::Body& body() const;
  PROTOBUF_NODISCARD ::axcl::runtime::usrwork::response::Body* release_body();
  ::axcl::runtime::usrwork::response::Body* mutable_body();
  void set_allocated_body(::axcl::runtime::usrwork::response::Body* body);
  private:
  const ::axcl::runtime::usrwork::response::Body& _internal_body() const;
  ::axcl::runtime::usrwork::response::Body* _internal_mutable_body();
  public:
  void unsafe_arena_set_allocated_body(
      ::axcl::runtime::usrwork::response::Body* body);
  ::axcl::runtime::usrwork::response::Body* unsafe_arena_release_body();

  // @@protoc_insertion_point(class_scope:axcl.runtime.usrwork.response.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::axcl::runtime::usrwork::response::Head* head_;
  ::axcl::runtime::usrwork::response::Body* body_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fruntime_2fusrwork_2fresponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Head

// .axcl.runtime.usrwork.Api api = 1;
inline void Head::clear_api() {
  api_ = 0;
}
inline ::axcl::runtime::usrwork::Api Head::_internal_api() const {
  return static_cast< ::axcl::runtime::usrwork::Api >(api_);
}
inline ::axcl::runtime::usrwork::Api Head::api() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.usrwork.response.Head.api)
  return _internal_api();
}
inline void Head::_internal_set_api(::axcl::runtime::usrwork::Api value) {
  
  api_ = value;
}
inline void Head::set_api(::axcl::runtime::usrwork::Api value) {
  _internal_set_api(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.usrwork.response.Head.api)
}

// -------------------------------------------------------------------

// Body

// sint32 status = 1;
inline void Body::clear_status() {
  status_ = 0;
}
inline int32_t Body::_internal_status() const {
  return status_;
}
inline int32_t Body::status() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.usrwork.response.Body.status)
  return _internal_status();
}
inline void Body::_internal_set_status(int32_t value) {
  
  status_ = value;
}
inline void Body::set_status(int32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.usrwork.response.Body.status)
}

// optional uint32 pid = 2;
inline bool Body::_internal_has_pid() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Body::has_pid() const {
  return _internal_has_pid();
}
inline void Body::clear_pid() {
  pid_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline uint32_t Body::_internal_pid() const {
  return pid_;
}
inline uint32_t Body::pid() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.usrwork.response.Body.pid)
  return _internal_pid();
}
inline void Body::_internal_set_pid(uint32_t value) {
  _has_bits_[0] |= 0x00000002u;
  pid_ = value;
}
inline void Body::set_pid(uint32_t value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.usrwork.response.Body.pid)
}

// optional uint32 data_size = 3;
inline bool Body::_internal_has_data_size() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Body::has_data_size() const {
  return _internal_has_data_size();
}
inline void Body::clear_data_size() {
  data_size_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline uint32_t Body::_internal_data_size() const {
  return data_size_;
}
inline uint32_t Body::data_size() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.usrwork.response.Body.data_size)
  return _internal_data_size();
}
inline void Body::_internal_set_data_size(uint32_t value) {
  _has_bits_[0] |= 0x00000004u;
  data_size_ = value;
}
inline void Body::set_data_size(uint32_t value) {
  _internal_set_data_size(value);
  // @@protoc_insertion_point(field_set:axcl.runtime.usrwork.response.Body.data_size)
}

// optional bytes data = 4;
inline bool Body::_internal_has_data() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Body::has_data() const {
  return _internal_has_data();
}
inline void Body::clear_data() {
  data_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Body::data() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.usrwork.response.Body.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Body::set_data(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:axcl.runtime.usrwork.response.Body.data)
}
inline std::string* Body::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.usrwork.response.Body.data)
  return _s;
}
inline const std::string& Body::_internal_data() const {
  return data_.Get();
}
inline void Body::_internal_set_data(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  data_.Set(value, GetArenaForAllocation());
}
inline std::string* Body::_internal_mutable_data() {
  _has_bits_[0] |= 0x00000001u;
  return data_.Mutable(GetArenaForAllocation());
}
inline std::string* Body::release_data() {
  // @@protoc_insertion_point(field_release:axcl.runtime.usrwork.response.Body.data)
  if (!_internal_has_data()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = data_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault()) {
    data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Body::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault()) {
    data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.usrwork.response.Body.data)
}

// -------------------------------------------------------------------

// Payload

// .axcl.runtime.usrwork.response.Head head = 1;
inline bool Payload::_internal_has_head() const {
  return this != internal_default_instance() && head_ != nullptr;
}
inline bool Payload::has_head() const {
  return _internal_has_head();
}
inline void Payload::clear_head() {
  if (GetArenaForAllocation() == nullptr && head_ != nullptr) {
    delete head_;
  }
  head_ = nullptr;
}
inline const ::axcl::runtime::usrwork::response::Head& Payload::_internal_head() const {
  const ::axcl::runtime::usrwork::response::Head* p = head_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::usrwork::response::Head&>(
      ::axcl::runtime::usrwork::response::_Head_default_instance_);
}
inline const ::axcl::runtime::usrwork::response::Head& Payload::head() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.usrwork.response.Payload.head)
  return _internal_head();
}
inline void Payload::unsafe_arena_set_allocated_head(
    ::axcl::runtime::usrwork::response::Head* head) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(head_);
  }
  head_ = head;
  if (head) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.usrwork.response.Payload.head)
}
inline ::axcl::runtime::usrwork::response::Head* Payload::release_head() {
  
  ::axcl::runtime::usrwork::response::Head* temp = head_;
  head_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::usrwork::response::Head* Payload::unsafe_arena_release_head() {
  // @@protoc_insertion_point(field_release:axcl.runtime.usrwork.response.Payload.head)
  
  ::axcl::runtime::usrwork::response::Head* temp = head_;
  head_ = nullptr;
  return temp;
}
inline ::axcl::runtime::usrwork::response::Head* Payload::_internal_mutable_head() {
  
  if (head_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::usrwork::response::Head>(GetArenaForAllocation());
    head_ = p;
  }
  return head_;
}
inline ::axcl::runtime::usrwork::response::Head* Payload::mutable_head() {
  ::axcl::runtime::usrwork::response::Head* _msg = _internal_mutable_head();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.usrwork.response.Payload.head)
  return _msg;
}
inline void Payload::set_allocated_head(::axcl::runtime::usrwork::response::Head* head) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete head_;
  }
  if (head) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(head);
    if (message_arena != submessage_arena) {
      head = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, head, submessage_arena);
    }
    
  } else {
    
  }
  head_ = head;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.usrwork.response.Payload.head)
}

// .axcl.runtime.usrwork.response.Body body = 2;
inline bool Payload::_internal_has_body() const {
  return this != internal_default_instance() && body_ != nullptr;
}
inline bool Payload::has_body() const {
  return _internal_has_body();
}
inline void Payload::clear_body() {
  if (GetArenaForAllocation() == nullptr && body_ != nullptr) {
    delete body_;
  }
  body_ = nullptr;
}
inline const ::axcl::runtime::usrwork::response::Body& Payload::_internal_body() const {
  const ::axcl::runtime::usrwork::response::Body* p = body_;
  return p != nullptr ? *p : reinterpret_cast<const ::axcl::runtime::usrwork::response::Body&>(
      ::axcl::runtime::usrwork::response::_Body_default_instance_);
}
inline const ::axcl::runtime::usrwork::response::Body& Payload::body() const {
  // @@protoc_insertion_point(field_get:axcl.runtime.usrwork.response.Payload.body)
  return _internal_body();
}
inline void Payload::unsafe_arena_set_allocated_body(
    ::axcl::runtime::usrwork::response::Body* body) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  body_ = body;
  if (body) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:axcl.runtime.usrwork.response.Payload.body)
}
inline ::axcl::runtime::usrwork::response::Body* Payload::release_body() {
  
  ::axcl::runtime::usrwork::response::Body* temp = body_;
  body_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::axcl::runtime::usrwork::response::Body* Payload::unsafe_arena_release_body() {
  // @@protoc_insertion_point(field_release:axcl.runtime.usrwork.response.Payload.body)
  
  ::axcl::runtime::usrwork::response::Body* temp = body_;
  body_ = nullptr;
  return temp;
}
inline ::axcl::runtime::usrwork::response::Body* Payload::_internal_mutable_body() {
  
  if (body_ == nullptr) {
    auto* p = CreateMaybeMessage<::axcl::runtime::usrwork::response::Body>(GetArenaForAllocation());
    body_ = p;
  }
  return body_;
}
inline ::axcl::runtime::usrwork::response::Body* Payload::mutable_body() {
  ::axcl::runtime::usrwork::response::Body* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:axcl.runtime.usrwork.response.Payload.body)
  return _msg;
}
inline void Payload::set_allocated_body(::axcl::runtime::usrwork::response::Body* body) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete body_;
  }
  if (body) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(body);
    if (message_arena != submessage_arena) {
      body = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body, submessage_arena);
    }
    
  } else {
    
  }
  body_ = body;
  // @@protoc_insertion_point(field_set_allocated:axcl.runtime.usrwork.response.Payload.body)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace response
}  // namespace usrwork
}  // namespace runtime
}  // namespace axcl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fusrwork_2fresponse_2eproto
