// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/runtime/usrwork/type.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fusrwork_2ftype_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fusrwork_2ftype_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2fruntime_2fusrwork_2ftype_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fruntime_2fusrwork_2ftype_2eproto {
  static const uint32_t offsets[];
};
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace axcl {
namespace runtime {
namespace usrwork {

enum FileTransferPolicy : int {
  FILE_TRANSFER_FROM_HOST_TO_DEVICE = 0,
  FILE_TRANSFER_FROM_DEVICE_TO_HOST = 1,
  FILE_TRANSFER_FROM_DEVICE_TO_DEVICE = 2,
  FILE_TRANSFER_REMOVE_DEVICE_FILE = 3,
  FileTransferPolicy_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  FileTransferPolicy_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool FileTransferPolicy_IsValid(int value);
constexpr FileTransferPolicy FileTransferPolicy_MIN = FILE_TRANSFER_FROM_HOST_TO_DEVICE;
constexpr FileTransferPolicy FileTransferPolicy_MAX = FILE_TRANSFER_REMOVE_DEVICE_FILE;
constexpr int FileTransferPolicy_ARRAYSIZE = FileTransferPolicy_MAX + 1;

const std::string& FileTransferPolicy_Name(FileTransferPolicy value);
template<typename T>
inline const std::string& FileTransferPolicy_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FileTransferPolicy>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FileTransferPolicy_Name.");
  return FileTransferPolicy_Name(static_cast<FileTransferPolicy>(enum_t_value));
}
bool FileTransferPolicy_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, FileTransferPolicy* value);
enum Api : int {
  TRANSFER_FILE = 0,
  EXEC_WORKER = 1,
  KILL_WORKER = 2,
  WORKER_SEND = 3,
  WORKER_RECV = 4,
  Api_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Api_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Api_IsValid(int value);
constexpr Api Api_MIN = TRANSFER_FILE;
constexpr Api Api_MAX = WORKER_RECV;
constexpr int Api_ARRAYSIZE = Api_MAX + 1;

const std::string& Api_Name(Api value);
template<typename T>
inline const std::string& Api_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Api>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Api_Name.");
  return Api_Name(static_cast<Api>(enum_t_value));
}
bool Api_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Api* value);
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace usrwork
}  // namespace runtime
}  // namespace axcl

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::axcl::runtime::usrwork::FileTransferPolicy> : ::std::true_type {};
template <> struct is_proto_enum< ::axcl::runtime::usrwork::Api> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2fruntime_2fusrwork_2ftype_2eproto
