// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/native/module/sys.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2fnative_2fmodule_2fsys_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2fnative_2fmodule_2fsys_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2fnative_2fmodule_2fsys_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2fnative_2fmodule_2fsys_2eproto {
  static const uint32_t offsets[];
};
namespace axcl {
namespace native {
namespace module {
namespace sys {
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace sys
}  // namespace module
}  // namespace native
}  // namespace axcl
PROTOBUF_NAMESPACE_OPEN
template<> ::axcl::native::module::sys::Request* Arena::CreateMaybeMessage<::axcl::native::module::sys::Request>(Arena*);
template<> ::axcl::native::module::sys::Response* Arena::CreateMaybeMessage<::axcl::native::module::sys::Response>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace axcl {
namespace native {
namespace module {
namespace sys {

enum Api : int {
  AX_SYS_Init = 0,
  AX_SYS_Deinit = 1,
  AX_SYS_MemAlloc = 2,
  AX_SYS_MemAllocCached = 3,
  AX_SYS_MemFree = 4,
  AX_SYS_Mmap = 5,
  AX_SYS_MmapCache = 6,
  AX_SYS_MmapFast = 7,
  AX_SYS_MmapCacheFast = 8,
  AX_SYS_Munmap = 9,
  AX_SYS_MflushCache = 10,
  AX_SYS_MinvalidateCache = 11,
  AX_SYS_MemGetBlockInfoByPhy = 12,
  AX_SYS_MemGetBlockInfoByVirt = 13,
  AX_SYS_MemGetPartitionInfo = 14,
  AX_SYS_MemSetConfig = 15,
  AX_SYS_MemGetConfig = 16,
  AX_SYS_MemQueryStatus = 17,
  AX_SYS_Link = 31,
  AX_SYS_UnLink = 32,
  AX_SYS_GetLinkByDest = 33,
  AX_SYS_GetLinkBySrc = 34,
  AX_POOL_SetConfig = 41,
  AX_POOL_GetConfig = 42,
  AX_POOL_Init = 43,
  AX_POOL_Exit = 44,
  AX_POOL_CreatePool = 45,
  AX_POOL_DestroyPool = 46,
  AX_POOL_GetBlock = 47,
  AX_POOL_ReleaseBlock = 48,
  AX_POOL_PhysAddr2Handle = 49,
  AX_POOL_Handle2PhysAddr = 50,
  AX_POOL_Handle2MetaPhysAddr = 51,
  AX_POOL_Handle2PoolId = 52,
  AX_POOL_Handle2BlkSize = 53,
  AX_POOL_MmapPool = 54,
  AX_POOL_MunmapPool = 55,
  AX_POOL_GetBlockVirAddr = 56,
  AX_POOL_GetMetaVirAddr = 57,
  AX_POOL_IncreaseRefCnt = 58,
  AX_POOL_DecreaseRefCnt = 59,
  AX_SYS_GetCurPTS = 71,
  AX_SYS_InitPTSBase = 72,
  AX_SYS_SyncPTS = 73,
  AX_SYS_GetChipType = 81,
  AX_SYS_SetLogLevel = 91,
  AX_SYS_SetLogTarget = 92,
  AX_SYS_EnableTimestamp = 93,
  AX_SYS_Sleep = 101,
  AX_SYS_WakeLock = 102,
  AX_SYS_WakeUnlock = 103,
  AX_SYS_RegisterEventCb = 104,
  AX_SYS_UnregisterEventCb = 105,
  Api_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Api_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Api_IsValid(int value);
constexpr Api Api_MIN = AX_SYS_Init;
constexpr Api Api_MAX = AX_SYS_UnregisterEventCb;
constexpr int Api_ARRAYSIZE = Api_MAX + 1;

const std::string& Api_Name(Api value);
template<typename T>
inline const std::string& Api_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Api>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Api_Name.");
  return Api_Name(static_cast<Api>(enum_t_value));
}
bool Api_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Api* value);
// ===================================================================

class Request final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.native.module.sys.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  ~Request() override;
  explicit PROTOBUF_CONSTEXPR Request(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Request& default_instance() {
    return *internal_default_instance();
  }
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Request* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Request* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.native.module.sys.Request";
  }
  protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParametersFieldNumber = 2,
    kApiFieldNumber = 1,
  };
  // repeated bytes parameters = 2;
  int parameters_size() const;
  private:
  int _internal_parameters_size() const;
  public:
  void clear_parameters();
  const std::string& parameters(int index) const;
  std::string* mutable_parameters(int index);
  void set_parameters(int index, const std::string& value);
  void set_parameters(int index, std::string&& value);
  void set_parameters(int index, const char* value);
  void set_parameters(int index, const void* value, size_t size);
  std::string* add_parameters();
  void add_parameters(const std::string& value);
  void add_parameters(std::string&& value);
  void add_parameters(const char* value);
  void add_parameters(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& parameters() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_parameters();
  private:
  const std::string& _internal_parameters(int index) const;
  std::string* _internal_add_parameters();
  public:

  // .axcl.native.module.sys.Api api = 1;
  void clear_api();
  ::axcl::native::module::sys::Api api() const;
  void set_api(::axcl::native::module::sys::Api value);
  private:
  ::axcl::native::module::sys::Api _internal_api() const;
  void _internal_set_api(::axcl::native::module::sys::Api value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.native.module.sys.Request)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> parameters_;
  int api_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fnative_2fmodule_2fsys_2eproto;
};
// -------------------------------------------------------------------

class Response final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:axcl.native.module.sys.Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  ~Response() override;
  explicit PROTOBUF_CONSTEXPR Response(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Response& default_instance() {
    return *internal_default_instance();
  }
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Response* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "axcl.native.module.sys.Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kParametersFieldNumber = 2,
    kApiFieldNumber = 1,
  };
  // repeated bytes parameters = 2;
  int parameters_size() const;
  private:
  int _internal_parameters_size() const;
  public:
  void clear_parameters();
  const std::string& parameters(int index) const;
  std::string* mutable_parameters(int index);
  void set_parameters(int index, const std::string& value);
  void set_parameters(int index, std::string&& value);
  void set_parameters(int index, const char* value);
  void set_parameters(int index, const void* value, size_t size);
  std::string* add_parameters();
  void add_parameters(const std::string& value);
  void add_parameters(std::string&& value);
  void add_parameters(const char* value);
  void add_parameters(const void* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& parameters() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_parameters();
  private:
  const std::string& _internal_parameters(int index) const;
  std::string* _internal_add_parameters();
  public:

  // .axcl.native.module.sys.Api api = 1;
  void clear_api();
  ::axcl::native::module::sys::Api api() const;
  void set_api(::axcl::native::module::sys::Api value);
  private:
  ::axcl::native::module::sys::Api _internal_api() const;
  void _internal_set_api(::axcl::native::module::sys::Api value);
  public:

  // @@protoc_insertion_point(class_scope:axcl.native.module.sys.Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> parameters_;
  int api_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protocol_2fnative_2fmodule_2fsys_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// .axcl.native.module.sys.Api api = 1;
inline void Request::clear_api() {
  api_ = 0;
}
inline ::axcl::native::module::sys::Api Request::_internal_api() const {
  return static_cast< ::axcl::native::module::sys::Api >(api_);
}
inline ::axcl::native::module::sys::Api Request::api() const {
  // @@protoc_insertion_point(field_get:axcl.native.module.sys.Request.api)
  return _internal_api();
}
inline void Request::_internal_set_api(::axcl::native::module::sys::Api value) {
  
  api_ = value;
}
inline void Request::set_api(::axcl::native::module::sys::Api value) {
  _internal_set_api(value);
  // @@protoc_insertion_point(field_set:axcl.native.module.sys.Request.api)
}

// repeated bytes parameters = 2;
inline int Request::_internal_parameters_size() const {
  return parameters_.size();
}
inline int Request::parameters_size() const {
  return _internal_parameters_size();
}
inline void Request::clear_parameters() {
  parameters_.Clear();
}
inline std::string* Request::add_parameters() {
  std::string* _s = _internal_add_parameters();
  // @@protoc_insertion_point(field_add_mutable:axcl.native.module.sys.Request.parameters)
  return _s;
}
inline const std::string& Request::_internal_parameters(int index) const {
  return parameters_.Get(index);
}
inline const std::string& Request::parameters(int index) const {
  // @@protoc_insertion_point(field_get:axcl.native.module.sys.Request.parameters)
  return _internal_parameters(index);
}
inline std::string* Request::mutable_parameters(int index) {
  // @@protoc_insertion_point(field_mutable:axcl.native.module.sys.Request.parameters)
  return parameters_.Mutable(index);
}
inline void Request::set_parameters(int index, const std::string& value) {
  parameters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:axcl.native.module.sys.Request.parameters)
}
inline void Request::set_parameters(int index, std::string&& value) {
  parameters_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:axcl.native.module.sys.Request.parameters)
}
inline void Request::set_parameters(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  parameters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:axcl.native.module.sys.Request.parameters)
}
inline void Request::set_parameters(int index, const void* value, size_t size) {
  parameters_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:axcl.native.module.sys.Request.parameters)
}
inline std::string* Request::_internal_add_parameters() {
  return parameters_.Add();
}
inline void Request::add_parameters(const std::string& value) {
  parameters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:axcl.native.module.sys.Request.parameters)
}
inline void Request::add_parameters(std::string&& value) {
  parameters_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:axcl.native.module.sys.Request.parameters)
}
inline void Request::add_parameters(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  parameters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:axcl.native.module.sys.Request.parameters)
}
inline void Request::add_parameters(const void* value, size_t size) {
  parameters_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:axcl.native.module.sys.Request.parameters)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Request::parameters() const {
  // @@protoc_insertion_point(field_list:axcl.native.module.sys.Request.parameters)
  return parameters_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Request::mutable_parameters() {
  // @@protoc_insertion_point(field_mutable_list:axcl.native.module.sys.Request.parameters)
  return &parameters_;
}

// -------------------------------------------------------------------

// Response

// .axcl.native.module.sys.Api api = 1;
inline void Response::clear_api() {
  api_ = 0;
}
inline ::axcl::native::module::sys::Api Response::_internal_api() const {
  return static_cast< ::axcl::native::module::sys::Api >(api_);
}
inline ::axcl::native::module::sys::Api Response::api() const {
  // @@protoc_insertion_point(field_get:axcl.native.module.sys.Response.api)
  return _internal_api();
}
inline void Response::_internal_set_api(::axcl::native::module::sys::Api value) {
  
  api_ = value;
}
inline void Response::set_api(::axcl::native::module::sys::Api value) {
  _internal_set_api(value);
  // @@protoc_insertion_point(field_set:axcl.native.module.sys.Response.api)
}

// repeated bytes parameters = 2;
inline int Response::_internal_parameters_size() const {
  return parameters_.size();
}
inline int Response::parameters_size() const {
  return _internal_parameters_size();
}
inline void Response::clear_parameters() {
  parameters_.Clear();
}
inline std::string* Response::add_parameters() {
  std::string* _s = _internal_add_parameters();
  // @@protoc_insertion_point(field_add_mutable:axcl.native.module.sys.Response.parameters)
  return _s;
}
inline const std::string& Response::_internal_parameters(int index) const {
  return parameters_.Get(index);
}
inline const std::string& Response::parameters(int index) const {
  // @@protoc_insertion_point(field_get:axcl.native.module.sys.Response.parameters)
  return _internal_parameters(index);
}
inline std::string* Response::mutable_parameters(int index) {
  // @@protoc_insertion_point(field_mutable:axcl.native.module.sys.Response.parameters)
  return parameters_.Mutable(index);
}
inline void Response::set_parameters(int index, const std::string& value) {
  parameters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:axcl.native.module.sys.Response.parameters)
}
inline void Response::set_parameters(int index, std::string&& value) {
  parameters_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:axcl.native.module.sys.Response.parameters)
}
inline void Response::set_parameters(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  parameters_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:axcl.native.module.sys.Response.parameters)
}
inline void Response::set_parameters(int index, const void* value, size_t size) {
  parameters_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:axcl.native.module.sys.Response.parameters)
}
inline std::string* Response::_internal_add_parameters() {
  return parameters_.Add();
}
inline void Response::add_parameters(const std::string& value) {
  parameters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:axcl.native.module.sys.Response.parameters)
}
inline void Response::add_parameters(std::string&& value) {
  parameters_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:axcl.native.module.sys.Response.parameters)
}
inline void Response::add_parameters(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  parameters_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:axcl.native.module.sys.Response.parameters)
}
inline void Response::add_parameters(const void* value, size_t size) {
  parameters_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:axcl.native.module.sys.Response.parameters)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Response::parameters() const {
  // @@protoc_insertion_point(field_list:axcl.native.module.sys.Response.parameters)
  return parameters_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Response::mutable_parameters() {
  // @@protoc_insertion_point(field_mutable_list:axcl.native.module.sys.Response.parameters)
  return &parameters_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sys
}  // namespace module
}  // namespace native
}  // namespace axcl

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::axcl::native::module::sys::Api> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2fnative_2fmodule_2fsys_2eproto
